package component:component;

world wasm-tools {
    export parse: func(contents: string) -> result<list<u8>, string>;

    variant print-part {
        str(string),
        name,
        literal,
        keyword,
        %type,
        comment,
        reset,
    }
    export print: func(contents: list<u8>, skeleton: bool) -> result<list<print-part>, string>;
}
