(component
  (core module $main (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (import "env" "__wasm_get_stack_pointer" (func (;0;) (type 0)))
    (import "env" "__wasm_set_stack_pointer" (func (;1;) (type 1)))
    (import "env" "__wasm_get_tls_base" (func (;2;) (type 0)))
    (import "env" "__wasm_set_tls_base" (func (;3;) (type 1)))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (global (;0;) (mut i32) i32.const 0)
    (export "$get-tls-base" (func $$get-tls-base))
    (export "$set-tls-base" (func $$set-tls-base))
    (func $$get-tls-base (;0;) (type 0) (result i32)
      global.get 0
    )
    (func $$set-tls-base (;1;) (type 1) (param i32)
      local.get 0
      global.set 0
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (core func $"context.get 0" (;0;) (canon context.get i32 0))
  (core func $"context.set 0" (;1;) (canon context.set i32 0))
  (alias core export $wit-component-shim-instance "$get-tls-base" (core func $$get-tls-base (;2;)))
  (alias core export $wit-component-shim-instance "$set-tls-base" (core func $$set-tls-base (;3;)))
  (core instance $env (;1;)
    (export "__wasm_get_stack_pointer" (func $"context.get 0"))
    (export "__wasm_set_stack_pointer" (func $"context.set 0"))
    (export "__wasm_get_tls_base" (func $$get-tls-base))
    (export "__wasm_set_tls_base" (func $$set-tls-base))
  )
  (core instance $main (;2;) (instantiate $main
      (with "env" (instance $env))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
