(component
  (core module $main (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32)))
    (table (;0;) 3 funcref)
    (memory (;0;) 17)
    (tag (;0;) (type 1) (param i32))
    (tag (;1;) (type 2) (param i32 i32))
    (global (;0;) (mut i32) i32.const 1048576)
    (global (;1;) (mut i32) i32.const 1048576)
    (global (;2;) (mut i32) i32.const 0)
    (global (;3;) i32 i32.const 1048584)
    (global (;4;) i32 i32.const 2)
    (global (;5;) i32 i32.const 1048584)
    (global (;6;) i32 i32.const 2)
    (global (;7;) (mut i32) i32.const 2)
    (global (;8;) (mut i32) i32.const 1048592)
    (global (;9;) (mut i32) i32.const 1114112)
    (export "__stack_pointer" (global 0))
    (export "__stack_high" (global 1))
    (export "__stack_low" (global 2))
    (export "bar:memory_base" (global 3))
    (export "bar:table_base" (global 4))
    (export "foo:memory_base" (global 5))
    (export "foo:table_base" (global 6))
    (export "foo:bar" (global 7))
    (export "__heap_base" (global 8))
    (export "__heap_end" (global 9))
    (export "bar" (func 0))
    (export "tag1" (tag 0))
    (export "tag2" (tag 1))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (func (;0;) (type 0)
      i32.const 2
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $bar (;1;)
    (@dylink.0)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func))
    (tag $tag1 (;0;) (type 0) (param i32))
    (tag $tag2 (;1;) (type 1) (param i32 i32))
    (export "tag1" (tag 0))
    (export "tag2" (tag 1))
    (export "bar" (func $bar))
    (func $bar (;0;) (type 2)
      unreachable
    )
  )
  (core module $foo (;2;)
    (@dylink.0
      (needed "bar")
    )
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func))
    (import "env" "tag1" (tag (;0;) (type 0) (param i32)))
    (import "env" "tag2" (tag (;1;) (type 1) (param i32 i32)))
    (import "GOT.func" "bar" (global (;0;) (mut i32)))
    (export "run" (func 0))
    (func (;0;) (type 2)
      unreachable
    )
  )
  (core module $__init (;3;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func))
    (import "env" "memory" (memory (;0;) 0))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "bar" "bar" (func (;0;) (type 2)))
    (start 1)
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 2) func 0)
    (func (;1;) (type 0))
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core instance $bar (;1;) (instantiate $bar))
  (alias core export $main "tag1" (core tag $tag1 (;0;)))
  (alias core export $main "tag2" (core tag $tag2 (;1;)))
  (core instance $env (;2;)
    (export "tag1" (tag 0))
    (export "tag2" (tag 1))
  )
  (alias core export $main "foo:bar" (core global $foo:bar (;0;)))
  (core instance $GOT.func (;3;)
    (export "bar" (global $foo:bar))
  )
  (core instance $foo (;4;) (instantiate $foo
      (with "env" (instance $env))
      (with "GOT.func" (instance $GOT.func))
    )
  )
  (core instance $__init (;5;) (instantiate $__init
      (with "env" (instance $main))
      (with "bar" (instance $bar))
    )
  )
  (type (;0;) (func))
  (alias core export $foo "run" (core func $run (;0;)))
  (func $run (;0;) (type 0) (canon lift (core func $run)))
  (export $"#func1 run" (@name "run") (;1;) "run" (func $run))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
