(component
  (core module $main (;0;)
    (type (;0;) (func))
    (table (;0;) 3 funcref)
    (memory (;0;) 17)
    (global (;0;) i32 i32.const 1048584)
    (global (;1;) i32 i32.const 2)
    (global (;2;) i32 i32.const 1048584)
    (global (;3;) i32 i32.const 2)
    (global (;4;) (mut i32) i32.const 2)
    (export "bar:memory_base" (global 0))
    (export "bar:table_base" (global 1))
    (export "foo:memory_base" (global 2))
    (export "foo:table_base" (global 3))
    (export "foo:bar" (global 4))
    (export "bar" (func 0))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (func (;0;) (type 0)
      i32.const 2
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $bar (;1;)
    (@dylink.0)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func))
    (tag $tag1 (;0;) (type 0) (param i32))
    (tag $tag2 (;1;) (type 1) (param i32 i32))
    (export "tag1" (tag 0))
    (export "tag2" (tag 1))
    (export "bar" (func $bar))
    (func $bar (;0;) (type 2)
      unreachable
    )
  )
  (core module $foo (;2;)
    (@dylink.0
      (needed "bar")
    )
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func))
    (import "env" "tag1" (tag (;0;) (type 0) (param i32)))
    (import "env" "tag2" (tag (;1;) (type 1) (param i32 i32)))
    (import "GOT.func" "bar" (global (;0;) (mut i32)))
    (export "run" (func 0))
    (func (;0;) (type 2)
      unreachable
    )
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core instance $bar (;1;) (instantiate $bar))
  (alias core export $bar "tag1" (core tag $tag1 (;0;)))
  (alias core export $bar "tag2" (core tag $tag2 (;1;)))
  (core instance $env (;2;)
    (export "tag1" (tag 0))
    (export "tag2" (tag 1))
  )
  (alias core export $main "foo:bar" (core global $foo:bar (;0;)))
  (core instance $GOT.func (;3;)
    (export "bar" (global $foo:bar))
  )
  (core instance $foo (;4;) (instantiate $foo
      (with "env" (instance $env))
      (with "GOT.func" (instance $GOT.func))
    )
  )
  (core module $wit-component-fixup (;3;)
    (type (;0;) (func))
    (import "main" "memory" (memory (;0;) 0))
    (import "main" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "bar" "bar" (func $bar (;0;) (type 0)))
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 2) func $bar)
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "main" (instance $main))
      (with "bar" (instance $bar))
    )
  )
  (type (;0;) (func))
  (alias core export $foo "run" (core func $run (;0;)))
  (func $run (;0;) (type 0) (canon lift (core func $run)))
  (export $"#func1 run" (@name "run") (;1;) "run" (func $run))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
