(component
  (core module (;0;)
    (type (;0;) (func))
    (type (;1;) (func))
    (type (;2;) (func))
    (type (;3;) (func))
    (table (;0;) 3 funcref)
    (memory (;0;) 17)
    (tag (;0;) (type 1))
    (tag (;1;) (type 2))
    (tag (;2;) (type 3))
    (global (;0;) (mut i32) i32.const 1048576)
    (global (;1;) i32 i32.const 1048584)
    (global (;2;) i32 i32.const 2)
    (global (;3;) i32 i32.const 1048584)
    (global (;4;) i32 i32.const 2)
    (global (;5;) (mut i32) i32.const 2)
    (global (;6;) (mut i32) i32.const 1048592)
    (global (;7;) (mut i32) i32.const 1114112)
    (export "__stack_pointer" (global 0))
    (export "bar:memory_base" (global 1))
    (export "bar:table_base" (global 2))
    (export "foo:memory_base" (global 3))
    (export "foo:table_base" (global 4))
    (export "foo:bar" (global 5))
    (export "__heap_base" (global 6))
    (export "__heap_end" (global 7))
    (export "bar" (func 0))
    (export "tag2" (tag 0))
    (export "tag3" (tag 1))
    (export "tag1" (tag 2))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (func (;0;) (type 0)
      i32.const 2
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;1;)
    (@dylink.0)
    (type (;0;) (func))
    (import "env" "tag2" (tag (;0;) (type 0)))
    (import "env" "tag3" (tag (;1;) (type 0)))
    (export "bar" (func $bar))
    (func $bar (;0;) (type 0)
      unreachable
    )
  )
  (core module (;2;)
    (@dylink.0
      (needed "bar")
    )
    (type (;0;) (func))
    (import "env" "tag1" (tag (;0;) (type 0)))
    (import "env" "tag2" (tag (;1;) (type 0)))
    (import "GOT.func" "bar" (global (;0;) (mut i32)))
    (export "run" (func 0))
    (func (;0;) (type 0)
      unreachable
    )
  )
  (core module (;3;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func))
    (import "env" "memory" (memory (;0;) 0))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "bar" "bar" (func (;0;) (type 2)))
    (start 1)
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 2) func 0)
    (func (;1;) (type 0))
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (alias core export 0 "tag2" (core tag (;0;)))
  (alias core export 0 "tag3" (core tag (;1;)))
  (core instance (;1;)
    (export "tag2" (tag 0))
    (export "tag3" (tag 1))
  )
  (core instance (;2;) (instantiate 1
      (with "env" (instance 1))
    )
  )
  (alias core export 0 "tag1" (core tag (;2;)))
  (core instance (;3;)
    (export "tag1" (tag 2))
    (export "tag2" (tag 0))
  )
  (alias core export 0 "foo:bar" (core global (;0;)))
  (core instance (;4;)
    (export "bar" (global 0))
  )
  (core instance (;5;) (instantiate 2
      (with "env" (instance 3))
      (with "GOT.func" (instance 4))
    )
  )
  (core instance (;6;) (instantiate 3
      (with "env" (instance 0))
      (with "bar" (instance 2))
    )
  )
  (type (;0;) (func))
  (alias core export 5 "run" (core func (;0;)))
  (func (;0;) (type 0) (canon lift (core func 0)))
  (export (;1;) "run" (func 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
