(component
  (core module $main (;0;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32)))
    (import "$root" "[future-forward-0]foo" (func (;0;) (type 0)))
    (import "$root" "[stream-forward-1]foo" (func (;1;) (type 0)))
    (import "[export]$root" "[future-forward-0]foo" (func (;2;) (type 0)))
    (import "[export]$root" "[stream-forward-1]foo" (func (;3;) (type 0)))
    (export "[async-lift-stackful]foo" (func 4))
    (func (;4;) (type 1) (param i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (type (;0;) (future u32))
  (core func $future.forward (;0;) (canon future.forward 0))
  (type (;1;) (stream u32))
  (core func $stream.forward (;1;) (canon stream.forward 1))
  (core instance $$root (;0;)
    (export "[future-forward-0]foo" (func $future.forward))
    (export "[stream-forward-1]foo" (func $stream.forward))
  )
  (core func $"#core-func2 future.forward" (@name "future.forward") (;2;) (canon future.forward 0))
  (core func $"#core-func3 stream.forward" (@name "stream.forward") (;3;) (canon stream.forward 1))
  (core instance $"[export]$root" (;1;)
    (export "[future-forward-0]foo" (func $"#core-func2 future.forward"))
    (export "[stream-forward-1]foo" (func $"#core-func3 stream.forward"))
  )
  (core instance $main (;2;) (instantiate $main
      (with "$root" (instance $$root))
      (with "[export]$root" (instance $"[export]$root"))
    )
  )
  (type (;2;) (func async (param "x" 0) (result 1)))
  (alias core export $main "[async-lift-stackful]foo" (core func $"[async-lift-stackful]foo" (;4;)))
  (func $foo (;0;) (type 2) (canon lift (core func $"[async-lift-stackful]foo") async))
  (export $"#func1 foo" (@name "foo") (;1;) "foo" (func $foo))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
