(component
  (type (;0;) (record (field "a" u32)))
  (type (;1;) (func (param "a" 0) (result string)))
  (core module (;0;)
    (type (;0;) (func (param i32) (result i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (func (;0;) (type 0) (param i32) (result i32)
      unreachable
    )
    (func (;1;) (type 1) (param i32))
    (func (;2;) (type 2) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "foo#my-function" (func 0))
    (export "cabi_post_foo#my-function" (func 1))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 2))
  )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (alias core export 0 "cabi_realloc" (core func (;0;)))
  (alias core export 0 "foo#my-function" (core func (;1;)))
  (alias core export 0 "cabi_post_foo#my-function" (core func (;2;)))
  (func (;0;) (type 1) (canon lift (core func 1) (memory 0) string-encoding=utf8 (post-return 2)))
  (instance (;0;)
    (export "my-struct" (type 0))
    (export "my-function" (func 0))
  )
  (export "foo" (instance 0))
)