(component
  (core module (;0;)
    (type $thread-start-func-ty (;0;) (func (param i32)))
    (type (;1;) (func))
    (type (;2;) (func (param i32 i32)))
    (type (;3;) (func (result i32)))
    (type (;4;) (func (param i32 i32) (result i32)))
    (type (;5;) (func (param i32) (result i32)))
    (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
    (import "[export]$root" "[task-cancel]" (func (;0;) (type 1)))
    (import "[export]$root" "[task-return]foo" (func (;1;) (type 2)))
    (import "[export]foo:foo/bar" "[task-return]foo" (func (;2;) (type 2)))
    (import "$root" "[context-get-1]" (func (;3;) (type 3)))
    (import "$root" "[context-set-1]" (func (;4;) (type $thread-start-func-ty)))
    (import "$root" "[thread-index]" (func (;5;) (type 3)))
    (import "$root" "[thread-new-indirect-v0]" (func (;6;) (type 4)))
    (import "$root" "[thread-switch-to]" (func (;7;) (type 5)))
    (import "$root" "[thread-suspend]" (func (;8;) (type 3)))
    (import "$root" "[thread-resume-later]" (func (;9;) (type $thread-start-func-ty)))
    (import "$root" "[thread-yield-to]" (func (;10;) (type 5)))
    (table (;0;) 1 1 funcref)
    (memory (;0;) 1)
    (export "thread_main" (func 11))
    (export "[async-lift-stackful]foo" (func 12))
    (export "[async-lift-stackful]foo:foo/bar#foo" (func 13))
    (export "memory" (memory 0))
    (export "__indirect_function_table" (table 0))
    (export "cabi_realloc" (func 14))
    (elem (;0;) (i32.const 0) func 0)
    (func (;11;) (type $thread-start-func-ty) (param i32)
      unreachable
    )
    (func (;12;) (type 2) (param i32 i32)
      unreachable
    )
    (func (;13;) (type 2) (param i32 i32)
      unreachable
    )
    (func (;14;) (type 6) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32) (result i32)))
    (table (;0;) 3 3 funcref)
    (export "0" (func $task-return-foo))
    (export "1" (func $"#func1 task-return-foo"))
    (export "2" (func $thread.new_indirect))
    (export "$imports" (table 0))
    (func $task-return-foo (;0;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (func $"#func1 task-return-foo" (@name "task-return-foo") (;1;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 1
      call_indirect (type 0)
    )
    (func $thread.new_indirect (;2;) (type 1) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 2
      call_indirect (type 1)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32) (result i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "2" (func (;2;) (type 1)))
    (import "" "$imports" (table (;0;) 3 3 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 1))
  (core func (;0;) (canon task.cancel))
  (alias core export 0 "0" (core func (;1;)))
  (core instance (;1;)
    (export "[task-cancel]" (func 0))
    (export "[task-return]foo" (func 1))
  )
  (alias core export 0 "1" (core func (;2;)))
  (core instance (;2;)
    (export "[task-return]foo" (func 2))
  )
  (core func (;3;) (canon context.get i32 1))
  (core func (;4;) (canon context.set i32 1))
  (core func (;5;) (canon thread.index))
  (alias core export 0 "2" (core func (;6;)))
  (core func (;7;) (canon thread.switch-to))
  (core func (;8;) (canon thread.suspend))
  (core func (;9;) (canon thread.resume-later))
  (core func (;10;) (canon thread.yield-to))
  (core instance (;3;)
    (export "[context-get-1]" (func 3))
    (export "[context-set-1]" (func 4))
    (export "[thread-index]" (func 5))
    (export "[thread-new-indirect-v0]" (func 6))
    (export "[thread-switch-to]" (func 7))
    (export "[thread-suspend]" (func 8))
    (export "[thread-resume-later]" (func 9))
    (export "[thread-yield-to]" (func 10))
  )
  (core instance (;4;) (instantiate 0
      (with "[export]$root" (instance 1))
      (with "[export]foo:foo/bar" (instance 2))
      (with "$root" (instance 3))
    )
  )
  (alias core export 4 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias core export 4 "cabi_realloc" (core func (;11;)))
  (core func (;12;) (canon task.return (result string) (memory 0) string-encoding=utf8))
  (core func (;13;) (canon task.return (result string) (memory 0) string-encoding=utf8))
  (core type (;0;) (func (param i32)))
  (alias core export 4 "__indirect_function_table" (core table (;1;)))
  (core func (;14;) (canon thread.new_indirect 0 (table 1)))
  (core instance (;5;)
    (export "$imports" (table 0))
    (export "0" (func 12))
    (export "1" (func 13))
    (export "2" (func 14))
  )
  (core instance (;6;) (instantiate 2
      (with "" (instance 5))
    )
  )
  (type (;0;) (func (param "s" string) (result string)))
  (alias core export 4 "[async-lift-stackful]foo" (core func (;15;)))
  (func (;0;) (type 0) (canon lift (core func 15) (memory 0) (realloc 11) string-encoding=utf8 async))
  (export (;1;) "foo" (func 0))
  (type (;1;) (func (param "s" string) (result string)))
  (alias core export 4 "[async-lift-stackful]foo:foo/bar#foo" (core func (;16;)))
  (func (;2;) (type 1) (canon lift (core func 16) (memory 0) (realloc 11) string-encoding=utf8 async))
  (component (;0;)
    (type (;0;) (func (param "s" string) (result string)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (param "s" string) (result string)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance (;0;) (instantiate 0
      (with "import-func-foo" (func 2))
    )
  )
  (export (;1;) "foo:foo/bar" (instance 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
