(component
  (core module (;0;)
    (type $thread-start-func-ty (;0;) (func (param i32)))
    (type (;1;) (func))
    (type (;2;) (func (param i32 i32)))
    (type (;3;) (func (result i32)))
    (type (;4;) (func (param i32 i32) (result i32)))
    (type (;5;) (func (param i32) (result i32)))
    (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
    (import "$root" "[backpressure-set]" (func (;0;) (type $thread-start-func-ty)))
    (import "[export]$root" "[task-cancel]" (func (;1;) (type 1)))
    (import "[export]$root" "[task-return]foo" (func (;2;) (type 2)))
    (import "[export]foo:foo/bar" "[task-return]foo" (func (;3;) (type 2)))
    (import "$root" "[waitable-set-new]" (func (;4;) (type 3)))
    (import "$root" "[waitable-set-wait]" (func (;5;) (type 4)))
    (import "$root" "[waitable-set-poll]" (func (;6;) (type 4)))
    (import "$root" "[waitable-set-drop]" (func (;7;) (type $thread-start-func-ty)))
    (import "$root" "[waitable-join]" (func (;8;) (type 2)))
    (import "$root" "[thread-yield]" (func (;9;) (type 3)))
    (import "$root" "[subtask-drop]" (func (;10;) (type $thread-start-func-ty)))
    (import "$root" "[subtask-cancel]" (func (;11;) (type 5)))
    (import "$root" "[error-context-new-utf8]" (func (;12;) (type 4)))
    (import "$root" "[error-context-new-utf16]" (func (;13;) (type 4)))
    (import "$root" "[error-context-new-latin1+utf16]" (func (;14;) (type 4)))
    (import "$root" "[error-context-debug-message-utf8]" (func (;15;) (type 2)))
    (import "$root" "[error-context-debug-message-utf16]" (func (;16;) (type 2)))
    (import "$root" "[error-context-debug-message-latin1+utf16]" (func (;17;) (type 2)))
    (import "$root" "[error-context-drop]" (func (;18;) (type $thread-start-func-ty)))
    (import "$root" "[context-get-0]" (func (;19;) (type 3)))
    (import "$root" "[context-set-0]" (func (;20;) (type $thread-start-func-ty)))
    (import "$root" "[context-get-1]" (func (;21;) (type 3)))
    (import "$root" "[context-set-1]" (func (;22;) (type $thread-start-func-ty)))
    (import "$root" "[thread-index]" (func (;23;) (type 3)))
    (import "$root" "[thread-new-indirect-v0]" (func (;24;) (type 4)))
    (import "$root" "[thread-switch-to]" (func (;25;) (type 5)))
    (import "$root" "[thread-suspend]" (func (;26;) (type 3)))
    (import "$root" "[thread-resume-later]" (func (;27;) (type $thread-start-func-ty)))
    (import "$root" "[thread-yield-to]" (func (;28;) (type 5)))
    (table (;0;) 1 1 funcref)
    (memory (;0;) 1)
    (export "thread_main" (func 29))
    (export "[async-lift-stackful]foo" (func 30))
    (export "[async-lift-stackful]foo:foo/bar#foo" (func 31))
    (export "memory" (memory 0))
    (export "__indirect_function_table" (table 0))
    (export "cabi_realloc" (func 32))
    (elem (;0;) (i32.const 0) func 0)
    (func (;29;) (type $thread-start-func-ty) (param i32)
      unreachable
    )
    (func (;30;) (type 2) (param i32 i32)
      unreachable
    )
    (func (;31;) (type 2) (param i32 i32)
      unreachable
    )
    (func (;32;) (type 6) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func (param i32 i32)))
    (table (;0;) 11 11 funcref)
    (export "0" (func $waitable-set.wait))
    (export "1" (func $waitable-set.poll))
    (export "2" (func $error-new))
    (export "3" (func $"#func3 error-new"))
    (export "4" (func $"#func4 error-new"))
    (export "5" (func $error-debug-message))
    (export "6" (func $"#func6 error-debug-message"))
    (export "7" (func $"#func7 error-debug-message"))
    (export "8" (func $thread.new_indirect))
    (export "9" (func $task-return-foo))
    (export "10" (func $"#func10 task-return-foo"))
    (export "$imports" (table 0))
    (func $waitable-set.wait (;0;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (func $waitable-set.poll (;1;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 1
      call_indirect (type 0)
    )
    (func $error-new (;2;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 2
      call_indirect (type 0)
    )
    (func $"#func3 error-new" (@name "error-new") (;3;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 3
      call_indirect (type 0)
    )
    (func $"#func4 error-new" (@name "error-new") (;4;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 4
      call_indirect (type 0)
    )
    (func $error-debug-message (;5;) (type 1) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 5
      call_indirect (type 1)
    )
    (func $"#func6 error-debug-message" (@name "error-debug-message") (;6;) (type 1) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 6
      call_indirect (type 1)
    )
    (func $"#func7 error-debug-message" (@name "error-debug-message") (;7;) (type 1) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 7
      call_indirect (type 1)
    )
    (func $thread.new_indirect (;8;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 8
      call_indirect (type 0)
    )
    (func $task-return-foo (;9;) (type 2) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 9
      call_indirect (type 2)
    )
    (func $"#func10 task-return-foo" (@name "task-return-foo") (;10;) (type 2) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 10
      call_indirect (type 2)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func (param i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "2" (func (;2;) (type 0)))
    (import "" "3" (func (;3;) (type 0)))
    (import "" "4" (func (;4;) (type 0)))
    (import "" "5" (func (;5;) (type 1)))
    (import "" "6" (func (;6;) (type 1)))
    (import "" "7" (func (;7;) (type 1)))
    (import "" "8" (func (;8;) (type 0)))
    (import "" "9" (func (;9;) (type 2)))
    (import "" "10" (func (;10;) (type 2)))
    (import "" "$imports" (table (;0;) 11 11 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2 3 4 5 6 7 8 9 10)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 1))
  (core func (;0;) (canon backpressure.set))
  (core func (;1;) (canon waitable-set.new))
  (alias core export 0 "0" (core func (;2;)))
  (alias core export 0 "1" (core func (;3;)))
  (core func (;4;) (canon waitable-set.drop))
  (core func (;5;) (canon waitable.join))
  (core func (;6;) (canon thread.yield))
  (core func (;7;) (canon subtask.drop))
  (core func (;8;) (canon subtask.cancel))
  (alias core export 0 "2" (core func (;9;)))
  (alias core export 0 "3" (core func (;10;)))
  (alias core export 0 "4" (core func (;11;)))
  (alias core export 0 "5" (core func (;12;)))
  (alias core export 0 "6" (core func (;13;)))
  (alias core export 0 "7" (core func (;14;)))
  (core func (;15;) (canon error-context.drop))
  (core func (;16;) (canon context.get i32 0))
  (core func (;17;) (canon context.set i32 0))
  (core func (;18;) (canon context.get i32 1))
  (core func (;19;) (canon context.set i32 1))
  (core func (;20;) (canon thread.index))
  (alias core export 0 "8" (core func (;21;)))
  (core func (;22;) (canon thread.switch-to))
  (core func (;23;) (canon thread.suspend))
  (core func (;24;) (canon thread.resume-later))
  (core func (;25;) (canon thread.yield-to))
  (core instance (;1;)
    (export "[backpressure-set]" (func 0))
    (export "[waitable-set-new]" (func 1))
    (export "[waitable-set-wait]" (func 2))
    (export "[waitable-set-poll]" (func 3))
    (export "[waitable-set-drop]" (func 4))
    (export "[waitable-join]" (func 5))
    (export "[thread-yield]" (func 6))
    (export "[subtask-drop]" (func 7))
    (export "[subtask-cancel]" (func 8))
    (export "[error-context-new-utf8]" (func 9))
    (export "[error-context-new-utf16]" (func 10))
    (export "[error-context-new-latin1+utf16]" (func 11))
    (export "[error-context-debug-message-utf8]" (func 12))
    (export "[error-context-debug-message-utf16]" (func 13))
    (export "[error-context-debug-message-latin1+utf16]" (func 14))
    (export "[error-context-drop]" (func 15))
    (export "[context-get-0]" (func 16))
    (export "[context-set-0]" (func 17))
    (export "[context-get-1]" (func 18))
    (export "[context-set-1]" (func 19))
    (export "[thread-index]" (func 20))
    (export "[thread-new-indirect-v0]" (func 21))
    (export "[thread-switch-to]" (func 22))
    (export "[thread-suspend]" (func 23))
    (export "[thread-resume-later]" (func 24))
    (export "[thread-yield-to]" (func 25))
  )
  (core func (;26;) (canon task.cancel))
  (alias core export 0 "9" (core func (;27;)))
  (core instance (;2;)
    (export "[task-cancel]" (func 26))
    (export "[task-return]foo" (func 27))
  )
  (alias core export 0 "10" (core func (;28;)))
  (core instance (;3;)
    (export "[task-return]foo" (func 28))
  )
  (core instance (;4;) (instantiate 0
      (with "$root" (instance 1))
      (with "[export]$root" (instance 2))
      (with "[export]foo:foo/bar" (instance 3))
    )
  )
  (alias core export 4 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (core func (;29;) (canon waitable-set.wait (memory 0)))
  (core func (;30;) (canon waitable-set.poll (memory 0)))
  (core func (;31;) (canon error-context.new (memory 0) string-encoding=utf8))
  (core func (;32;) (canon error-context.new (memory 0) string-encoding=utf16))
  (core func (;33;) (canon error-context.new (memory 0) string-encoding=latin1+utf16))
  (alias core export 4 "cabi_realloc" (core func (;34;)))
  (core func (;35;) (canon error-context.debug-message (memory 0) (realloc 34) string-encoding=utf8))
  (core func (;36;) (canon error-context.debug-message (memory 0) (realloc 34) string-encoding=utf16))
  (core func (;37;) (canon error-context.debug-message (memory 0) (realloc 34) string-encoding=latin1+utf16))
  (core type (;0;) (func (param i32)))
  (alias core export 4 "__indirect_function_table" (core table (;1;)))
  (core func (;38;) (canon thread.new_indirect 0 (table 1)))
  (core func (;39;) (canon task.return (result string) (memory 0) string-encoding=utf8))
  (core func (;40;) (canon task.return (result string) (memory 0) string-encoding=utf8))
  (core instance (;5;)
    (export "$imports" (table 0))
    (export "0" (func 29))
    (export "1" (func 30))
    (export "2" (func 31))
    (export "3" (func 32))
    (export "4" (func 33))
    (export "5" (func 35))
    (export "6" (func 36))
    (export "7" (func 37))
    (export "8" (func 38))
    (export "9" (func 39))
    (export "10" (func 40))
  )
  (core instance (;6;) (instantiate 2
      (with "" (instance 5))
    )
  )
  (type (;0;) (func (param "s" string) (result string)))
  (alias core export 4 "[async-lift-stackful]foo" (core func (;41;)))
  (func (;0;) (type 0) (canon lift (core func 41) (memory 0) (realloc 34) string-encoding=utf8 async))
  (export (;1;) "foo" (func 0))
  (type (;1;) (func (param "s" string) (result string)))
  (alias core export 4 "[async-lift-stackful]foo:foo/bar#foo" (core func (;42;)))
  (func (;2;) (type 1) (canon lift (core func 42) (memory 0) (realloc 34) string-encoding=utf8 async))
  (component (;0;)
    (type (;0;) (func (param "s" string) (result string)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (param "s" string) (result string)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance (;0;) (instantiate 0
      (with "import-func-foo" (func 2))
    )
  )
  (export (;1;) "foo:foo/bar" (instance 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
