// RUN: component embed % --dummy-names legacy --async-callback | \
//        component new | \
//        validate -f cm-async

package a:b;

world c {
  export i: interface {
    flags name { a, b, c }
    f: func(p: future<name>);
  }
}
