// RUN: component embed % --dummy-names legacy --async-callback | \
//        component new | \
//        validate -f cm-async

package a:b;

world c {
  import i: interface {
    resource r {
      f: func(s: stream<r>);
    }
  }
}
