// RUN: component embed % --dummy-names legacy --async-callback | \
//        component new | \
//        validate -f cm-async,cm-error-context

package a:b;

world c {
  export name: interface {
    resource n {
      constructor();
    }
  }
}

