// RUN: component embed % --dummy-names legacy --async-callback | \
//        component new | \
//        validate -f component-model-async

package a:b;

world c {
  export name: interface {
    resource n {
      constructor();
    }
  }
}

