// RUN[legacy]: component embed -t --dummy-names legacy % | strip -t
// RUN[standard32]: component embed -t --dummy-names standard32 % | strip -t

package a:b;

interface x {
  y: func() -> string;
}

world w {
  import x;
  export x;
}
