// FAIL: component embed --dummy --world into % | component embed --world %from % | component wit

package a:b;

interface i1 {
  type t = u32;
}
interface i2 {
  use i1.{t};
}

world into {
  export x: interface {
    use i2.{t};
  }
}

// `into` has a transitive dep on importing i2 and must then import i1. Means
// we can't import `i1` when merging this in.
world %from {
  export i1;
}
