// RUN: component embed --world foo --dummy % | component wit --importize

package importize:importize;

interface t {
    resource r;
}
interface bar {
    use t.{r};
    record foo {
      x: string
    }
    importize: func(name: r);
}

interface qux {
   use bar.{foo};
   blah: func(boo: foo);
}

interface something-else-dep {
    type t = u32;
} 

world foo {
    export qux;
    export foo: func();
    type s = u32;
    export bar: func() -> s;
    export something: interface {
        foo: func();
    }
    export something-else: interface {
        use something-else-dep.{t};
        bar: func() -> t;
    }
}