// RUN[new-import-new-dep]: component wit % --merge-world-imports-based-on-semver new-dep
// RUN[reorder-new-dep]: component wit % --merge-world-imports-based-on-semver reorder-dep

package foo:bar;

world new-dep {
  import a:b/foo@0.1.0;
  import a:b/foo@0.1.1;
}

world reorder-dep {
  import a:b/add-dep-on-prev-foo@0.1.0;
  import a:b/foo@0.1.0;
  import a:b/add-dep-on-prev-foo@0.1.1;
}

package a:b@0.1.0 {
  interface foo {
    type t = u32;
  }

  interface add-dep-on-prev-foo {}
}

package a:b@0.1.1 {
  interface foo {
    use bar.{t};
  }

  interface bar {
    type t = u32;
  }

  interface add-dep-on-prev-foo {
    use a:b/foo@0.1.0.{t};
  }
}
