// RUN[new-import-new-dep]: component embed --dummy --world new-dep-a % | \
//                          component embed         --world new-dep-b % | \
//                          component wit
//
// RUN[reorder-new-dep]: component embed --dummy --world reorder-dep-a % | \
//                       component embed         --world reorder-dep-b % | \
//                       component wit

package foo:bar;

world new-dep-a {
  import a:b/foo@0.1.0;
}

world new-dep-b {
  import a:b/foo@0.1.1;
}

world reorder-dep-a {
  import a:b/add-dep-on-prev-foo@0.1.0;
  import a:b/foo@0.1.0;
}

world reorder-dep-b {
  import a:b/add-dep-on-prev-foo@0.1.1;
}

package a:b@0.1.0 {
  interface foo {
    type t = u32;
  }

  interface add-dep-on-prev-foo {}
}

package a:b@0.1.1 {
  interface foo {
    use bar.{t};
  }

  interface bar {
    type t = u32;
  }

  interface add-dep-on-prev-foo {
    use a:b/foo@0.1.0.{t};
  }
}
