// RUN: component wit % --merge-world-imports-based-on-semver a

package foo:bar;

world a {
  import a:b/foo@0.1.1;
  export a:b/bar@0.1.0;
}

package a:b@0.1.0 {
  interface foo {
    type t = u32;
  }

  interface bar {
    use foo.{t};
  }
}

package a:b@0.1.1 {
  interface foo {
    type t = u32;
  }
}
