// RUN: component embed --dummy --world=bar:bar/my-world % | component wit

package foo:root;
package foo:foo {
  interface my-interface {
    foo: func();
  }

  world my-world {
    import my-interface;
  }
}

package bar:bar {
  interface my-interface {
    foo: func();
  }

  world my-world {
    import my-interface;
  }
}
