// RUN: component embed --dummy --world w1 % | \
//      component embed         --world w2 % | \
//      component embed         --world w3 % | \
//      component embed         --world w4 % | \
//      component wit

package a:b;

world w1 {}
world w2 {
  import a: interface {}
}
world w3 {
  export a: interface {}
}
world w4 {
  import b: interface {}
  export b: interface {}
}
