// RUN: component semver-check % --prev a:b/prev --new a:b/next

package a:b {
  world prev {}

  interface next-interface {

  }

  world next {
    import a: func();
    import b: interface {}
    import next-interface;
  }
}

package c:d {
  world old {}

  world new {
    import a: func();
  }
}
