// FAIL: component semver-check % --prev a:b/worldly@0.2.0 --new a:b/worldly@0.2.1

package foo:root;
package a:b@0.2.0 {
  world worldly {
    import a: func();
    import b: interface {}
  }
}

package a:b@0.2.1 {
  world worldly {
  }
}
