// RUN: component wit % --out-dir %tmpdir | component wit %tmpdir

package foo:root;
package a:b@0.2.0 {
  interface foo {}
}

package a:b {
  interface foo {}
}

package a:c {
  world a {
    import a:b/foo@0.2.0;
    import a:b/foo;
  }
}