// RUN[parse]: component wit % -t | validate -f cm-fixed-length-lists
// RUN[abi]: component embed --dummy % | component new | validate -f cm-fixed-length-lists

package a:b;

world lists {
  type t = list<t2, 16>;
  type t2 = list<t3, 16>;
  type t3 = list<t4, 16>;
  type t4 = list<t5, 16>;
  type t5 = list<t6, 16>;
  type t6 = list<t7, 16>;
  type t7 = list<t8, 16>;
  type t8 = list<u8, 16>;

  import x: func(t: t);
}

