// RUN: wit-dylib --validate % | strip -t
// RUN[task-context]: wit-dylib --validate % --stack-pointer task-context | strip -t

package the:test;

world adapter {
  import x: func();
  export y: func();
}
