// RUN: component embed --dummy --world into % | component embed --world %from % | component wit

package a:b;

world into {
}

interface b {
  type t = u32;
}

world %from {
  import a: interface {}
  import b;
  use b.{t};
  import c: func() -> t;
}
