// RUN: component embed --dummy --world foo % | component embed --world foo % | component wit

// This test embeds this world twice and then ensures that merging the two
// worlds together works (it's the same definition anyway).

package a:b;

interface x {
  type t = u32;
}

world foo {
  import x;
  export x;

  use x.{t};

  import a: func() -> t;

  export x: interface {}
  export y: func();
}
