// RUN: component embed --dummy --world a % | \
//      component embed         --world b % | \
//      component wit


package a:b;

world a {
  resource a;
}

world b {
  resource a {
    constructor();
  }
}
