// RUN: component embed --dummy --world into % | component embed --world %from % | component wit

package a:b;

interface b {
  type t = u32;
}

world into {
  import a: interface {}
  import b;
  import c: func();
  use b.{t};
}

world %from {
  import a: interface {}
  import b;
  import c: func();
  use b.{t};
}
