// FAIL: component embed --dummy --world into % | component embed --world %from % | component wit

package a:b;

interface i1 {
  type t = u32;
}
interface i2 {
  use i1.{t};
}

world into {
  export i2;
}

// This world cannot be merged into `into` because it would change the meaning
// of `into`. Previously in `into` i2's export of `i2` would refer to the
// implicit import of `i1`, but here the export of `i2` refers to the export of
// `i1`.
world %from {
  export i1;
  export i2;
}

