(component
  (type (;0;) (list u8))
  (type (;1;) (record (field "a1" u32) (field "a2" u64) (field "a3" s32) (field "a4" s64) (field "b" string) (field "c" 0)))
  (type (;2;) (record (field "x" string) (field "y" 1) (field "c1" u32) (field "c2" u64) (field "c3" s32) (field "c4" s64)))
  (type (;3;) (variant (case "a") (case "b" u32) (case "c" string)))
  (type (;4;) (list 3))
  (type (;5;) (variant (case "a" string) (case "b") (case "c" u32) (case "d" 4)))
  (type (;6;) (tuple string u8 s8 u16 s16 u32 s32 u64 s64 float32 float64 char))
  (type (;7;) (list 6))
  (type (;8;) (func (param "x" 0)))
  (type (;9;) (list u16))
  (type (;10;) (func (param "x" 9)))
  (type (;11;) (list u32))
  (type (;12;) (func (param "x" 11)))
  (type (;13;) (list u64))
  (type (;14;) (func (param "x" 13)))
  (type (;15;) (list s8))
  (type (;16;) (func (param "x" 15)))
  (type (;17;) (list s16))
  (type (;18;) (func (param "x" 17)))
  (type (;19;) (list s32))
  (type (;20;) (func (param "x" 19)))
  (type (;21;) (list s64))
  (type (;22;) (func (param "x" 21)))
  (type (;23;) (list float32))
  (type (;24;) (func (param "x" 23)))
  (type (;25;) (list float64))
  (type (;26;) (func (param "x" 25)))
  (type (;27;) (func (result 0)))
  (type (;28;) (func (result 9)))
  (type (;29;) (func (result 11)))
  (type (;30;) (func (result 13)))
  (type (;31;) (func (result 15)))
  (type (;32;) (func (result 17)))
  (type (;33;) (func (result 19)))
  (type (;34;) (func (result 21)))
  (type (;35;) (func (result 23)))
  (type (;36;) (func (result 25)))
  (type (;37;) (tuple u8 s8))
  (type (;38;) (list 37))
  (type (;39;) (tuple s64 u32))
  (type (;40;) (list 39))
  (type (;41;) (func (param "x" 38) (result 40)))
  (type (;42;) (list string))
  (type (;43;) (func (param "a" 42)))
  (type (;44;) (func (result 42)))
  (type (;45;) (tuple u8 string))
  (type (;46;) (list 45))
  (type (;47;) (tuple string u8))
  (type (;48;) (list 47))
  (type (;49;) (func (param "x" 46) (result 48)))
  (type (;50;) (func (param "x" 42) (result 42)))
  (type (;51;) (list 2))
  (type (;52;) (list 1))
  (type (;53;) (func (param "x" 51) (result 52)))
  (type (;54;) (list 5))
  (type (;55;) (func (param "x" 54) (result 4)))
  (type (;56;) (func (param "a" 7) (result 7)))
  (type (;57;)
    (instance
      (alias outer 1 1 (type (;0;)))
      (export "other-record" (type (eq 0)))
      (alias outer 1 2 (type (;1;)))
      (export "some-record" (type (eq 1)))
      (alias outer 1 3 (type (;2;)))
      (export "other-variant" (type (eq 2)))
      (alias outer 1 5 (type (;3;)))
      (export "some-variant" (type (eq 3)))
      (alias outer 1 7 (type (;4;)))
      (export "load-store-all-sizes" (type (eq 4)))
      (alias outer 1 8 (type (;5;)))
      (export "list-u8-param" (func (type 5)))
      (alias outer 1 10 (type (;6;)))
      (export "list-u16-param" (func (type 6)))
      (alias outer 1 12 (type (;7;)))
      (export "list-u32-param" (func (type 7)))
      (alias outer 1 14 (type (;8;)))
      (export "list-u64-param" (func (type 8)))
      (alias outer 1 16 (type (;9;)))
      (export "list-s8-param" (func (type 9)))
      (alias outer 1 18 (type (;10;)))
      (export "list-s16-param" (func (type 10)))
      (alias outer 1 20 (type (;11;)))
      (export "list-s32-param" (func (type 11)))
      (alias outer 1 22 (type (;12;)))
      (export "list-s64-param" (func (type 12)))
      (alias outer 1 24 (type (;13;)))
      (export "list-float32-param" (func (type 13)))
      (alias outer 1 26 (type (;14;)))
      (export "list-float64-param" (func (type 14)))
      (alias outer 1 27 (type (;15;)))
      (export "list-u8-ret" (func (type 15)))
      (alias outer 1 28 (type (;16;)))
      (export "list-u16-ret" (func (type 16)))
      (alias outer 1 29 (type (;17;)))
      (export "list-u32-ret" (func (type 17)))
      (alias outer 1 30 (type (;18;)))
      (export "list-u64-ret" (func (type 18)))
      (alias outer 1 31 (type (;19;)))
      (export "list-s8-ret" (func (type 19)))
      (alias outer 1 32 (type (;20;)))
      (export "list-s16-ret" (func (type 20)))
      (alias outer 1 33 (type (;21;)))
      (export "list-s32-ret" (func (type 21)))
      (alias outer 1 34 (type (;22;)))
      (export "list-s64-ret" (func (type 22)))
      (alias outer 1 35 (type (;23;)))
      (export "list-float32-ret" (func (type 23)))
      (alias outer 1 36 (type (;24;)))
      (export "list-float64-ret" (func (type 24)))
      (alias outer 1 41 (type (;25;)))
      (export "tuple-list" (func (type 25)))
      (alias outer 1 43 (type (;26;)))
      (export "string-list-arg" (func (type 26)))
      (alias outer 1 44 (type (;27;)))
      (export "string-list-ret" (func (type 27)))
      (alias outer 1 49 (type (;28;)))
      (export "tuple-string-list" (func (type 28)))
      (alias outer 1 50 (type (;29;)))
      (export "string-list" (func (type 29)))
      (alias outer 1 53 (type (;30;)))
      (export "record-list" (func (type 30)))
      (alias outer 1 55 (type (;31;)))
      (export "variant-list" (func (type 31)))
      (alias outer 1 56 (type (;32;)))
      (export "load-store-everything" (func (type 32)))
    )
  )
  (import "lists" (instance (;0;) (type 57)))
)