version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "alexcrichton"

  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "alexcrichton"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-minor"]
