(component
  (type $ty-foo (;0;)
    (instance
      (type (;0;) (func))
      (export (;0;) "x" (func (type 0)))
    )
  )
  (import "foo" (implements "a:b/c@0.1") (versionsuffix ".1") (instance $foo (;0;) (type $ty-foo)))
  (core module $main (;0;)
    (type (;0;) (func))
    (import "foo" "x" (func (;0;) (type 0)))
    (export "bar#x" (func 1))
    (func (;1;) (type 0)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (alias export $foo "x" (func $x (;0;)))
  (core func $x (;0;) (canon lower (func $x)))
  (core instance $foo (;0;)
    (export "x" (func $x))
  )
  (core instance $main (;1;) (instantiate $main
      (with "foo" (instance $foo))
    )
  )
  (type (;1;) (func))
  (alias core export $main "bar#x" (core func $bar#x (;1;)))
  (func $"#func1 x" (@name "x") (;1;) (type 1) (canon lift (core func $bar#x)))
  (component $bar-shim-component (;0;)
    (type (;0;) (func))
    (import "import-func-x" (func (;0;) (type 0)))
    (type (;1;) (func))
    (export (;1;) "x" (func 0) (func (type 1)))
  )
  (instance $bar-shim-instance (;1;) (instantiate $bar-shim-component
      (with "import-func-x" (func $"#func1 x"))
    )
  )
  (export $bar (;2;) "bar" (implements "a:b/c@0.1") (versionsuffix ".1") (instance $bar-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
