(component
  (core module $main (;0;)
    (type (;0;) (func))
    (import "old" "thunk" (func (;0;) (type 0)))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component:adapter:old (;1;)
    (type (;0;) (func))
    (export "thunk" (func 0))
    (func (;0;) (type 0))
  )
  (core module $wit-component-shim-module (;2;)
    (type (;0;) (func))
    (table (;0;) 1 1 funcref)
    (export "0" (func $adapt-old-thunk))
    (export "$imports" (table 0))
    (func $adapt-old-thunk (;0;) (type 0)
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias core export $wit-component-shim-instance "0" (core func $adapt-old-thunk (;0;)))
  (core instance $old (;1;)
    (export "thunk" (func $adapt-old-thunk))
  )
  (core instance $main (;2;) (instantiate $main
      (with "old" (instance $old))
    )
  )
  (core instance $"#core-instance3 old" (@name "old") (;3;) (instantiate $wit-component:adapter:old))
  (core module $wit-component-fixup (;3;)
    (type (;0;) (func))
    (import "actual" "0" (func (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (alias core export $"#core-instance3 old" "thunk" (core func $thunk (;1;)))
  (core instance $actual (;4;)
    (export "0" (func $thunk))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "shim" (instance $wit-component-shim-instance))
      (with "actual" (instance $actual))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
