(component
  (type (;0;)
    (instance
      (export (;0;) "fields" (type (sub resource)))
      (export (;1;) "trailers" (type (eq 0)))
    )
  )
  (import "a:b/types" (instance (;0;) (type 0)))
  (core module (;0;)
    (type (;0;) (func (param i32) (result i32)))
    (type (;1;) (func (param i32)))
    (import "a:b/types" "[future-cancel-read-0][static]request.new" (func (;0;) (type 0)))
    (import "a:b/types" "[resource-drop]fields" (func (;1;) (type 1)))
    (memory (;0;) 17)
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (alias export 0 "trailers" (type (;1;)))
  (type (;2;) (own 1))
  (type (;3;) (future 2))
  (core func (;0;) (canon future.cancel-read 3))
  (alias export 0 "fields" (type (;4;)))
  (core func (;1;) (canon resource.drop 4))
  (core instance (;0;)
    (export "[future-cancel-read-0][static]request.new" (func 0))
    (export "[resource-drop]fields" (func 1))
  )
  (core instance (;1;) (instantiate 0
      (with "a:b/types" (instance 0))
    )
  )
  (alias core export 1 "memory" (core memory (;0;)))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
