(component
  (type (;0;)
    (instance
      (type (;0;) u8)
      (export "foo" (type (eq 0)))
      (type (;1;) (record (field "x" 0)))
      (export "bar" (type (eq 2)))
      (type (;2;) (func (param "b" 2)))
      (export "a" (func (type 4)))
    )
  )
  (import "foo" (instance (;0;) (type 0)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (import "foo" "a" (func (;0;) (type 0)))
    (func (;1;) (type 1) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;2;) (type 0) (param i32)
      unreachable
    )
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 1))
    (export "a" (func 2))
  )
  (alias export 0 "a" (func (;0;)))
  (core func (;0;) (canon lower (func 0)))
  (core instance (;0;)
    (export "a" (func 0))
  )
  (core instance (;1;) (instantiate 0
      (with "foo" (instance 0))
    )
  )
  (alias core export 1 "memory" (core memory (;0;)))
  (alias core export 1 "cabi_realloc" (core func (;1;)))
  (alias core export 1 "a" (core func (;2;)))
  (type (;1;) u8)
  (type (;2;) (record (field "x" 1)))
  (type (;3;) (func (param "b" 2)))
  (func (;1;) (type 3) (canon lift (core func 2)))
  (export (;2;) "a" (func 1))
  (export (;4;) "foo" (type 1))
  (export (;5;) "bar" (type 2))
)