(component
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func (param i32) (result i32)))
    (type (;3;) (func))
    (type (;4;) (func (param i32 i32) (result i32)))
    (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
    (import "$root" "[task-backpressure]" (func (;0;) (type 0)))
    (import "[export]$root" "[task-return]foo" (func (;1;) (type 1)))
    (import "[export]foo:foo/bar" "[task-return]foo" (func (;2;) (type 1)))
    (import "$root" "[task-wait]" (func (;3;) (type 2)))
    (import "$root" "[task-poll]" (func (;4;) (type 2)))
    (import "$root" "[task-yield]" (func (;5;) (type 3)))
    (import "$root" "[subtask-drop]" (func (;6;) (type 0)))
    (import "$root" "[error-context-new;encoding=utf8]" (func (;7;) (type 4)))
    (import "$root" "[error-context-debug-message;encoding=utf8;realloc=cabi_realloc]" (func (;8;) (type 1)))
    (import "$root" "[error-context-drop]" (func (;9;) (type 0)))
    (memory (;0;) 1)
    (export "[async-stackful]foo" (func 10))
    (export "[async-stackful]foo:foo/bar#foo" (func 11))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 12))
    (func (;10;) (type 1) (param i32 i32)
      unreachable
    )
    (func (;11;) (type 1) (param i32 i32)
      unreachable
    )
    (func (;12;) (type 5) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32) (result i32)))
    (type (;1;) (func (param i32 i32) (result i32)))
    (type (;2;) (func (param i32 i32)))
    (table (;0;) 4 4 funcref)
    (export "0" (func $task-wait))
    (export "1" (func $task-poll))
    (export "2" (func $error-new))
    (export "3" (func $error-debug-message))
    (export "$imports" (table 0))
    (func $task-wait (;0;) (type 0) (param i32) (result i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (func $task-poll (;1;) (type 0) (param i32) (result i32)
      local.get 0
      i32.const 1
      call_indirect (type 0)
    )
    (func $error-new (;2;) (type 1) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 2
      call_indirect (type 1)
    )
    (func $error-debug-message (;3;) (type 2) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 3
      call_indirect (type 2)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32) (result i32)))
    (type (;1;) (func (param i32 i32) (result i32)))
    (type (;2;) (func (param i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "2" (func (;2;) (type 1)))
    (import "" "3" (func (;3;) (type 2)))
    (import "" "$imports" (table (;0;) 4 4 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2 3)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 1))
  (core func (;0;) (canon task.backpressure))
  (alias core export 0 "0" (core func (;1;)))
  (alias core export 0 "1" (core func (;2;)))
  (core func (;3;) (canon task.yield))
  (core func (;4;) (canon subtask.drop))
  (alias core export 0 "2" (core func (;5;)))
  (alias core export 0 "3" (core func (;6;)))
  (core func (;7;) (canon error-context.drop))
  (core instance (;1;)
    (export "[task-backpressure]" (func 0))
    (export "[task-wait]" (func 1))
    (export "[task-poll]" (func 2))
    (export "[task-yield]" (func 3))
    (export "[subtask-drop]" (func 4))
    (export "[error-context-new;encoding=utf8]" (func 5))
    (export "[error-context-debug-message;encoding=utf8;realloc=cabi_realloc]" (func 6))
    (export "[error-context-drop]" (func 7))
  )
  (core func (;8;) (canon task.return (result string)))
  (core instance (;2;)
    (export "[task-return]foo" (func 8))
  )
  (core func (;9;) (canon task.return (result string)))
  (core instance (;3;)
    (export "[task-return]foo" (func 9))
  )
  (core instance (;4;) (instantiate 0
      (with "$root" (instance 1))
      (with "[export]$root" (instance 2))
      (with "[export]foo:foo/bar" (instance 3))
    )
  )
  (alias core export 4 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (core func (;10;) (canon task.wait (memory 0)))
  (core func (;11;) (canon task.poll (memory 0)))
  (core func (;12;) (canon error-context.new (memory 0) string-encoding=utf8))
  (alias core export 4 "cabi_realloc" (core func (;13;)))
  (core func (;14;) (canon error-context.debug-message (memory 0) (realloc 13) string-encoding=utf8))
  (core instance (;5;)
    (export "$imports" (table 0))
    (export "0" (func 10))
    (export "1" (func 11))
    (export "2" (func 12))
    (export "3" (func 14))
  )
  (core instance (;6;) (instantiate 2
      (with "" (instance 5))
    )
  )
  (type (;0;) (func (param "s" string) (result string)))
  (alias core export 4 "[async-stackful]foo" (core func (;15;)))
  (func (;0;) (type 0) (canon lift (core func 15) (memory 0) (realloc 13) string-encoding=utf8 async))
  (export (;1;) "foo" (func 0))
  (type (;1;) (func (param "s" string) (result string)))
  (alias core export 4 "[async-stackful]foo:foo/bar#foo" (core func (;16;)))
  (func (;2;) (type 1) (canon lift (core func 16) (memory 0) (realloc 13) string-encoding=utf8 async))
  (component (;0;)
    (type (;0;) (func (param "s" string) (result string)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (param "s" string) (result string)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance (;0;) (instantiate 0
      (with "import-func-foo" (func 2))
    )
  )
  (export (;1;) "foo:foo/bar" (instance 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
