(module
  (import "$root" "[task-backpressure]" (func (param i32)))
  (import "$root" "[task-return]foo" (func (param i32 i32)))
  (import "[export]foo:foo/bar" "[task-return]foo" (func (param i32 i32)))  
  (import "$root" "[task-wait]" (func (param i32) (result i32)))
  (import "$root" "[task-poll]" (func (param i32) (result i32)))
  (import "$root" "[task-yield]" (func))
  (import "$root" "[subtask-drop]" (func (param i32)))
  (import "$root" "[error-context-new;encoding=utf8]" (func (param i32 i32) (result i32)))
  (import "$root" "[error-context-debug-message;encoding=utf8;realloc=cabi_realloc]" (func (param i32 i32)))
  (import "$root" "[error-context-drop]" (func (param i32)))
  (func (export "[async]foo") (param i32 i32) (result i32) unreachable)
  (func (export "[async]foo:foo/bar#foo") (param i32 i32) (result i32) unreachable)
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
)
