(component
  (core module $main (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi:cli/environment@0.2.0" "get-environment" (func $get-environment (;0;) (type 1)))
    (memory (;0;) 1)
    (export "cabi_realloc" (func $realloc))
    (export "memory" (memory 0))
    (start $start)
    (func $start (;1;) (type 0))
    (func $realloc (;2;) (type 2) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component:adapter:wasi:cli/environment@0.2.0 (;1;)
    (type (;0;) (func (param i32)))
    (export "get-environment" (func $get-environment))
    (func $get-environment (;0;) (type 0) (param i32)
      unreachable
    )
  )
  (core module $wit-component-shim-module (;2;)
    (type (;0;) (func (param i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func $adapt-wasi:cli/environment@0.2.0-get-environment))
    (export "$imports" (table 0))
    (func $adapt-wasi:cli/environment@0.2.0-get-environment (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias core export $wit-component-shim-instance "0" (core func $adapt-wasi:cli/environment@0.2.0-get-environment (;0;)))
  (core instance $wasi:cli/environment@0.2.0 (;1;)
    (export "get-environment" (func $adapt-wasi:cli/environment@0.2.0-get-environment))
  )
  (core instance $main (;2;) (instantiate $main
      (with "wasi:cli/environment@0.2.0" (instance $wasi:cli/environment@0.2.0))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core instance $"#core-instance3 wasi:cli/environment@0.2.0" (@name "wasi:cli/environment@0.2.0") (;3;) (instantiate $wit-component:adapter:wasi:cli/environment@0.2.0))
  (core module $wit-component-fixup (;3;)
    (type (;0;) (func (param i32)))
    (import "actual" "0" (func $0 (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func $0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (alias core export $"#core-instance3 wasi:cli/environment@0.2.0" "get-environment" (core func $get-environment (;1;)))
  (core instance $actual (;4;)
    (export "0" (func $get-environment))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "actual" (instance $actual))
      (with "shim" (instance $wit-component-shim-instance))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
