[package]
name = "test-programs"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
wit-dylib-ffi = { path = '../ffi' }
wit-bindgen = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true

[lib]
test = false
doctest = false
