(component
  (type (;0;)
    (instance
      (export (;0;) "a" (type (sub resource)))
    )
  )
  (import (interface "foo:bar/foo") (instance (;0;) (type 0)))
  (alias export 0 "a" (type (;1;)))
  (import "a" (type (;2;) (eq 1)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32) (result i32)))
    (import "foo:bar/foo" "[resource-drop-own]a" (func (;0;) (type 0)))
    (import "foo:bar/foo" "[resource-drop-borrow]a" (func (;1;) (type 0)))
    (import "[export]foo:bar/foo" "[resource-drop-own]a" (func (;2;) (type 0)))
    (import "[export]foo:bar/foo" "[resource-drop-borrow]a" (func (;3;) (type 0)))
    (import "[export]foo:bar/foo" "[resource-rep]a" (func (;4;) (type 1)))
    (import "[export]foo:bar/foo" "[resource-new]a" (func (;5;) (type 1)))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (alias export 0 "a" (type (;3;)))
  (type (;4;) (own 3))
  (core func (;0;) (canon resource.drop 4))
  (alias export 0 "a" (type (;5;)))
  (type (;6;) (borrow 5))
  (core func (;1;) (canon resource.drop 6))
  (core instance (;0;)
    (export "[resource-drop-own]a" (func 0))
    (export "[resource-drop-borrow]a" (func 1))
  )
  (type (;7;) (resource (rep i32)))
  (type (;8;) (own 7))
  (core func (;2;) (canon resource.drop 8))
  (type (;9;) (borrow 7))
  (core func (;3;) (canon resource.drop 9))
  (core func (;4;) (canon resource.rep 7))
  (core func (;5;) (canon resource.new 7))
  (core instance (;1;)
    (export "[resource-drop-own]a" (func 2))
    (export "[resource-drop-borrow]a" (func 3))
    (export "[resource-rep]a" (func 4))
    (export "[resource-new]a" (func 5))
  )
  (core instance (;2;) (instantiate 0
      (with "foo:bar/foo" (instance 0))
      (with "[export]foo:bar/foo" (instance 1))
    )
  )
  (component (;0;)
    (import "import-type-a" (type (;0;) (sub resource)))
    (export (;1;) "a" (type 0))
  )
  (instance (;1;) (instantiate 0
      (with "import-type-a" (type 7))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
  (export (;2;) (interface "foo:bar/foo") (instance 1))
)