interface different-name {
  record bar {
  }

}

interface other-name {
  use self.different-name.{bar}
  a: func() -> bar
}

default world component {
  import different-name: self.different-name
  import other-name: self.other-name
}
