(component
  (core module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (result i32)))
    (type (;2;) (func (param i32)))
    (type (;3;) (func (param i32 i32) (result i32)))
    (type (;4;) (func (param i32 i32 i32)))
    (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;6;) (func (param i32) (result i32)))
    (type (;7;) (func (param i32 i32)))
    (type (;8;) (func (param i32 i32 i32) (result i32)))
    (func $__wasm_call_ctors (;0;) (type 0))
    (func $wasi:cli-base/environment#get-environment (;1;) (type 1) (result i32)
      i32.const 0
    )
    (func $cabi_post_wasi:cli-base/environment#get-environment (;2;) (type 2) (param i32))
    (func $wasi:cli-base/environment#get-arguments (;3;) (type 1) (result i32)
      i32.const 0
    )
    (func $cabi_post_wasi:cli-base/environment#get-arguments (;4;) (type 2) (param i32))
    (func $cabi_realloc (;10;) (type 5) (param i32 i32 i32 i32) (result i32)
      i32.const 0
    )
    (table (;0;) 1 1 funcref)
    (memory (;0;) 17)
    (global $__stack_pointer (;0;) (mut i32) i32.const 1048576)
    (export "memory" (memory 0))
    (export "wasi:cli-base/environment#get-environment" (func $wasi:cli-base/environment#get-environment))
    (export "cabi_post_wasi:cli-base/environment#get-environment" (func $cabi_post_wasi:cli-base/environment#get-environment))
    (export "wasi:cli-base/environment#get-arguments" (func $wasi:cli-base/environment#get-arguments))
    (export "cabi_post_wasi:cli-base/environment#get-arguments" (func $cabi_post_wasi:cli-base/environment#get-arguments))
    (export "cabi_realloc" (func $cabi_realloc))
  )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (alias core export 0 "cabi_realloc" (core func (;0;)))
  (type (;0;) (tuple string string))
  (type (;1;) (list 0))
  (type (;2;) (func (result 1)))
  (alias core export 0 "wasi:cli-base/environment#get-environment" (core func (;1;)))
  (alias core export 0 "cabi_post_wasi:cli-base/environment#get-environment" (core func (;2;)))
  (func (;0;) (type 2) (canon lift (core func 1) (memory 0) string-encoding=utf8 (post-return 2)))
  (type (;3;) (list string))
  (type (;4;) (func (result 3)))
  (alias core export 0 "wasi:cli-base/environment#get-arguments" (core func (;3;)))
  (alias core export 0 "cabi_post_wasi:cli-base/environment#get-arguments" (core func (;4;)))
  (func (;1;) (type 4) (canon lift (core func 3) (memory 0) string-encoding=utf8 (post-return 4)))
  (component (;0;)
    (type (;0;) (tuple string string))
    (type (;1;) (list 0))
    (type (;2;) (func (result 1)))
    (import "import-func-get-environment" (func (;0;) (type 2)))
    (type (;3;) (list string))
    (type (;4;) (func (result 3)))
    (import "import-func-get-arguments" (func (;1;) (type 4)))
    (type (;5;) (tuple string string))
    (type (;6;) (list 5))
    (type (;7;) (func (result 6)))
    (export (;2;) "get-environment" (func 0) (func (type 7)))
    (type (;8;) (list string))
    (type (;9;) (func (result 8)))
    (export (;3;) "get-arguments" (func 1) (func (type 9)))
  )
  (instance (;0;) (instantiate 0
      (with "import-func-get-environment" (func 0))
      (with "import-func-get-arguments" (func 1))
    )
  )
  (export (;1;) (interface "wasi:cli-base/environment") (instance 0))
)
