(component
  (type (;0;)
    (instance
      (type (;0;) (tuple string string))
      (type (;1;) (list 0))
      (type (;2;) (func (result 1)))
      (export (;0;) "get-environment" (func (type 2)))
      (type (;3;) (list string))
      (type (;4;) (func (result 3)))
      (export (;1;) "get-arguments" (func (type 4)))
    )
  )
  (import (interface "wasi:cli-base/environment") (instance (;0;) (type 0)))
  (import "other1" (instance (;0;)))
  (import "other2" (instance (;0;)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (import "wasi:cli-base/environment" "get-environment" (func (;0;) (type 0)))
    (import "wasi:cli-base/environment" "get-arguments" (func (;1;) (type 0)))
    (func (;2;) (type 1) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 2))
    (@producers
      (processed-by "wit-component" "0.11.0")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32)))
    (func $indirect-wasi:cli-base/environment-get-environment (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (func $indirect-wasi:cli-base/environment-get-arguments (;1;) (type 0) (param i32)
      local.get 0
      i32.const 1
      call_indirect (type 0)
    )
    (table (;0;) 2 2 funcref)
    (export "0" (func $indirect-wasi:cli-base/environment-get-environment))
    (export "1" (func $indirect-wasi:cli-base/environment-get-arguments))
    (export "$imports" (table 0))
    (@producers
      (processed-by "wit-component" "0.11.0")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "$imports" (table (;0;) 2 2 funcref))
    (elem (;0;) (i32.const 0) func 0 1)
    (@producers
      (processed-by "wit-component" "0.11.0")
    )
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (alias core export 0 "1" (core func (;1;)))
  (core instance (;1;)
    (export "get-environment" (func 0))
    (export "get-arguments" (func 1))
  )
  (core instance (;2;) (instantiate 0
      (with "wasi:cli-base/environment" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 2 "cabi_realloc" (core func (;2;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "get-environment" (func (;0;)))
  (core func (;3;) (canon lower (func 0) (memory 0) (realloc 2) string-encoding=utf8))
  (alias export 0 "get-arguments" (func (;1;)))
  (core func (;4;) (canon lower (func 1) (memory 0) (realloc 2) string-encoding=utf8))
  (@producers
    (processed-by "wit-component" "0.11.0")
  )
  (core instance (;3;)
    (export "$imports" (table 0))
    (export "0" (func 3))
    (export "1" (func 4))
  )
  (core instance (;4;) (instantiate 2
      (with "" (instance 3))
    )
  )
)