(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "blob" (type (sub resource)))
          (type (;1;) (list u8))
          (type (;2;) (own 0))
          (type (;3;) (func (param "init" 1) (result 2)))
          (export (;0;) "[constructor]blob" (func (type 3)))
          (type (;4;) (borrow 0))
          (type (;5;) (func (param "self" 4) (param "bytes" 1)))
          (export (;1;) "[method]blob.write" (func (type 5)))
          (type (;6;) (func (param "self" 4) (result u64)))
          (export (;2;) "[method][get]blob.position" (func (type 6)))
          (type (;7;) (func (param "self" 4) (param "value" u64)))
          (export (;3;) "[method][set]blob.position" (func (type 7)))
          (type (;8;) (func (result u64)))
          (export (;4;) "[static][get]blob.max-size" (func (type 8)))
          (type (;9;) (result (error string)))
          (type (;10;) (func (param "value" u64) (result 9)))
          (export (;5;) "[static][set]blob.max-size" (func (type 10)))
          (type (;11;) (func (result string)))
          (export (;6;) "[static][get]blob.name" (func (type 11)))
          (export (;7;) "[get]prop" (func (type 8)))
          (type (;12;) (func (param "value" u64)))
          (export (;8;) "[set]prop" (func (type 12)))
          (export (;9;) "[get]read-only" (func (type 11)))
          (type (;13;) (func (result u32)))
          (export (;10;) "[get]fallible" (func (type 13)))
          (type (;14;) (func (param "value" u32) (result 9)))
          (export (;11;) "[set]fallible" (func (type 14)))
          (type (;15;) (func (result bool)))
          (export (;12;) "[get]reversed" (func (type 15)))
          (type (;16;) (func (param "value" bool)))
          (export (;13;) "[set]reversed" (func (type 16)))
        )
      )
      (export (;0;) "foo:accessors/accessors" (instance (type 0)))
    )
  )
  (export (;1;) "accessors" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (component
          (type (;0;) (func (result u64)))
          (import "[get]prop" (func (;0;) (type 0)))
          (type (;1;) (func (param "value" u64)))
          (import "[set]prop" (func (;1;) (type 1)))
          (export (;2;) "[get]other" (func (type 0)))
          (export (;3;) "[set]other" (func (type 1)))
          (type (;2;)
            (instance
              (export (;0;) "blob" (type (sub resource)))
              (type (;1;) (list u8))
              (type (;2;) (own 0))
              (type (;3;) (func (param "init" 1) (result 2)))
              (export (;0;) "[constructor]blob" (func (type 3)))
              (type (;4;) (borrow 0))
              (type (;5;) (func (param "self" 4) (param "bytes" 1)))
              (export (;1;) "[method]blob.write" (func (type 5)))
              (type (;6;) (func (param "self" 4) (result u64)))
              (export (;2;) "[method][get]blob.position" (func (type 6)))
              (type (;7;) (func (param "self" 4) (param "value" u64)))
              (export (;3;) "[method][set]blob.position" (func (type 7)))
              (type (;8;) (func (result u64)))
              (export (;4;) "[static][get]blob.max-size" (func (type 8)))
              (type (;9;) (result (error string)))
              (type (;10;) (func (param "value" u64) (result 9)))
              (export (;5;) "[static][set]blob.max-size" (func (type 10)))
              (type (;11;) (func (result string)))
              (export (;6;) "[static][get]blob.name" (func (type 11)))
              (export (;7;) "[get]prop" (func (type 8)))
              (type (;12;) (func (param "value" u64)))
              (export (;8;) "[set]prop" (func (type 12)))
              (export (;9;) "[get]read-only" (func (type 11)))
              (type (;13;) (func (result u32)))
              (export (;10;) "[get]fallible" (func (type 13)))
              (type (;14;) (func (param "value" u32) (result 9)))
              (export (;11;) "[set]fallible" (func (type 14)))
              (type (;15;) (func (result bool)))
              (export (;12;) "[get]reversed" (func (type 15)))
              (type (;16;) (func (param "value" bool)))
              (export (;13;) "[set]reversed" (func (type 16)))
            )
          )
          (export (;0;) "foo:accessors/accessors" (instance (type 2)))
        )
      )
      (export (;0;) "foo:accessors/accessors-world" (component (type 0)))
    )
  )
  (export (;3;) "accessors-world" (type 2))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
