(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (enum "a"))
          (export (;1;) "the-enum" (type (eq 0)))
        )
      )
      (export (;0;) (interface "foo:foo/shared-items") (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (enum "a"))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (import (interface "foo:foo/shared-items") (instance (;0;) (type 0)))
          (alias export 0 "the-enum" (type (;1;)))
          (type (;2;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (import "foo" (instance (;1;) (type 2)))
          (type (;3;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (import "bar" (instance (;2;) (type 3)))
        )
      )
      (export (;0;) (interface "foo:foo/w1") (component (type 1)))
      (type (;2;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (enum "a"))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (import (interface "foo:foo/shared-items") (instance (;0;) (type 0)))
          (alias export 0 "the-enum" (type (;1;)))
          (type (;2;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (import "foo" (instance (;1;) (type 2)))
          (type (;3;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (export (;2;) "bar" (instance (type 3)))
        )
      )
      (export (;1;) (interface "foo:foo/w2") (component (type 2)))
      (type (;3;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (enum "a"))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (import (interface "foo:foo/shared-items") (instance (;0;) (type 0)))
          (alias export 0 "the-enum" (type (;1;)))
          (type (;2;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "the-enum" (type (eq 0)))
            )
          )
          (export (;1;) "bar" (instance (type 2)))
        )
      )
      (export (;2;) (interface "foo:foo/w3") (component (type 3)))
    )
  )
  (export (;1;) (interface "foo:foo/wit") (type 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)