(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u8)
          (export (;1;) "t2" (type (eq 0)))
        )
      )
      (export (;0;) "shared" "pkg:/shared2/shared" (instance (type 0)))
    )
  )
  (export (;1;) "shared2" "pkg:/shared2" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u8)
          (export (;1;) "t1" (type (eq 0)))
        )
      )
      (export (;0;) "shared" "pkg:/shared1/shared" (instance (type 0)))
    )
  )
  (export (;3;) "shared1" "pkg:/shared1" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) u8)
              (export (;1;) "t1" (type (eq 0)))
            )
          )
          (import "shared1" "pkg:/shared1/shared" (instance (type 0)))
          (alias export 0 "t1" (type (;1;)))
          (type (;2;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "t1" (type (eq 0)))
            )
          )
          (import "foo" (instance (type 2)))
          (type (;3;)
            (instance
              (type (;0;) u8)
              (export (;1;) "t2" (type (eq 0)))
            )
          )
          (import "shared" "pkg:/shared2/shared" (instance (type 3)))
          (alias export 2 "t2" (type (;4;)))
          (type (;5;)
            (instance
              (alias outer 1 4 (type (;0;)))
              (export (;1;) "t2" (type (eq 0)))
            )
          )
          (import "bar" (instance (type 5)))
        )
      )
      (export (;0;) "w1" "pkg:/join/w1" (component (type 0)))
    )
  )
  (export (;5;) "join" "pkg:/join" (type 4))
)