(component
  (type (;0;)
    (component
      (type (;0;)
        (instance)
      )
      (export (;0;) "empty" "pkg:/empty/empty" (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance)
          )
          (import "empty" "pkg:/empty/empty" (instance (type 0)))
          (type (;1;)
            (instance)
          )
          (export (;0;) "empty2" "pkg:/empty/empty" (instance (type 1)))
        )
      )
      (export (;0;) "empty-world" "pkg:/empty/empty-world" (component (type 1)))
      (type (;2;)
        (component)
      )
      (export (;1;) "actually-empty-world" "pkg:/empty/actually-empty-world" (component (type 2)))
    )
  )
  (export (;1;) "empty" "pkg:/empty" (type 0))
)