(component
  (type (;0;)
    (component
      (type (;0;)
        (instance)
      )
      (export (;0;) (interface "foo:empty/empty") (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance)
          )
          (import (interface "foo:empty/empty") (instance (;0;) (type 0)))
          (type (;1;)
            (instance)
          )
          (import "empty" (instance (;1;) (type 1)))
          (type (;2;)
            (instance)
          )
          (export (;2;) (interface "foo:empty/empty") (instance (type 2)))
          (type (;3;)
            (instance)
          )
          (export (;3;) "empty2" (instance (type 3)))
        )
      )
      (export (;0;) (interface "foo:empty/empty-world") (component (type 1)))
      (type (;2;)
        (component)
      )
      (export (;1;) (interface "foo:empty/actually-empty-world") (component (type 2)))
    )
  )
  (export (;1;) (interface "foo:empty/wit") (type 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)