(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (func (param "x" float32)))
          (export (;0;) "float32-param" (func (type 0)))
          (type (;1;) (func (param "x" float64)))
          (export (;1;) "float64-param" (func (type 1)))
          (type (;2;) (func (result float32)))
          (export (;2;) "float32-result" (func (type 2)))
          (type (;3;) (func (result float64)))
          (export (;3;) "float64-result" (func (type 3)))
        )
      )
      (export (;0;) "floats" "pkg:/floats/floats" (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (func (param "x" float32)))
              (export (;0;) "float32-param" (func (type 0)))
              (type (;1;) (func (param "x" float64)))
              (export (;1;) "float64-param" (func (type 1)))
              (type (;2;) (func (result float32)))
              (export (;2;) "float32-result" (func (type 2)))
              (type (;3;) (func (result float64)))
              (export (;3;) "float64-result" (func (type 3)))
            )
          )
          (import "floats" "pkg:/floats/floats" (instance (type 0)))
        )
      )
      (export (;0;) "floats-world" "pkg:/floats/floats-world" (component (type 1)))
    )
  )
  (export (;1;) "floats" "pkg:/floats" (type 0))
)