(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record))
          (export (;1;) "the-type" (type (eq 0)))
        )
      )
      (export (;0;) "b" "pkg:/b/b" (instance (type 0)))
      (alias export 0 "the-type" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "the-type" (type (eq 0)))
        )
      )
      (export (;1;) "a" "pkg:/b/a" (instance (type 2)))
    )
  )
  (export (;1;) "b" "pkg:/b" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record))
          (export (;1;) "the-type" (type (eq 0)))
        )
      )
      (import "b2" "pkg:/b/b" (instance (type 0)))
      (alias export 0 "the-type" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "the-type" (type (eq 0)))
        )
      )
      (import "a2" "pkg:/b/a" (instance (type 2)))
      (alias export 1 "the-type" (type (;3;)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (export (;1;) "the-type" (type (eq 0)))
        )
      )
      (export (;0;) "b" "pkg:/a/b" (instance (type 4)))
      (alias export 2 "the-type" (type (;5;)))
      (type (;6;)
        (instance
          (alias outer 1 5 (type (;0;)))
          (export (;1;) "the-type" (type (eq 0)))
        )
      )
      (export (;1;) "a" "pkg:/a/a" (instance (type 6)))
    )
  )
  (export (;3;) "a" "pkg:/a" (type 2))
)