(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u8)
          (export (;1;) "t2" (type (eq 0)))
          (type (;2;) u8)
          (export (;3;) "t1" (type (eq 2)))
        )
      )
      (export (;0;) "foo" "pkg:/multiple-use/foo" (instance (type 0)))
      (type (;1;)
        (instance
          (type (;0;) u8)
          (export (;1;) "u" (type (eq 0)))
        )
      )
      (export (;1;) "bar" "pkg:/multiple-use/bar" (instance (type 1)))
      (alias export 0 "t1" (type (;2;)))
      (alias export 1 "u" (type (;3;)))
      (alias export 0 "t2" (type (;4;)))
      (type (;5;)
        (instance
          (alias outer 1 2 (type (;0;)))
          (export (;1;) "t1" (type (eq 0)))
          (alias outer 1 3 (type (;2;)))
          (export (;3;) "u" (type (eq 2)))
          (alias outer 1 4 (type (;4;)))
          (export (;5;) "t2" (type (eq 4)))
        )
      )
      (export (;2;) "baz" "pkg:/multiple-use/baz" (instance (type 5)))
    )
  )
  (export (;1;) "multiple-use" "pkg:/multiple-use" (type 0))
)