(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "foo" string)))
          (export (;1;) "my-record" (type (eq 0)))
          (type (;2;) (func (result string)))
          (export (;0;) "hello" (func (type 2)))
          (type (;3;)
            (instance
              (type (;0;) (record (field "foo" string)))
              (export (;1;) "nest-record" (type (eq 0)))
              (type (;2;) (func (result 1)))
              (export (;0;) "goodbye" (func (type 2)))
              (type (;3;)
                (instance
                  (type (;0;) (record (field "foo" string)))
                  (export (;1;) "deep-record" (type (eq 0)))
                  (type (;2;) string)
                  (export (;3;) "anything" (type (eq 2)))
                )
              )
              (export (;0;) "foo:nestnest/deep" (instance (type 3)))
            )
          )
          (export (;0;) "foo:nestee/things@1.0.0" (instance (type 3)))
          (type (;4;)
            (instance
              (export (;0;) "foo" (type (sub resource)))
              (type (;1;) (borrow 0))
              (type (;2;) (option string))
              (type (;3;) (func (param "self" 1) (result 2)))
              (export (;0;) "[method]foo.bar" (func (type 3)))
            )
          )
          (export (;1;) "foo:nestee/more@1.0.0" (instance (type 4)))
        )
      )
      (export (;0;) "foo:thing/something@1.0.0" (instance (type 0)))
    )
  )
  (export (;1;) "something" (type 0))
  (@custom "package-docs" "\01{\22interfaces\22:{\22something\22:{\22types\22:{\22my-record\22:{\22stability\22:{\22stable\22:{\22since\22:\221.0.0\22}}}},\22nested\22:{\22things\22:{\22docs\22:{\22contents\22:\22nesting can be documented\22},\22stability\22:\22unknown\22},\22more\22:{\22docs\22:{\22contents\22:null},\22stability\22:{\22stable\22:{\22since\22:\221.0.0\22}}}}}}}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
