(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (import "local:types/point" (type (;1;) (eq 0)))
  (type (;2;) (record (field "p" 1)))
  (export (;3;) "bin" (type 2))
  (type (;4;)
    (component
      (type (;0;) (record (field "x" u32) (field "y" u32)))
      (import "local:types/point" (type (;1;) (eq 0)))
      (type (;2;) (record (field "p" 1)))
      (import "local:consumer/bin" (type (;3;) (eq 2)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (type (;1;) (func (param "b" 0)))
          (export (;0;) "wrap" (func (type 1)))
          (alias outer 1 1 (type (;2;)))
          (type (;3;) (func (param "p" 2)))
          (export (;1;) "move-to" (func (type 3)))
        )
      )
      (export (;0;) "local:consumer/api" (instance (type 4)))
    )
  )
  (export (;5;) "api" (type 4))
  (type (;6;)
    (component
      (type (;0;)
        (component
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (import "local:types/point" (type (;1;) (eq 0)))
          (type (;2;) (record (field "p" 1)))
          (import "local:consumer/bin" (type (;3;) (eq 2)))
          (type (;4;)
            (instance
              (alias outer 1 3 (type (;0;)))
              (type (;1;) (func (param "b" 0)))
              (export (;0;) "wrap" (func (type 1)))
              (alias outer 1 1 (type (;2;)))
              (type (;3;) (func (param "p" 2)))
              (export (;1;) "move-to" (func (type 3)))
            )
          )
          (export (;0;) "local:consumer/api" (instance (type 4)))
        )
      )
      (export (;0;) "local:consumer/w" (component (type 0)))
    )
  )
  (export (;7;) "w" (type 6))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
