(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (external-id "pkg-point") (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (option string))
          (type (;1;) (func (param "key" string) (result 0)))
          (export (;0;) "get" (func (type 1)))
        )
      )
      (export (;0;) "local:demo/store" (instance (type 0)))
    )
  )
  (export (;3;) "store" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (option string))
              (type (;1;) (func (param "key" string) (result 0)))
              (export (;0;) "get" (func (type 1)))
            )
          )
          (import "primary" (implements "local:demo/store") (instance (;0;) (type 0)))
          (type (;1;)
            (instance
              (type (;0;) (option string))
              (type (;1;) (func (param "key" string) (result 0)))
              (export (;0;) "get" (func (type 1)))
            )
          )
          (import "backup" (implements "local:demo/store") (instance (;1;) (type 1)))
          (type (;2;) (record (field "x" u32) (field "y" u32)))
          (import "local:demo/point" (external-id "pkg-point") (type (;3;) (eq 2)))
          (type (;4;) (func (param "p" 3)))
          (import "move-to" (external-id "world-move") (func (;0;) (type 4)))
          (export (;1;) "place" (func (type 4)))
        )
      )
      (export (;0;) "local:demo/w" (component (type 0)))
    )
  )
  (export (;5;) "w" (type 4))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
