(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "file" (type (sub resource)))
          (type (;1;) (borrow 0))
          (type (;2;) (func (param "self" 1) (result string)))
          (export (;0;) "[method]file.path" (func (type 2)))
        )
      )
      (export (;0;) "local:demo/files" (instance (type 0)))
    )
  )
  (export (;3;) "files" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (instance
          (export (;0;) "file" (type (sub resource)))
        )
      )
      (import "local:demo/files" (instance (;0;) (type 0)))
      (alias export 0 "file" (type (;1;)))
      (type (;2;) (record (field "x" u32) (field "y" u32)))
      (import "local:demo/point" (type (;3;) (eq 2)))
      (type (;4;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "file" (type (eq 0)))
          (alias outer 1 3 (type (;2;)))
          (type (;3;) (func (param "p" 2)))
          (export (;0;) "move-to" (func (type 3)))
          (type (;4;) (own 1))
          (type (;5;) (func (result 4)))
          (export (;1;) "open" (func (type 5)))
        )
      )
      (export (;1;) "local:demo/api" (instance (type 4)))
    )
  )
  (export (;5;) "api" (type 4))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
