(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;) (record (field "p" 1)))
  (export (;3;) "bin" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (export (;1;) "point" (type (eq 0)))
          (type (;2;) (record (field "p" 1)))
          (export (;3;) "bin" (type (eq 2)))
          (type (;4;) (func (param "b" 3)))
          (export (;0;) "wrap" (func (type 4)))
          (type (;5;) (func (param "p" 1)))
          (export (;1;) "move-to" (func (type 5)))
        )
      )
      (export (;0;) "local:consumer/api" (instance (type 0)))
    )
  )
  (export (;5;) "api" (type 4))
  (type (;6;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (record (field "x" u32) (field "y" u32)))
              (export (;1;) "point" (type (eq 0)))
              (type (;2;) (record (field "p" 1)))
              (export (;3;) "bin" (type (eq 2)))
              (type (;4;) (func (param "b" 3)))
              (export (;0;) "wrap" (func (type 4)))
              (type (;5;) (func (param "p" 1)))
              (export (;1;) "move-to" (func (type 5)))
            )
          )
          (export (;0;) "local:consumer/api" (instance (type 0)))
        )
      )
      (export (;0;) "local:consumer/w" (component (type 0)))
    )
  )
  (export (;7;) "w" (type 6))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
