(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) string)
          (export (;1;) "tag" (type (eq 0)))
        )
      )
      (export (;0;) "local:demo/types" (instance (type 0)))
    )
  )
  (export (;3;) "types" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) string)
              (export (;1;) "tag" (type (eq 0)))
            )
          )
          (import "local:demo/types" (instance (;0;) (type 0)))
          (alias export 0 "tag" (type (;1;)))
          (import "tag" (type (;2;) (eq 1)))
          (type (;3;) (record (field "x" u32) (field "y" u32)))
          (import "local:demo/point" (type (;4;) (eq 3)))
          (type (;5;) (func (param "p" 4)))
          (import "move-to" (func (;0;) (type 5)))
          (type (;6;) (func (param "t" 2) (result 4)))
          (export (;1;) "label" (func (type 6)))
        )
      )
      (export (;0;) "local:demo/w" (component (type 0)))
    )
  )
  (export (;5;) "w" (type 4))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
