(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;) (variant (case "circle" u32) (case "rect" 1)))
  (export (;3;) "shape" (type 2))
  (type (;4;) (flags "bold" "italic"))
  (export (;5;) "style" (type 4))
  (type (;6;) (enum "north" "south" "east" "west"))
  (export (;7;) "direction" (type 6))
  (type (;8;) (list 1))
  (export (;9;) "path" (type 8))
  (type (;10;)
    (component
      (type (;0;) (record (field "x" u32) (field "y" u32)))
      (import "local:demo/point" (type (;1;) (eq 0)))
      (type (;2;) (enum "north" "south" "east" "west"))
      (import "local:demo/direction" (type (;3;) (eq 2)))
      (type (;4;) (list 1))
      (import "local:demo/path" (type (;5;) (eq 4)))
      (type (;6;) (variant (case "circle" u32) (case "rect" 1)))
      (import "local:demo/shape" (type (;7;) (eq 6)))
      (type (;8;) (flags "bold" "italic"))
      (import "local:demo/style" (type (;9;) (eq 8)))
      (type (;10;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (type (;1;) (func (param "p" 0)))
          (export (;0;) "move-to" (func (type 1)))
          (alias outer 1 3 (type (;2;)))
          (type (;3;) (func (result 2)))
          (export (;1;) "heading" (func (type 3)))
          (alias outer 1 5 (type (;4;)))
          (type (;5;) (func (result 4)))
          (export (;2;) "trail" (func (type 5)))
          (alias outer 1 7 (type (;6;)))
          (alias outer 1 9 (type (;7;)))
          (type (;8;) (func (param "s" 6) (param "style" 7)))
          (export (;3;) "draw" (func (type 8)))
        )
      )
      (export (;0;) "local:demo/api" (instance (type 10)))
    )
  )
  (export (;11;) "api" (type 10))
  (type (;12;)
    (component
      (type (;0;)
        (component
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (import "local:demo/point" (type (;1;) (eq 0)))
          (type (;2;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (type (;1;) (func (param "p" 0)))
              (export (;0;) "place" (func (type 1)))
            )
          )
          (import "host" (instance (;0;) (type 2)))
          (type (;3;) (enum "north" "south" "east" "west"))
          (import "local:demo/direction" (type (;4;) (eq 3)))
          (type (;5;) (list 1))
          (import "local:demo/path" (type (;6;) (eq 5)))
          (type (;7;) (variant (case "circle" u32) (case "rect" 1)))
          (import "local:demo/shape" (type (;8;) (eq 7)))
          (type (;9;) (flags "bold" "italic"))
          (import "local:demo/style" (type (;10;) (eq 9)))
          (type (;11;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (type (;1;) (func (param "p" 0)))
              (export (;0;) "move-to" (func (type 1)))
              (alias outer 1 4 (type (;2;)))
              (type (;3;) (func (result 2)))
              (export (;1;) "heading" (func (type 3)))
              (alias outer 1 6 (type (;4;)))
              (type (;5;) (func (result 4)))
              (export (;2;) "trail" (func (type 5)))
              (alias outer 1 8 (type (;6;)))
              (alias outer 1 10 (type (;7;)))
              (type (;8;) (func (param "s" 6) (param "style" 7)))
              (export (;3;) "draw" (func (type 8)))
            )
          )
          (export (;1;) "local:demo/api" (instance (type 11)))
        )
      )
      (export (;0;) "local:demo/w" (component (type 0)))
    )
  )
  (export (;13;) "w" (type 12))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
