(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (component
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (import "point" (type (;1;) (eq 0)))
          (type (;2;) (func (param "p" 1)))
          (import "move-to" (func (;0;) (type 2)))
          (export (;1;) "place" (func (type 2)))
          (type (;3;) (list 1))
          (type (;4;) (func (result 3)))
          (export (;2;) "trail" (func (type 4)))
        )
      )
      (export (;0;) "local:demo/w" (component (type 0)))
    )
  )
  (export (;3;) "w" (type 2))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
