(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;)
    (component
      (type (;0;) (record (field "x" u32) (field "y" u32)))
      (import "foo:foo/point" (type (;1;) (eq 0)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "pt" (type (eq 0)))
          (type (;2;) (func (result 1)))
          (export (;0;) "get" (func (type 2)))
        )
      )
      (export (;0;) "foo:foo/api" (instance (type 2)))
    )
  )
  (export (;3;) "api" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (component
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (import "foo:foo/point" (type (;1;) (eq 0)))
          (type (;2;)
            (instance
              (alias outer 1 1 (type (;0;)))
              (export (;1;) "pt" (type (eq 0)))
              (type (;2;) (func (result 1)))
              (export (;0;) "get" (func (type 2)))
            )
          )
          (import "foo:foo/api" (instance (;0;) (type 2)))
          (import "wpt" (type (;3;) (eq 1)))
          (type (;4;) (func (result 3)))
          (export (;0;) "run" (func (type 4)))
        )
      )
      (export (;0;) "foo:foo/w" (component (type 0)))
    )
  )
  (export (;5;) "w" (type 4))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
