(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;) (variant (case "circle") (case "rect" 1)))
  (export (;3;) "shape" (type 2))
  (type (;4;) (flags "bold" "italic"))
  (export (;5;) "style" (type 4))
  (type (;6;) (enum "north" "south"))
  (export (;7;) "direction" (type 6))
  (type (;8;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (export (;1;) "point" (type (eq 0)))
          (type (;2;) (variant (case "circle") (case "rect" 1)))
          (export (;3;) "shape" (type (eq 2)))
          (type (;4;) (flags "bold" "italic"))
          (export (;5;) "style" (type (eq 4)))
          (type (;6;) (func (param "s" 3) (param "style" 5)))
          (export (;0;) "draw" (func (type 6)))
          (type (;7;) (enum "north" "south"))
          (export (;8;) "direction" (type (eq 7)))
          (type (;9;) (func (result 8)))
          (export (;1;) "heading" (func (type 9)))
        )
      )
      (export (;0;) "local:demo/api" (instance (type 0)))
    )
  )
  (export (;9;) "api" (type 8))
  (type (;10;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (record (field "x" u32) (field "y" u32)))
              (export (;1;) "point" (type (eq 0)))
              (type (;2;) (variant (case "circle") (case "rect" 1)))
              (export (;3;) "shape" (type (eq 2)))
              (type (;4;) (flags "bold" "italic"))
              (export (;5;) "style" (type (eq 4)))
              (type (;6;) (func (param "s" 3) (param "style" 5)))
              (export (;0;) "draw" (func (type 6)))
              (type (;7;) (enum "north" "south"))
              (export (;8;) "direction" (type (eq 7)))
              (type (;9;) (func (result 8)))
              (export (;1;) "heading" (func (type 9)))
            )
          )
          (export (;0;) "local:demo/api" (instance (type 0)))
        )
      )
      (export (;0;) "local:demo/w" (component (type 0)))
    )
  )
  (export (;11;) "w" (type 10))
  (@custom "package-docs" "\01{\22types\22:{\22point\22:{\22docs\22:\22A shared point type at package scope.\22,\22items\22:{\22x\22:\22X coordinate\22,\22y\22:\22Y coordinate\22}},\22shape\22:{\22docs\22:\22Geometric shape using package-scope point.\22,\22items\22:{\22circle\22:\22Unit circle case\22,\22rect\22:\22Rectangle backed by a point\22}},\22style\22:{\22items\22:{\22bold\22:\22Bold text\22}},\22direction\22:{\22items\22:{\22north\22:\22Facing north\22}}}}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
