(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;) (variant (case "circle" u32) (case "rect" 1)))
  (export (;3;) "shape" (type 2))
  (type (;4;) (flags "bold" "italic"))
  (export (;5;) "style" (type 4))
  (type (;6;) (enum "north" "south" "east" "west"))
  (export (;7;) "direction" (type 6))
  (type (;8;) (list 1))
  (export (;9;) "path" (type 8))
  (type (;10;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record (field "x" u32) (field "y" u32)))
          (export (;1;) "point" (type (eq 0)))
          (type (;2;) (func (param "p" 1)))
          (export (;0;) "move-to" (func (type 2)))
          (type (;3;) (enum "north" "south" "east" "west"))
          (export (;4;) "direction" (type (eq 3)))
          (type (;5;) (func (result 4)))
          (export (;1;) "heading" (func (type 5)))
          (type (;6;) (list 1))
          (export (;7;) "path" (type (eq 6)))
          (type (;8;) (func (result 7)))
          (export (;2;) "trail" (func (type 8)))
          (type (;9;) (variant (case "circle" u32) (case "rect" 1)))
          (export (;10;) "shape" (type (eq 9)))
          (type (;11;) (flags "bold" "italic"))
          (export (;12;) "style" (type (eq 11)))
          (type (;13;) (func (param "s" 10) (param "style" 12)))
          (export (;3;) "draw" (func (type 13)))
        )
      )
      (export (;0;) "local:demo/api" (instance (type 0)))
    )
  )
  (export (;11;) "api" (type 10))
  (type (;12;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (record (field "x" u32) (field "y" u32)))
              (export (;1;) "point" (type (eq 0)))
              (type (;2;) (func (param "p" 1)))
              (export (;0;) "place" (func (type 2)))
            )
          )
          (import "host" (instance (;0;) (type 0)))
          (type (;1;)
            (instance
              (type (;0;) (record (field "x" u32) (field "y" u32)))
              (export (;1;) "point" (type (eq 0)))
              (type (;2;) (func (param "p" 1)))
              (export (;0;) "move-to" (func (type 2)))
              (type (;3;) (enum "north" "south" "east" "west"))
              (export (;4;) "direction" (type (eq 3)))
              (type (;5;) (func (result 4)))
              (export (;1;) "heading" (func (type 5)))
              (type (;6;) (list 1))
              (export (;7;) "path" (type (eq 6)))
              (type (;8;) (func (result 7)))
              (export (;2;) "trail" (func (type 8)))
              (type (;9;) (variant (case "circle" u32) (case "rect" 1)))
              (export (;10;) "shape" (type (eq 9)))
              (type (;11;) (flags "bold" "italic"))
              (export (;12;) "style" (type (eq 11)))
              (type (;13;) (func (param "s" 10) (param "style" 12)))
              (export (;3;) "draw" (func (type 13)))
            )
          )
          (export (;1;) "local:demo/api" (instance (type 1)))
        )
      )
      (export (;0;) "local:demo/w" (component (type 0)))
    )
  )
  (export (;13;) "w" (type 12))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
