(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (enum "info" "debug"))
          (export (;1;) "level" (type (eq 0)))
        )
      )
      (export (;0;) "local:demo/types" (instance (type 0)))
    )
  )
  (export (;3;) "types" (type 2))
  (type (;4;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (enum "info" "debug"))
          (export (;1;) "level" (type (eq 0)))
        )
      )
      (import "local:demo/types" (instance (;0;) (type 0)))
      (alias export 0 "level" (type (;1;)))
      (type (;2;) (record (field "x" u32) (field "y" u32)))
      (import "local:demo/point" (type (;3;) (eq 2)))
      (type (;4;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "level" (type (eq 0)))
          (alias outer 1 3 (type (;2;)))
          (type (;3;) (func (param "p" 2)))
          (export (;0;) "move-to" (func (type 3)))
          (type (;4;) (func (param "level" 1) (param "msg" string)))
          (export (;1;) "log" (func (type 4)))
        )
      )
      (export (;1;) "local:demo/api" (instance (type 4)))
    )
  )
  (export (;5;) "api" (type 4))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
