(component
  (type (;0;) (record (field "x" u32) (field "y" u32)))
  (export (;1;) "point" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (option string))
          (type (;1;) (func (param "key" string) (result 0)))
          (export (;0;) "get" (func (type 1)))
          (type (;2;) (func (param "key" string) (param "value" string)))
          (export (;1;) "set" (func (type 2)))
        )
      )
      (export (;0;) "local:demo/store" (instance (type 0)))
    )
  )
  (export (;3;) "store" (type 2))
  (type (;4;)
    (component
      (type (;0;) (record (field "x" u32) (field "y" u32)))
      (import "local:demo/point" (type (;1;) (eq 0)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (type (;1;) (func (param "p" 0)))
          (export (;0;) "move-to" (func (type 1)))
        )
      )
      (export (;0;) "local:demo/api" (instance (type 2)))
    )
  )
  (export (;5;) "api" (type 4))
  (type (;6;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (option string))
              (type (;1;) (func (param "key" string) (result 0)))
              (export (;0;) "get" (func (type 1)))
              (type (;2;) (func (param "key" string) (param "value" string)))
              (export (;1;) "set" (func (type 2)))
            )
          )
          (import "primary" (implements "local:demo/store") (instance (;0;) (type 0)))
          (type (;1;)
            (instance
              (type (;0;) (option string))
              (type (;1;) (func (param "key" string) (result 0)))
              (export (;0;) "get" (func (type 1)))
              (type (;2;) (func (param "key" string) (param "value" string)))
              (export (;1;) "set" (func (type 2)))
            )
          )
          (import "backup" (implements "local:demo/store") (instance (;1;) (type 1)))
          (type (;2;) (record (field "x" u32) (field "y" u32)))
          (import "local:demo/point" (type (;3;) (eq 2)))
          (type (;4;) (func (param "p" 3)))
          (import "move-to" (func (;0;) (type 4)))
        )
      )
      (export (;0;) "local:demo/multi-import" (component (type 0)))
    )
  )
  (export (;7;) "multi-import" (type 6))
  (type (;8;)
    (component
      (type (;0;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (option string))
              (type (;1;) (func (param "key" string) (result 0)))
              (export (;0;) "get" (func (type 1)))
              (type (;2;) (func (param "key" string) (param "value" string)))
              (export (;1;) "set" (func (type 2)))
            )
          )
          (import "local:demo/store" (instance (;0;) (type 0)))
          (type (;1;)
            (instance
              (type (;0;) (option string))
              (type (;1;) (func (param "key" string) (result 0)))
              (export (;0;) "get" (func (type 1)))
              (type (;2;) (func (param "key" string) (param "value" string)))
              (export (;1;) "set" (func (type 2)))
            )
          )
          (import "cache" (implements "local:demo/store") (instance (;1;) (type 1)))
          (type (;2;) (record (field "x" u32) (field "y" u32)))
          (import "local:demo/point" (type (;3;) (eq 2)))
          (type (;4;)
            (instance
              (alias outer 1 3 (type (;0;)))
              (type (;1;) (func (param "p" 0)))
              (export (;0;) "move-to" (func (type 1)))
            )
          )
          (export (;2;) "local:demo/api" (instance (type 4)))
        )
      )
      (export (;0;) "local:demo/mixed" (component (type 0)))
    )
  )
  (export (;9;) "mixed" (type 8))
  (@custom "package-docs" "\01{}")
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
