(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record))
          (export (;1;) "name" (type (eq 0)))
        )
      )
      (export (;0;) "other" "pkg:/bar/other" (instance (type 0)))
      (alias export 0 "name" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "the-name" (type (eq 0)))
          (type (;2;) (enum "a"))
          (export (;3;) "name" (type (eq 2)))
        )
      )
      (export (;1;) "d" "pkg:/bar/d" (instance (type 2)))
    )
  )
  (export (;1;) "bar" "pkg:/bar" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record))
          (export (;1;) "name" (type (eq 0)))
        )
      )
      (import "other" "pkg:/bar/other" (instance (type 0)))
      (alias export 0 "name" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "the-name" (type (eq 0)))
          (type (;2;) (enum "a"))
          (export (;3;) "name" (type (eq 2)))
        )
      )
      (import "d" "pkg:/bar/d" (instance (type 2)))
      (alias export 1 "the-name" (type (;3;)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (export (;1;) "the-name" (type (eq 0)))
        )
      )
      (export (;0;) "foo" "pkg:/foo/foo" (instance (type 4)))
    )
  )
  (export (;3;) "foo" "pkg:/foo" (type 2))
)