(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u8)
          (export (;1;) "a" (type (eq 0)))
        )
      )
      (export (;0;) "a" "pkg:/def/a" (instance (type 0)))
      (alias export 0 "a" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "a" (type (eq 0)))
          (type (;2;) (enum "other"))
          (export (;3;) "name" (type (eq 2)))
        )
      )
      (export (;1;) "name" "pkg:/def/name" (instance (type 2)))
    )
  )
  (export (;1;) "def" "pkg:/def" (type 0))
  (type (;2;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u8)
          (export (;1;) "a" (type (eq 0)))
        )
      )
      (import "a" "pkg:/def/a" (instance (type 0)))
      (alias export 0 "a" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "a" (type (eq 0)))
          (type (;2;) (enum "other"))
          (export (;3;) "name" (type (eq 2)))
        )
      )
      (import "name" "pkg:/def/name" (instance (type 2)))
      (alias export 1 "name" (type (;3;)))
      (type (;4;)
        (instance
          (alias outer 1 3 (type (;0;)))
          (export (;1;) "name" (type (eq 0)))
        )
      )
      (export (;0;) "foo" "pkg:/the-use/foo" (instance (type 4)))
    )
  )
  (export (;3;) "the-use" "pkg:/the-use" (type 2))
)