(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (record))
          (export (;1;) "ty" (type (eq 0)))
          (type (;2;) (enum "b"))
          (export (;3;) "a" (type (eq 2)))
        )
      )
      (import "foo" "path:/dep/foo/foo" (instance (type 0)))
      (alias export 0 "ty" (type (;1;)))
      (type (;2;)
        (instance
          (alias outer 1 1 (type (;0;)))
          (export (;1;) "ty" (type (eq 0)))
        )
      )
      (export (;0;) "foo" "pkg:/foo/foo" (instance (type 2)))
      (type (;3;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (record))
              (export (;1;) "ty" (type (eq 0)))
              (type (;2;) (enum "b"))
              (export (;3;) "a" (type (eq 2)))
            )
          )
          (import "foo" "path:/dep/foo/foo" (instance (type 0)))
        )
      )
      (export (;0;) "bar" "pkg:/foo/bar" (component (type 3)))
    )
  )
  (export (;1;) "foo" "pkg:/foo" (type 0))
)