(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (variant (case "s" u32)))
          (export (;1;) "v-no-string" (type (eq 0)))
          (type (;2;) (variant (case "s" string)))
          (export (;3;) "v" (type (eq 2)))
          (type (;4;) (record (field "s" u32)))
          (export (;5;) "r-no-string" (type (eq 4)))
          (type (;6;) (record (field "s" string)))
          (export (;7;) "r" (type (eq 6)))
          (type (;8;) (func (param "x" 7)))
          (export (;0;) "a" (func (type 8)))
          (type (;9;) (func (param "x" 3)))
          (export (;1;) "b" (func (type 9)))
          (type (;10;) (func (param "x" 5)))
          (export (;2;) "c" (func (type 10)))
          (type (;11;) (func (param "x" 1)))
          (export (;3;) "d" (func (type 11)))
        )
      )
      (export (;0;) "foo" "pkg:/reference-out-of-order/foo" (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (variant (case "s" u32)))
              (export (;1;) "v-no-string" (type (eq 0)))
              (type (;2;) (variant (case "s" string)))
              (export (;3;) "v" (type (eq 2)))
              (type (;4;) (record (field "s" u32)))
              (export (;5;) "r-no-string" (type (eq 4)))
              (type (;6;) (record (field "s" string)))
              (export (;7;) "r" (type (eq 6)))
              (type (;8;) (func (param "x" 7)))
              (export (;0;) "a" (func (type 8)))
              (type (;9;) (func (param "x" 3)))
              (export (;1;) "b" (func (type 9)))
              (type (;10;) (func (param "x" 5)))
              (export (;2;) "c" (func (type 10)))
              (type (;11;) (func (param "x" 1)))
              (export (;3;) "d" (func (type 11)))
            )
          )
          (import "foo" "pkg:/reference-out-of-order/foo" (instance (type 0)))
        )
      )
      (export (;0;) "foo-world" "pkg:/reference-out-of-order/foo-world" (component (type 1)))
    )
  )
  (export (;1;) "reference-out-of-order" "pkg:/reference-out-of-order" (type 0))
)