(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (flags "b"))
          (export (;1;) "a" (type (eq 0)))
          (export (;2;) "b" (type (eq 1)))
          (type (;3;) (func (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (export (;0;) "foo" "pkg:/type-alias2/foo" (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance
              (type (;0;) (flags "b"))
              (export (;1;) "a" (type (eq 0)))
              (export (;2;) "b" (type (eq 1)))
              (type (;3;) (func (result 2)))
              (export (;0;) "f" (func (type 3)))
            )
          )
          (export (;0;) "foo" "pkg:/type-alias2/foo" (instance (type 0)))
        )
      )
      (export (;0;) "my-world" "pkg:/type-alias2/my-world" (component (type 1)))
    )
  )
  (export (;1;) "type-alias2" "pkg:/type-alias2" (type 0))
)