(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u8)
          (export (;1;) "a" (type (eq 0)))
          (export (;2;) "b" (type (eq 1)))
          (type (;3;) (func (param "a" 1) (result 2)))
          (export (;0;) "f" (func (type 3)))
        )
      )
      (export (;0;) "foo" "pkg:/type-alias/foo" (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance
              (type (;0;) u8)
              (export (;1;) "a" (type (eq 0)))
              (export (;2;) "b" (type (eq 1)))
              (type (;3;) (func (param "a" 1) (result 2)))
              (export (;0;) "f" (func (type 3)))
            )
          )
          (import "foo" "pkg:/type-alias/foo" (instance (type 0)))
          (type (;1;)
            (instance
              (type (;0;) u8)
              (export (;1;) "a" (type (eq 0)))
              (export (;2;) "b" (type (eq 1)))
              (type (;3;) (func (param "a" 1) (result 2)))
              (export (;0;) "f" (func (type 3)))
            )
          )
          (export (;0;) "foo" "pkg:/type-alias/foo" (instance (type 1)))
        )
      )
      (export (;0;) "my-world" "pkg:/type-alias/my-world" (component (type 1)))
    )
  )
  (export (;1;) "type-alias" "pkg:/type-alias" (type 0))
)