(component
  (type (;0;)
    (component
      (type (;0;)
        (instance)
      )
      (export (;0;) (interface "foo:foo/foo") (instance (type 0)))
      (type (;1;)
        (instance
          (type (;0;) u8)
          (export (;1;) "t" (type (eq 0)))
        )
      )
      (export (;1;) (interface "foo:foo/bar") (instance (type 1)))
      (alias export 1 "t" (type (;2;)))
      (type (;3;)
        (instance
          (alias outer 1 2 (type (;0;)))
          (export (;1;) "t" (type (eq 0)))
          (type (;2;) (record (field "a" 1)))
          (export (;3;) "bar" (type (eq 2)))
        )
      )
      (export (;2;) (interface "foo:foo/baz") (instance (type 3)))
    )
  )
  (export (;1;) (interface "foo:foo/wit") (type 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)