(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) u32)
          (export (;1;) "foo" (type (eq 0)))
        )
      )
      (export (;0;) "import-me" "pkg:/worlds-with-types/import-me" (instance (type 0)))
      (type (;1;)
        (component
          (type (;0;)
            (instance
              (type (;0;) u32)
              (export (;1;) "foo" (type (eq 0)))
            )
          )
          (import "import-me" "pkg:/worlds-with-types/import-me" (instance (type 0)))
          (alias export 0 "foo" (type (;1;)))
          (import "foo" (type (eq 1)))
          (type (;2;) (func (param "a" 2)))
          (import "a" (func (type 3)))
          (export (;0;) "b" (func (type 3)))
        )
      )
      (export (;0;) "with-imports" "pkg:/worlds-with-types/with-imports" (component (type 1)))
      (type (;2;)
        (component
          (type (;0;) (record))
          (import "foo" (type (eq 0)))
          (import "bar" (type (eq 1)))
          (type (;1;) (func (param "a" 1) (result 2)))
          (import "a" (func (type 3)))
          (export (;0;) "b" (func (type 3)))
        )
      )
      (export (;1;) "simple" "pkg:/worlds-with-types/simple" (component (type 2)))
    )
  )
  (export (;1;) "worlds-with-types" "pkg:/worlds-with-types" (type 0))
)