[package]
name = "rot26"
version = "0.1.0"
edition = "2021"

[dependencies]
rot26 = "0.1.2"
wit-bindgen-rust = { git = "https://github.com/bytecodealliance/wit-bindgen", default_features = false }

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
direct-interface-export = "encryption"

[package.metadata.component.exports]
encryption = "../encryption.wit"

[workspace]
