(component
  (type (;0;) (func (param "x" float32)))
  (type (;1;) (func (param "x" float64)))
  (type (;2;) (func (result float32)))
  (type (;3;) (func (result float64)))
  (export "float32-param" (type 0))
  (export "float64-param" (type 1))
  (export "float32-result" (type 2))
  (export "float64-result" (type 3))
)