(component
  (type (;0;)
    (instance
      (type (;0;) (func (param "x" float32)))
      (export "float32-param" (func (type 0)))
      (type (;1;) (func (param "x" float64)))
      (export "float64-param" (func (type 1)))
      (type (;2;) (func (result float32)))
      (export "float32-result" (func (type 2)))
      (type (;3;) (func (result float64)))
      (export "float64-result" (func (type 3)))
    )
  )
  (import "floats" (instance (;0;) (type 0)))
)