interface handler {
    record request {
        headers: list<tuple<list<u8>, list<u8>>>,
        body: list<u8>,
    }

    record response {
        headers: list<tuple<list<u8>, list<u8>>>,
        body: list<u8>
    }

    enum error {
        bad-request,
    }

    execute: func(req: request) -> result<response, error>
}

default world service {
    export handler: self.handler
}

world middleware {
    import downstream: self.handler
    export handler: self.handler
}
