package example:service@0.1.0

interface handler {
    record request {
        headers: list<tuple<list<u8>, list<u8>>>,
        body: list<u8>,
    }

    record response {
        headers: list<tuple<list<u8>, list<u8>>>,
        body: list<u8>
    }

    enum error {
        bad-request,
    }

    execute: func(req: request) -> result<response, error>
}

world service {
    export handler
}

world middleware {
    import handler
    export handler
}
