interface adapter-imports {
  foo: func(x: string)
}

default world component {
  import foo: func(x: string)
  import adapter-imports: self.adapter-imports
  export bar: func()
  export adapter-bar: func(x: string)
}
