(component
  (core module $main (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32 i32) (result i32)))
    (type (;2;) (func (param i32 i32 i32) (result i32)))
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (import "[export]$root" "[task-cancel]" (func (;0;) (type 0)))
    (import "[export]$root" "[task-return]foo" (func (;1;) (type 0)))
    (memory (;0;) 1)
    (export "[async-lift]foo" (func 2))
    (export "[callback][async-lift]foo" (func 3))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 4))
    (func (;2;) (type 1) (param i32 i32) (result i32)
      unreachable
    )
    (func (;3;) (type 2) (param i32 i32 i32) (result i32)
      unreachable
    )
    (func (;4;) (type 3) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core func $task.cancel (;0;) (canon task.cancel))
  (core func $task.return (;1;) (canon task.return))
  (core instance $"[export]$root" (;0;)
    (export "[task-cancel]" (func $task.cancel))
    (export "[task-return]foo" (func $task.return))
  )
  (core instance $main (;1;) (instantiate $main
      (with "[export]$root" (instance $"[export]$root"))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (type (;0;) (func (param "s" string)))
  (alias core export $main "[async-lift]foo" (core func $"[async-lift]foo" (;2;)))
  (alias core export $main "cabi_realloc" (core func $cabi_realloc (;3;)))
  (alias core export $main "[callback][async-lift]foo" (core func $"[callback][async-lift]foo" (;4;)))
  (func $foo (;0;) (type 0) (canon lift (core func $"[async-lift]foo") (memory $memory) (realloc $cabi_realloc) string-encoding=utf8 async (callback $"[callback][async-lift]foo")))
  (export $"#func1 foo" (@name "foo") (;1;) "foo" (func $foo))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
