(component
  (core module $main (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32 i32) (result i32)))
    (type (;2;) (func (param i32 i32 i32) (result i32)))
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (import "[export]$root" "[task-cancel]" (func (;0;) (type 0)))
    (import "[export]$root" "[task-return]foo" (func (;1;) (type 0)))
    (memory (;0;) 1)
    (export "[async-lift]foo" (func 2))
    (export "[callback][async-lift]foo" (func 3))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 4))
    (func (;2;) (type 1) (param i32 i32) (result i32)
      unreachable
    )
    (func (;3;) (type 2) (param i32 i32 i32) (result i32)
      unreachable
    )
    (func (;4;) (type 3) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func))
    (table (;0;) 1 1 funcref)
    (export "0" (func $task-return-foo))
    (export "$imports" (table 0))
    (func $task-return-foo (;0;) (type 0)
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (core func $task.cancel (;0;) (canon task.cancel))
  (alias core export $wit-component-shim-instance "0" (core func $task-return-foo (;1;)))
  (core instance $"[export]$root" (;1;)
    (export "[task-cancel]" (func $task.cancel))
    (export "[task-return]foo" (func $task-return-foo))
  )
  (core instance $main (;2;) (instantiate $main
      (with "[export]$root" (instance $"[export]$root"))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (alias core export $wit-component-shim-instance "$imports" (core table $"shim table" (;0;)))
  (alias core export $main "cabi_realloc" (core func $realloc (;2;)))
  (core func $task.return (;3;) (canon task.return (memory $memory) string-encoding=utf8))
  (core instance $fixup-args (;3;)
    (export "$imports" (table $"shim table"))
    (export "0" (func $task.return))
  )
  (core instance $fixup (;4;) (instantiate $wit-component-fixup
      (with "" (instance $fixup-args))
    )
  )
  (type (;0;) (func (param "s" string)))
  (alias core export $main "[async-lift]foo" (core func $"[async-lift]foo" (;4;)))
  (alias core export $main "[callback][async-lift]foo" (core func $"[callback][async-lift]foo" (;5;)))
  (func $foo (;0;) (type 0) (canon lift (core func $"[async-lift]foo") (memory $memory) (realloc $realloc) string-encoding=utf8 async (callback $"[callback][async-lift]foo")))
  (export $"#func1 foo" (@name "foo") (;1;) "foo" (func $foo))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
