package foo:comments;

// hello
// world
// why, yes
// this is a comment
/* this too */ /* is a comment */
/* this /* is /* a */ nested */ comment */

/// doc comment for `foo`
/// second doc line
interface foo {
  type x = u32;

  type /* foo */ bar /* baz */ = //
  stream < //
  //
  //



  x

  >;

  /// doc comment for `docd`
  // this line comment must NOT appear in docs
  /* neither does this block */
  /** doc block for `docd`, continued */
  type docd = u32;

  //// four-slash lines are NOT doc comments
  type undocd = u32;

  /**/
  /***/
  type also-undocd = u32;
}

/// docs for bar interface
interface bar {
  /// docs for the-fn
  the-fn: func();
}
