// hello
// world
// why, yes
// this is a comment
/* this too */ /* is a comment */
/* this /* is /* a */ nested */ comment */

type x = u32

type /* foo */ bar /* baz */ = //
stream < //
//
//




x

>

