use { foo } from import-me
use { foo as bar } from import-me
use { x as import-me-x } from import-me

type x = foo
type y = bar
type z1 = import-me-x
type z2 = handle import-me-x

use { %handle } from import-me
resource xyz
type my-handle = handle xyz
type my-handle2 = xyz

use { some-record } from import-me
