interface foo {}
interface bar {}

world the-world {
  import foo: self.foo
  import bar: self.bar
  import baz: interface {
    foo: func()
  }
  export foo: self.foo
  export bar: self.bar
  export baz: interface {
    foo: func()
  }
}

default world a-different-world {
  import foo: self.foo
}
