interface shared {
  type foo = u32
}

interface i1 {
  use self.shared.{foo}

  a: func() -> foo
}

interface i2 {
  use self.shared.{foo}

  a: func() -> foo
}

world the-world {
  import i1: self.i1
  import i2: self.i2
}
