interface a1 { }
interface a2 { }
interface b1 { }
interface b2 { }
interface c { }
interface d { }

world my-world-a {
    import a: self.a1
    import b: self.b1
    export d: self.d
}

world my-world-b {
    import a: self.a2
    import b: self.b2
    export c: self.c
}

world union-my-world {
    include self.my-world-a with { a as a1, b as b1 }
    include self.my-world-b
}
