(module
  (import "env" "memory" (memory 1))
  (import "$root" "[backpressure-inc]" (func))
  (import "$root" "[backpressure-dec]" (func))
  (import "[export]$root" "[task-cancel]" (func))
  (import "[export]$root" "[task-return]foo" (func (param i32 i32)))
  (import "[export]foo:foo/bar" "[task-return]foo" (func (param i32 i32)))
  (import "$root" "[waitable-set-new]" (func (result i32)))
  (import "$root" "[waitable-set-wait]" (func (param i32 i32) (result i32)))
  (import "$root" "[waitable-set-poll]" (func (param i32 i32) (result i32)))
  (import "$root" "[waitable-set-drop]" (func (param i32)))
  (import "$root" "[waitable-join]" (func (param i32 i32)))
  (import "$root" "[thread-yield]" (func (result i32)))
  (import "$root" "[subtask-drop]" (func (param i32)))
  (import "$root" "[subtask-cancel]" (func (param i32) (result i32)))
  (import "$root" "[error-context-new-utf8]" (func (param i32 i32) (result i32)))
  (import "$root" "[error-context-new-utf16]" (func (param i32 i32) (result i32)))
  (import "$root" "[error-context-new-latin1+utf16]" (func (param i32 i32) (result i32)))
  (import "$root" "[error-context-debug-message-utf8]" (func (param i32 i32)))
  (import "$root" "[error-context-debug-message-utf16]" (func (param i32 i32)))
  (import "$root" "[error-context-debug-message-latin1+utf16]" (func (param i32 i32)))
  (import "$root" "[error-context-drop]" (func (param i32)))
  (import "$root" "[context-get-0]" (func (result i32)))
  (import "$root" "[context-set-0]" (func (param i32)))

  (import "$root" "[future-read-unit]" (func (param i32 i32) (result i32)))
  (import "$root" "[future-write-unit]" (func (param i32 i32) (result i32)))
  (import "$root" "[stream-read-unit]" (func (param i32 i32 i32) (result i32)))
  (import "$root" "[stream-write-unit]" (func (param i32 i32 i32) (result i32)))

  (import "$root" "[future-write-0]a" (func (param i32 i32) (result i32)))
  (import "$root" "[future-read-0]a" (func (param i32 i32) (result i32)))
  (import "$root" "[stream-write-0]b" (func (param i32 i32 i32) (result i32)))
  (import "$root" "[stream-read-0]b" (func (param i32 i32 i32) (result i32)))
  (import "$root" "[future-write-0]c" (func (param i32 i32) (result i32)))
  (import "$root" "[future-read-0]c" (func (param i32 i32) (result i32)))
  (import "$root" "[stream-write-0]d" (func (param i32 i32 i32) (result i32)))
  (import "$root" "[stream-read-0]d" (func (param i32 i32 i32) (result i32)))

  (func (export "[async-lift-stackful]foo") (param i32 i32) unreachable)
  (func (export "[async-lift-stackful]foo:foo/bar#foo") (param i32 i32) unreachable)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
)
