[package]
name = "artifacts"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
wit-component = { workspace = true }
wasmparser = { workspace = true }
anyhow = { workspace = true }
tempfile = { workspace = true }
wit-dylib = { workspace = true }
wit-parser = { workspace = true }
wasi-preview1-component-adapter-provider = "36.0.2"
wasm-compose = { workspace = true }

[build-dependencies]
cargo_metadata = "0.19.0"

[lints]
workspace = true

[lib]
test = false
doctest = false
