(component
  (type $ty-test:test/test (;0;)
    (instance
      (type (;0;) (func (param "v" s32) (result s32)))
      (export (;0;) "foo" (func (type 0)))
    )
  )
  (import "test:test/test" (instance $test:test/test (;0;) (type $ty-test:test/test)))
  (core module $main (;0;)
    (type (;0;) (func (param i32) (result i32)))
    (table (;0;) 2 funcref)
    (memory (;0;) 17)
    (global (;0;) i32 i32.const 1048592)
    (global (;1;) i32 i32.const 1)
    (global (;2;) i32 i32.const 1048592)
    (global (;3;) i32 i32.const 1)
    (export "bar:memory_base" (global 0))
    (export "bar:table_base" (global 1))
    (export "foo:memory_base" (global 2))
    (export "foo:table_base" (global 3))
    (export "foo" (func 0))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (func (;0;) (type 0) (param i32) (result i32)
      local.get 0
      i32.const 1
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $bar (;1;)
    (@dylink.0
      (mem-info (memory 0 4))
      (needed "foo")
    )
    (type (;0;) (func (param i32) (result i32)))
    (import "env" "foo" (func $import_foo (;0;) (type 0)))
    (export "bar" (func $bar))
    (export "foo" (func $bar))
    (func $bar (;1;) (type 0) (param i32) (result i32)
      unreachable
    )
  )
  (core module $foo (;2;)
    (@dylink.0
      (mem-info (memory 0 4))
      (needed "bar")
    )
    (type (;0;) (func (param i32) (result i32)))
    (import "test:test/test" "foo" (func $import_foo (;0;) (type 0)))
    (import "env" "foo" (func $import_foo2 (;1;) (type 0)))
    (import "env" "bar" (func $import_bar (;2;) (type 0)))
    (export "test:test/test#foo" (func $foo))
    (export "foo" (func $foo))
    (func $foo (;3;) (type 0) (param i32) (result i32)
      unreachable
    )
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (alias core export $main "foo" (core func $foo (;0;)))
  (core instance $env (;1;)
    (export "foo" (func $foo))
  )
  (core instance $bar (;2;) (instantiate $bar
      (with "env" (instance $env))
    )
  )
  (alias export $test:test/test "foo" (func $foo (;0;)))
  (core func $"#core-func1 foo" (@name "foo") (;1;) (canon lower (func $foo)))
  (core instance $test:test/test (;3;)
    (export "foo" (func $"#core-func1 foo"))
  )
  (alias core export $bar "foo" (core func $"#core-func2 foo" (@name "foo") (;2;)))
  (alias core export $bar "bar" (core func $bar (;3;)))
  (core instance $"#core-instance4 env" (@name "env") (;4;)
    (export "foo" (func $"#core-func2 foo"))
    (export "bar" (func $bar))
  )
  (core instance $foo (;5;) (instantiate $foo
      (with "test:test/test" (instance $test:test/test))
      (with "env" (instance $"#core-instance4 env"))
    )
  )
  (core module $wit-component-fixup (;3;)
    (type (;0;) (func))
    (type (;1;) (func (param i32) (result i32)))
    (import "main" "memory" (memory (;0;) 0))
    (import "main" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "bar" "foo" (func $foo (;0;) (type 1)))
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 1) func $foo)
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $fixup (;6;) (instantiate $wit-component-fixup
      (with "main" (instance $main))
      (with "bar" (instance $bar))
    )
  )
  (type (;1;) (func (param "v" s32) (result s32)))
  (alias core export $foo "test:test/test#foo" (core func $test:test/test#foo (;4;)))
  (func $"#func1 foo" (@name "foo") (;1;) (type 1) (canon lift (core func $test:test/test#foo)))
  (component $test:test/test-shim-component (;0;)
    (type (;0;) (func (param "v" s32) (result s32)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (param "v" s32) (result s32)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance $test:test/test-shim-instance (;1;) (instantiate $test:test/test-shim-component
      (with "import-func-foo" (func $"#func1 foo"))
    )
  )
  (export $"#instance2 test:test/test" (@name "test:test/test") (;2;) "test:test/test" (instance $test:test/test-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
