(component
  (type (;0;) (record))
  (type (;1;) (func (param "a" 0) (result 0)))
  (type (;2;)
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "foo" (type (eq 0)))
      (export "bar" (type (eq 0)))
      (alias outer 1 1 (type (;1;)))
      (export "baz" (func (type 1)))
    )
  )
  (import "foo" (instance (;0;) (type 2)))
  (core module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (import "foo" "baz" (func (;0;) (type 0)))
    (func (;1;) (type 1) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 1))
  )
  (alias export 0 "baz" (func (;0;)))
  (core func (;0;) (canon lower (func 0)))
  (core instance (;0;)
    (export "baz" (func 0))
  )
  (core instance (;1;) (instantiate 0
      (with "foo" (instance 0))
    )
  )
  (alias core export 1 "memory" (core memory (;0;)))
  (alias core export 1 "cabi_realloc" (core func (;1;)))
)