(component
  (type (;0;) (func))
  (type (;1;) (func (result string)))
  (type (;2;) (func (param "x" string) (result string)))
  (type (;3;) (list string))
  (type (;4;) (func (param "x" (type 3))))
  (module (;0;)
    (type (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func))
    (type (;3;) (func (result i32)))
    (type (;4;) (func (param i32 i32) (result i32)))
    (type (;5;) (func (param i32 i32)))
    (func $canonical_abi_realloc (;0;) (type 0) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func $canonical_abi_free (;1;) (type 1) (param i32 i32 i32)
      unreachable
    )
    (func (;2;) (type 2)
      unreachable
    )
    (func (;3;) (type 3) (result i32)
      unreachable
    )
    (func (;4;) (type 4) (param i32 i32) (result i32)
      unreachable
    )
    (func (;5;) (type 5) (param i32 i32)
      unreachable
    )
    (memory $memory (;0;) 1)
    (export "memory" (memory $memory))
    (export "canonical_abi_realloc" (func $canonical_abi_realloc))
    (export "canonical_abi_free" (func $canonical_abi_free))
    (export "a" (func 2))
    (export "b" (func 3))
    (export "c" (func 4))
    (export "d" (func 5))
  )
  (instance (;0;) (instantiate (module 0)))
  (alias export (instance 0) "a" (func (;0;)))
  (alias export (instance 0) "b" (func (;1;)))
  (alias export (instance 0) "c" (func (;2;)))
  (alias export (instance 0) "d" (func (;3;)))
  (func (;4;) (canon.lift (type 0) (func 0)))
  (func (;5;) (canon.lift (type 1) utf8 (into (instance 0)) (func 1)))
  (func (;6;) (canon.lift (type 2) utf8 (into (instance 0)) (func 2)))
  (func (;7;) (canon.lift (type 4) utf8 (into (instance 0)) (func 3)))
  (export "x" (type 3))
  (export "a" (func 4))
  (export "b" (func 5))
  (export "c" (func 6))
  (export "d" (func 7))
)