a1: function(x: u8)

a2: function(x: s8)

a3: function(x: u16)

a4: function(x: s16)

a5: function(x: u32)

a6: function(x: s32)

a7: function(x: u64)

a8: function(x: s64)

a9: function(p1: u8, p2: s8, p3: u16, p4: s16, p5: u32, p6: s32, p7: u64, p8: s64)

r1: function() -> u8

r2: function() -> s8

r3: function() -> u16

r4: function() -> s16

r5: function() -> u32

r6: function() -> s32

r7: function() -> u64

r8: function() -> s64

pair-ret: function() -> tuple<s64, u8>

multi-ret: function() -> tuple<s64, u8>

