(component
  (type (;0;) (func (result string)))
  (import "bar" (func $bar (;0;) (type 0)))
  (core module $main (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (import "env" "__wasm_get_tls_base" (func (;0;) (type 0)))
    (import "env" "__wasm_set_tls_base" (func (;1;) (type 1)))
    (import "$root" "bar" (func (;2;) (type 1)))
    (memory (;0;) 1)
    (export "cabi_realloc" (func 3))
    (export "memory" (memory 0))
    (func (;3;) (type 2) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (result i32)))
    (table (;0;) 1 1 funcref)
    (global (;0;) (mut i32) i32.const 0)
    (export "0" (func $indirect-$root-bar))
    (export "$imports" (table 0))
    (export "$get-tls-base" (func $$get-tls-base))
    (export "$set-tls-base" (func $$set-tls-base))
    (func $indirect-$root-bar (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (func $$get-tls-base (;1;) (type 1) (result i32)
      global.get 0
    )
    (func $$set-tls-base (;2;) (type 0) (param i32)
      local.get 0
      global.set 0
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias core export $wit-component-shim-instance "$get-tls-base" (core func $$get-tls-base (;0;)))
  (alias core export $wit-component-shim-instance "$set-tls-base" (core func $$set-tls-base (;1;)))
  (core instance $env (;1;)
    (export "__wasm_get_tls_base" (func $$get-tls-base))
    (export "__wasm_set_tls_base" (func $$set-tls-base))
  )
  (alias core export $wit-component-shim-instance "0" (core func $indirect-$root-bar (;2;)))
  (core instance $$root (;2;)
    (export "bar" (func $indirect-$root-bar))
  )
  (core instance $main (;3;) (instantiate $main
      (with "env" (instance $env))
      (with "$root" (instance $$root))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func (param i32)))
    (import "actual" "0" (func $0 (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func $0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (alias core export $main "cabi_realloc" (core func $cabi_realloc (;3;)))
  (core func $"#core-func4 indirect-$root-bar" (@name "indirect-$root-bar") (;4;) (canon lower (func $bar) (memory $memory) (realloc $cabi_realloc) string-encoding=utf8))
  (core instance $actual (;4;)
    (export "0" (func $"#core-func4 indirect-$root-bar"))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "actual" (instance $actual))
      (with "shim" (instance $wit-component-shim-instance))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
