(component
  (type (;0;) (func (param "x" u64) (param "y" string)))
  (type (;1;) 
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "a" (type 0))
    )
  )
  (type (;2;) (list u8))
  (type (;3;) (func (param "x" (type 2)) (result (type 2))))
  (type (;4;) 
    (instance
      (alias outer 1 3 (type (;0;)))
      (export "baz" (type 0))
    )
  )
  (type (;5;) (func))
  (type (;6;) 
    (instance
      (alias outer 1 5 (type (;0;)))
      (export "a" (type 0))
    )
  )
  (module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i64 i32 i32)))
    (type (;2;) (func (param i32 i32 i32)))
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (import "foo" "a" (func (;0;) (type 0)))
    (import "bar" "a" (func (;1;) (type 1)))
    (import "baz" "baz" (func (;2;) (type 2)))
    (func (;3;) (type 3) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;4;) (type 2) (param i32 i32 i32)
      unreachable
    )
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "canonical_abi_realloc" (func 3))
    (export "canonical_abi_free" (func 4))
  )
  (import "bar" (instance (;0;) (type 1)))
  (import "baz" (instance (;1;) (type 4)))
  (import "foo" (instance (;2;) (type 6)))
  (module (;1;)
    (type (;0;) (func (param i64 i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (func (;0;) (type 0) (param i64 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 0
      call_indirect (type 0)
    )
    (func (;1;) (type 1) (param i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 1
      call_indirect (type 1)
    )
    (table (;0;) 2 2 funcref)
    (export "0" (func 0))
    (export "1" (func 1))
    (export "$imports" (table 0))
  )
  (module (;2;)
    (type (;0;) (func (param i64 i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 1)))
    (import "" "$imports" (table (;0;) 2 2 funcref))
    (elem (;0;) (i32.const 0) func 0 1)
  )
  (instance (;3;) (instantiate (module 1)))
  (alias export (instance 3) "0" (func (;0;)))
  (alias export (instance 3) "1" (func (;1;)))
  (alias export (instance 2) "a" (func (;2;)))
  (func (;3;) (canon.lower (func 2)))
  (instance (;4;) core
    (export "a" (func 0))
  )
  (instance (;5;) core
    (export "baz" (func 1))
  )
  (instance (;6;) core
    (export "a" (func 3))
  )
  (instance (;7;) (instantiate (module 0)
      (with "bar" (instance 4))
      (with "baz" (instance 5))
      (with "foo" (instance 6))
    )
  )
  (alias export (instance 3) "$imports" (table (;0;)))
  (alias export (instance 0) "a" (func (;4;)))
  (alias export (instance 1) "baz" (func (;5;)))
  (func (;6;) (canon.lower utf8 (into (instance 7)) (func 4)))
  (func (;7;) (canon.lower (into (instance 7)) (func 5)))
  (instance (;8;) core
    (export "$imports" (table 0))
    (export "0" (func 6))
    (export "1" (func 7))
  )
  (instance (;9;) (instantiate (module 2)
      (with "" (instance 8))
    )
  )
)