(component
  (type $t0 (func))
  (type $t1 (func (param "x" s8)))
  (type $t2 (func (param "x" u8)))
  (type $t3 (func (param "x" s16)))
  (type $t4 (func (param "x" u16)))
  (type $t5 (func (param "x" s32)))
  (type $t6 (func (param "x" u32)))
  (type $t7 (func (param "x" s64)))
  (type $t8 (func (param "x" u64)))
  (type $t9 (func (param "x" float32)))
  (type $t10 (func (param "x" float64)))
  (type $t11 (func (param "x" bool)))
  (type $t12 (func (param "x" string)))
  (type $t13' (record (field "a" s8) (field "b" u8) (field "c" s16) (field "d" u16) (field "e" s32) (field "f" u32) (field "g" s64) (field "h" u64) (field "i" float32) (field "j" float64) (field "k" bool) (field "l" string)))
  (export $t13 "record1" (type $t13'))
  (type $t14 (func (param "x" $t13)))
  (type $t15 (list $t13))
  (type $t16 (func (param "x" $t15)))
  (type $t17 (tuple $t13 string))
  (type $t18 (func (param "x" $t17)))
  (type $t19' (flags "a" "b" "c"))
  (export $t19 "flags1" (type $t19'))
  (type $t20 (func (param "x" $t19)))
  (type $t21' (enum "a" "b" "c"))
  (export $t21 "enum1" (type $t21'))
  (type $t22 (func (param "x" $t21)))
  (type $t23' (option $t13))
  (export $t23 "option1" (type $t23'))
  (type $t24 (func (param "x" $t23)))
  (type $t25' (variant (case "a" s8) (case "b" u8) (case "c" s16) (case "d" u16) (case "e" s32) (case "f" u32) (case "g" s64) (case "h" u64) (case "i" float32) (case "j" float64) (case "k" bool) (case "l" string) (case "m" $t13)))
  (export $t25 "variant1" (type $t25'))
  (type $t26 (option $t25))
  (type $t27 (func (param "x" $t26)))
  (type $t28 (result $t13 (error string)))
  (type $t29 (func (result $t28)))
  (core module
    (func $a unreachable)
    (func $b (param i32) unreachable)
    (func $c (param i32) unreachable)
    (func $d (param i32) unreachable)
    (func $e (param i32) unreachable)
    (func $f (param i32) unreachable)
    (func $g (param i32) unreachable)
    (func $h (param i64) unreachable)
    (func $i (param i64) unreachable)
    (func $j (param f32) unreachable)
    (func $k (param f64) unreachable)
    (func $l (param i32) unreachable)
    (func $m (param i32 i32) unreachable)
    (func $n (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32) unreachable)
    (func $o (param i32 i32) unreachable)
    (func $p (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32 i32 i32) unreachable)
    (func $q (param i32) unreachable)
    (func $r (param i32) unreachable)
    (func $s (param i32 i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32) unreachable)
    (func $t (param i32 i32 i64 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32) unreachable)
    (func $u (result i32) unreachable)
    (func $canonical_abi_realloc (param i32 i32 i32 i32) (result i32) unreachable)
    (memory 0)
    (export "memory" (memory 0))
    (export "a" (func $a))
    (export "b" (func $b))
    (export "c" (func $c))
    (export "d" (func $d))
    (export "e" (func $e))
    (export "f" (func $f))
    (export "g" (func $g))
    (export "h" (func $h))
    (export "i" (func $i))
    (export "j" (func $j))
    (export "k" (func $k))
    (export "l" (func $l))
    (export "m" (func $m))
    (export "n" (func $n))
    (export "o" (func $o))
    (export "p" (func $p))
    (export "q" (func $q))
    (export "r" (func $r))
    (export "s" (func $s))
    (export "t" (func $t))
    (export "u" (func $u))
    (export "canonical_abi_realloc" (func $canonical_abi_realloc))
  )
  (core instance (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (alias core export 0 "canonical_abi_realloc" (core func (;0;)))
  (alias core export 0 "a" (core func (;1;)))
  (alias core export 0 "b" (core func (;2;)))
  (alias core export 0 "c" (core func (;3;)))
  (alias core export 0 "d" (core func (;4;)))
  (alias core export 0 "e" (core func (;5;)))
  (alias core export 0 "f" (core func (;6;)))
  (alias core export 0 "g" (core func (;7;)))
  (alias core export 0 "h" (core func (;8;)))
  (alias core export 0 "i" (core func (;9;)))
  (alias core export 0 "j" (core func (;10;)))
  (alias core export 0 "k" (core func (;11;)))
  (alias core export 0 "l" (core func (;12;)))
  (alias core export 0 "m" (core func (;13;)))
  (alias core export 0 "n" (core func (;14;)))
  (alias core export 0 "o" (core func (;15;)))
  (alias core export 0 "p" (core func (;16;)))
  (alias core export 0 "q" (core func (;17;)))
  (alias core export 0 "r" (core func (;18;)))
  (alias core export 0 "s" (core func (;19;)))
  (alias core export 0 "t" (core func (;20;)))
  (alias core export 0 "u" (core func (;21;)))
  (func (;0;) (type $t0) (canon lift (core func 1)))
  (func (;1;) (type $t1) (canon lift (core func 2)))
  (func (;2;) (type $t2) (canon lift (core func 3)))
  (func (;3;) (type $t3) (canon lift (core func 4)))
  (func (;4;) (type $t4) (canon lift (core func 5)))
  (func (;5;) (type $t5) (canon lift (core func 6)))
  (func (;6;) (type $t6) (canon lift (core func 7)))
  (func (;7;) (type $t7) (canon lift (core func 8)))
  (func (;8;) (type $t8) (canon lift (core func 9)))
  (func (;9;) (type $t9) (canon lift (core func 10)))
  (func (;10;) (type $t10) (canon lift (core func 11)))
  (func (;11;) (type $t11) (canon lift (core func 12)))
  (func (;12;) (type $t12) (canon lift (core func 13) (memory 0) (realloc 0) string-encoding=utf8))
  (func (;13;) (type $t14) (canon lift (core func 14) (memory 0) (realloc 0) string-encoding=utf8))
  (func (;14;) (type $t16) (canon lift (core func 15) (memory 0) (realloc 0) string-encoding=utf8))
  (func (;15;) (type $t18) (canon lift (core func 16) (memory 0) (realloc 0) string-encoding=utf8))
  (func (;16;) (type $t20) (canon lift (core func 17)))
  (func (;17;) (type $t22) (canon lift (core func 18)))
  (func (;18;) (type $t24) (canon lift (core func 19) (memory 0) (realloc 0) string-encoding=utf8))
  (func (;19;) (type $t27) (canon lift (core func 20) (memory 0) (realloc 0) string-encoding=utf8))
  (func (;20;) (type $t29) (canon lift (core func 21) (memory 0) (realloc 0) string-encoding=utf8))
  (export (;21;) "a" (func 0))
  (export (;22;) "b" (func 1))
  (export (;23;) "c" (func 2))
  (export (;24;) "d" (func 3))
  (export (;25;) "e" (func 4))
  (export (;26;) "f" (func 5))
  (export (;27;) "g" (func 6))
  (export (;28;) "h" (func 7))
  (export (;29;) "i" (func 8))
  (export (;30;) "j" (func 9))
  (export (;31;) "k" (func 10))
  (export (;32;) "l" (func 11))
  (export (;33;) "m" (func 12))
  (export (;34;) "n" (func 13))
  (export (;35;) "o" (func 14))
  (export (;36;) "p" (func 15))
  (export (;37;) "q" (func 16))
  (export (;38;) "r" (func 17))
  (export (;39;) "s" (func 18))
  (export (;40;) "t" (func 19))
  (export (;41;) "u" (func 20))
)
