;; This is just to show the WIT definition of component `a`.

a: func()
b: func(x: s8)
c: func(x: u8)
d: func(x: s16)
e: func(x: u16)
f: func(x: s32)
g: func(x: u32)
h: func(x: s64)
i: func(x: u64)
j: func(x: float32)
k: func(x: float64)
l: func(x: bool)
m: func(x: string)

record record1 {
    a: s8,
    b: u8,
    c: s16,
    d: u16,
    e: s32,
    f: u32,
    g: s64,
    h: u64,
    i: float32,
    j: float64,
    k: bool,
    l: string,
}

n: func(x: record1)

variant variant1 {
    a(s8),
    b(u8),
    c(s16),
    d(u16),
    e(s32),
    f(u32),
    g(s64),
    h(u64),
    i(float32),
    j(float64),
    k(bool),
    l(string),
    m(record1),
}

o: func(x: list<record1>)
p: func(x: tuple<record1, string>)

flags flags1 {
    a,
    b,
    c
}

q: func(x: flags1)

enum enum1 {
    a,
    b,
    c
}

r: func(x: enum1)

union union1 {
    s8,
    string,
    record1
}

s: func(x: union1)

t: func(x: option<variant1>)
u: func() -> expected<record1, string>
