(component
  (component (;0;)
    (type (;0;)
      (instance
        (type (;0;) (func (param "x" string) (result string)))
        (export (;0;) "m" (func (type 0)))
      )
    )
    (import "b1" (instance (;0;) (type 0)))
    (import "b2" (instance (;1;) (type 0)))
    (alias export 0 "m" (func (;0;)))
    (alias export 1 "m" (func (;1;)))
    (export (;2;) "m1" (func 0))
    (export (;3;) "m2" (func 1))
  )
  (component (;1;)
    (type $i1 (;0;)
      (instance
        (type (;0;) (func))
        (type (;1;) (func (param "x" s8)))
        (type (;2;) (func (param "x" u8)))
        (type (;3;) (func (param "x" s16)))
        (type (;4;) (func (param "x" u16)))
        (type (;5;) (func (param "x" s32)))
        (type (;6;) (func (param "x" u32)))
        (type (;7;) (func (param "x" s64)))
        (type (;8;) (func (param "x" u64)))
        (type (;9;) (func (param "x" float32)))
        (type (;10;) (func (param "x" float64)))
        (type (;11;) (func (param "x" bool)))
        (type (;12;) (func (param "x" string)))
        (export (;0;) "a" (func (type 0)))
        (export (;1;) "b" (func (type 1)))
        (export (;2;) "c" (func (type 2)))
        (export (;3;) "d" (func (type 3)))
        (export (;4;) "e" (func (type 4)))
        (export (;5;) "f" (func (type 5)))
        (export (;6;) "g" (func (type 6)))
        (export (;7;) "h" (func (type 7)))
        (export (;8;) "i" (func (type 8)))
        (export (;9;) "j" (func (type 9)))
        (export (;10;) "k" (func (type 10)))
        (export (;11;) "l" (func (type 11)))
        (export (;12;) "m" (func (type 12)))
        (type (;13;) (record (field "a" s8) (field "b" u8) (field "c" s16) (field "d" u16) (field "e" s32) (field "f" u32) (field "g" s64) (field "h" u64) (field "i" float32) (field "j" float64) (field "k" bool) (field "l" string)))
        (export (;14;) "record1" (type (eq 13)))
        (type (;15;) (func (param "x" 14)))
        (export (;13;) "n" (func (type 15)))
        (type (;16;) (list 14))
        (type (;17;) (func (param "x" 16)))
        (export (;14;) "o" (func (type 17)))
        (type (;18;) (tuple 14 string))
        (type (;19;) (func (param "x" 18)))
        (export (;15;) "p" (func (type 19)))
        (type (;20;) (flags "a" "b" "c"))
        (export (;21;) "flags1" (type (eq 20)))
        (type (;22;) (func (param "x" 21)))
        (export (;16;) "q" (func (type 22)))
        (type (;23;) (enum "a" "b" "c"))
        (export (;24;) "enum1" (type (eq 23)))
        (type (;25;) (func (param "x" 24)))
        (export (;17;) "r" (func (type 25)))
        (type (;26;) (option 14))
        (export (;27;) "option1" (type (eq 26)))
        (type (;28;) (func (param "x" 27)))
        (export (;18;) "s" (func (type 28)))
        (type (;29;) (variant (case "a" s8) (case "b" u8) (case "c" s16) (case "d" u16) (case "e" s32) (case "f" u32) (case "g" s64) (case "h" u64) (case "i" float32) (case "j" float64) (case "k" bool) (case "l" string) (case "m" 14)))
        (export (;30;) "variant1" (type (eq 29)))
        (type (;31;) (option 30))
        (type (;32;) (func (param "x" 31)))
        (export (;19;) "t" (func (type 32)))
        (type (;33;) (result 14 (error string)))
        (type (;34;) (func (result 33)))
        (export (;20;) "u" (func (type 34)))
      )
    )
    (type $f22 (;1;) (func (param "x" string) (result string)))
    (import "a" (instance $i1 (;0;) (type $i1)))
    (core module $m0 (;0;)
      (type (;0;) (func (param i32 i32)))
      (type (;1;) (func (param i32 i32) (result i32)))
      (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
      (import "a" "m" (func (;0;) (type 0)))
      (func $m (;1;) (type 1) (param i32 i32) (result i32)
        unreachable
      )
      (func $canonical_abi_realloc (;2;) (type 2) (param i32 i32 i32 i32) (result i32)
        unreachable
      )
      (memory (;0;) 0)
      (export "memory" (memory 0))
      (export "m" (func $m))
      (export "canonical_abi_realloc" (func $canonical_abi_realloc))
    )
    (core module $m1 (;1;)
      (type (;0;) (func (param i32 i32)))
      (type (;1;) (func (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;2;) (func (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32 i32 i32)))
      (type (;3;) (func (param i32 i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;4;) (func (param i32 i32 i64 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;5;) (func (param i32)))
      (func (;0;) (type 0) (param i32 i32)
        local.get 0
        local.get 1
        i32.const 0
        call_indirect (type 0)
      )
      (func (;1;) (type 1) (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)
        local.get 0
        local.get 1
        local.get 2
        local.get 3
        local.get 4
        local.get 5
        local.get 6
        local.get 7
        local.get 8
        local.get 9
        local.get 10
        local.get 11
        local.get 12
        i32.const 1
        call_indirect (type 1)
      )
      (func (;2;) (type 0) (param i32 i32)
        local.get 0
        local.get 1
        i32.const 2
        call_indirect (type 0)
      )
      (func (;3;) (type 2) (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32 i32 i32)
        local.get 0
        local.get 1
        local.get 2
        local.get 3
        local.get 4
        local.get 5
        local.get 6
        local.get 7
        local.get 8
        local.get 9
        local.get 10
        local.get 11
        local.get 12
        local.get 13
        local.get 14
        i32.const 3
        call_indirect (type 2)
      )
      (func (;4;) (type 3) (param i32 i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)
        local.get 0
        local.get 1
        local.get 2
        local.get 3
        local.get 4
        local.get 5
        local.get 6
        local.get 7
        local.get 8
        local.get 9
        local.get 10
        local.get 11
        local.get 12
        local.get 13
        i32.const 4
        call_indirect (type 3)
      )
      (func (;5;) (type 4) (param i32 i32 i64 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)
        local.get 0
        local.get 1
        local.get 2
        local.get 3
        local.get 4
        local.get 5
        local.get 6
        local.get 7
        local.get 8
        local.get 9
        local.get 10
        local.get 11
        local.get 12
        local.get 13
        local.get 14
        i32.const 5
        call_indirect (type 4)
      )
      (func (;6;) (type 5) (param i32)
        local.get 0
        i32.const 6
        call_indirect (type 5)
      )
      (table (;0;) 7 7 funcref)
      (export "0" (func 0))
      (export "1" (func 1))
      (export "2" (func 2))
      (export "3" (func 3))
      (export "4" (func 4))
      (export "5" (func 5))
      (export "6" (func 6))
      (export "$imports" (table 0))
    )
    (core module $m2 (;2;)
      (type (;0;) (func (param i32 i32)))
      (type (;1;) (func (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;2;) (func (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32 i32 i32)))
      (type (;3;) (func (param i32 i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;4;) (func (param i32 i32 i64 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;5;) (func (param i32)))
      (import "" "0" (func (;0;) (type 0)))
      (import "" "1" (func (;1;) (type 1)))
      (import "" "2" (func (;2;) (type 0)))
      (import "" "3" (func (;3;) (type 2)))
      (import "" "4" (func (;4;) (type 3)))
      (import "" "5" (func (;5;) (type 4)))
      (import "" "6" (func (;6;) (type 5)))
      (import "" "$imports" (table (;0;) 7 7 funcref))
      (elem (;0;) (i32.const 0) func 0 1 2 3 4 5 6)
    )
    (core instance $m1 (;0;) (instantiate $m1))
    (alias export $i1 "a" (func (;0;)))
    (core func $a (;0;) (canon lower (func 0)))
    (alias export $i1 "b" (func (;1;)))
    (core func $b (;1;) (canon lower (func 1)))
    (alias export $i1 "c" (func (;2;)))
    (core func $c (;2;) (canon lower (func 2)))
    (alias export $i1 "d" (func (;3;)))
    (core func $d (;3;) (canon lower (func 3)))
    (alias export $i1 "e" (func (;4;)))
    (core func $e (;4;) (canon lower (func 4)))
    (alias export $i1 "f" (func (;5;)))
    (core func $f (;5;) (canon lower (func 5)))
    (alias export $i1 "g" (func (;6;)))
    (core func $g (;6;) (canon lower (func 6)))
    (alias export $i1 "h" (func (;7;)))
    (core func $h (;7;) (canon lower (func 7)))
    (alias export $i1 "i" (func (;8;)))
    (core func $i (;8;) (canon lower (func 8)))
    (alias export $i1 "j" (func (;9;)))
    (core func $j (;9;) (canon lower (func 9)))
    (alias export $i1 "k" (func (;10;)))
    (core func $k (;10;) (canon lower (func 10)))
    (alias export $i1 "l" (func (;11;)))
    (core func $l (;11;) (canon lower (func 11)))
    (alias export $i1 "q" (func (;12;)))
    (core func $q (;12;) (canon lower (func 12)))
    (alias export $i1 "r" (func (;13;)))
    (core func $r (;13;) (canon lower (func 13)))
    (alias core export $m1 "0" (core func (;14;)))
    (alias core export $m1 "1" (core func (;15;)))
    (alias core export $m1 "2" (core func (;16;)))
    (alias core export $m1 "3" (core func (;17;)))
    (alias core export $m1 "4" (core func (;18;)))
    (alias core export $m1 "5" (core func (;19;)))
    (alias core export $m1 "6" (core func (;20;)))
    (core instance (;1;)
      (export "m" (func 14))
      (export "n" (func 15))
      (export "o" (func 16))
      (export "p" (func 17))
      (export "s" (func 18))
      (export "t" (func 19))
      (export "u" (func 20))
      (export "a" (func $a))
      (export "b" (func $b))
      (export "c" (func $c))
      (export "d" (func $d))
      (export "e" (func $e))
      (export "f" (func $f))
      (export "g" (func $g))
      (export "h" (func $h))
      (export "i" (func $i))
      (export "j" (func $j))
      (export "k" (func $k))
      (export "l" (func $l))
      (export "q" (func $q))
      (export "r" (func $r))
    )
    (core instance $m0 (;2;) (instantiate $m0
        (with "a" (instance 1))
      )
    )
    (alias core export $m0 "memory" (core memory $m (;0;)))
    (alias core export $m0 "canonical_abi_realloc" (core func $realloc (;21;)))
    (alias core export $m1 "$imports" (core table $t (;0;)))
    (alias export $i1 "m" (func (;14;)))
    (core func (;22;) (canon lower (func 14) (memory $m) (realloc $realloc) string-encoding=utf8))
    (alias export $i1 "n" (func (;15;)))
    (core func (;23;) (canon lower (func 15) (memory $m) (realloc $realloc) string-encoding=utf8))
    (alias export $i1 "o" (func (;16;)))
    (core func (;24;) (canon lower (func 16) (memory $m) (realloc $realloc) string-encoding=utf8))
    (alias export $i1 "p" (func (;17;)))
    (core func (;25;) (canon lower (func 17) (memory $m) (realloc $realloc) string-encoding=utf8))
    (alias export $i1 "s" (func (;18;)))
    (core func (;26;) (canon lower (func 18) (memory $m) (realloc $realloc) string-encoding=utf8))
    (alias export $i1 "t" (func (;19;)))
    (core func (;27;) (canon lower (func 19) (memory $m) (realloc $realloc) string-encoding=utf8))
    (alias export $i1 "u" (func (;20;)))
    (core func (;28;) (canon lower (func 20) (memory $m) (realloc $realloc) string-encoding=utf8))
    (core instance (;3;)
      (export "$imports" (table $t))
      (export "0" (func 22))
      (export "1" (func 23))
      (export "2" (func 24))
      (export "3" (func 25))
      (export "4" (func 26))
      (export "5" (func 27))
      (export "6" (func 28))
    )
    (core instance (;4;) (instantiate $m2
        (with "" (instance 3))
      )
    )
    (alias core export $m0 "m" (core func (;29;)))
    (func $m (;21;) (type $f22) (canon lift (core func 29) (memory $m) (realloc $realloc) string-encoding=utf8))
    (instance $x (;1;)
      (export "m" (func $m))
    )
    (export (;2;) "x" (instance $x))
  )
  (component (;2;)
    (type $t0 (;0;) (func))
    (type $t1 (;1;) (func (param "x" s8)))
    (type $t2 (;2;) (func (param "x" u8)))
    (type $t3 (;3;) (func (param "x" s16)))
    (type $t4 (;4;) (func (param "x" u16)))
    (type $t5 (;5;) (func (param "x" s32)))
    (type $t6 (;6;) (func (param "x" u32)))
    (type $t7 (;7;) (func (param "x" s64)))
    (type $t8 (;8;) (func (param "x" u64)))
    (type $t9 (;9;) (func (param "x" float32)))
    (type $t10 (;10;) (func (param "x" float64)))
    (type $t11 (;11;) (func (param "x" bool)))
    (type $t12 (;12;) (func (param "x" string)))
    (type $t13' (;13;) (record (field "a" s8) (field "b" u8) (field "c" s16) (field "d" u16) (field "e" s32) (field "f" u32) (field "g" s64) (field "h" u64) (field "i" float32) (field "j" float64) (field "k" bool) (field "l" string)))
    (export $t13 (;14;) "record1" (type $t13'))
    (type $t14 (;15;) (func (param "x" $t13)))
    (type $t15 (;16;) (list $t13))
    (type $t16 (;17;) (func (param "x" $t15)))
    (type $t17 (;18;) (tuple $t13 string))
    (type $t18 (;19;) (func (param "x" $t17)))
    (type $t19' (;20;) (flags "a" "b" "c"))
    (export $t19 (;21;) "flags1" (type $t19'))
    (type $t20 (;22;) (func (param "x" $t19)))
    (type $t21' (;23;) (enum "a" "b" "c"))
    (export $t21 (;24;) "enum1" (type $t21'))
    (type $t22 (;25;) (func (param "x" $t21)))
    (type $t23' (;26;) (option $t13))
    (export $t23 (;27;) "option1" (type $t23'))
    (type $t24 (;28;) (func (param "x" $t23)))
    (type $t25' (;29;) (variant (case "a" s8) (case "b" u8) (case "c" s16) (case "d" u16) (case "e" s32) (case "f" u32) (case "g" s64) (case "h" u64) (case "i" float32) (case "j" float64) (case "k" bool) (case "l" string) (case "m" $t13)))
    (export $t25 (;30;) "variant1" (type $t25'))
    (type $t26 (;31;) (option $t25))
    (type $t27 (;32;) (func (param "x" $t26)))
    (type $t28 (;33;) (result $t13 (error string)))
    (type $t29 (;34;) (func (result $t28)))
    (core module (;0;)
      (type (;0;) (func))
      (type (;1;) (func (param i32)))
      (type (;2;) (func (param i64)))
      (type (;3;) (func (param f32)))
      (type (;4;) (func (param f64)))
      (type (;5;) (func (param i32 i32)))
      (type (;6;) (func (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;7;) (func (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32 i32 i32)))
      (type (;8;) (func (param i32 i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;9;) (func (param i32 i32 i64 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)))
      (type (;10;) (func (result i32)))
      (type (;11;) (func (param i32 i32 i32 i32) (result i32)))
      (func $a (;0;) (type 0)
        unreachable
      )
      (func $b (;1;) (type 1) (param i32)
        unreachable
      )
      (func $c (;2;) (type 1) (param i32)
        unreachable
      )
      (func $d (;3;) (type 1) (param i32)
        unreachable
      )
      (func $e (;4;) (type 1) (param i32)
        unreachable
      )
      (func $f (;5;) (type 1) (param i32)
        unreachable
      )
      (func $g (;6;) (type 1) (param i32)
        unreachable
      )
      (func $h (;7;) (type 2) (param i64)
        unreachable
      )
      (func $i (;8;) (type 2) (param i64)
        unreachable
      )
      (func $j (;9;) (type 3) (param f32)
        unreachable
      )
      (func $k (;10;) (type 4) (param f64)
        unreachable
      )
      (func $l (;11;) (type 1) (param i32)
        unreachable
      )
      (func $m (;12;) (type 5) (param i32 i32)
        unreachable
      )
      (func $n (;13;) (type 6) (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)
        unreachable
      )
      (func $o (;14;) (type 5) (param i32 i32)
        unreachable
      )
      (func $p (;15;) (type 7) (param i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32 i32 i32)
        unreachable
      )
      (func $q (;16;) (type 1) (param i32)
        unreachable
      )
      (func $r (;17;) (type 1) (param i32)
        unreachable
      )
      (func $s (;18;) (type 8) (param i32 i32 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)
        unreachable
      )
      (func $t (;19;) (type 9) (param i32 i32 i64 i32 i32 i32 i32 i32 i64 i64 f32 f64 i32 i32 i32)
        unreachable
      )
      (func $u (;20;) (type 10) (result i32)
        unreachable
      )
      (func $canonical_abi_realloc (;21;) (type 11) (param i32 i32 i32 i32) (result i32)
        unreachable
      )
      (memory (;0;) 0)
      (export "memory" (memory 0))
      (export "a" (func $a))
      (export "b" (func $b))
      (export "c" (func $c))
      (export "d" (func $d))
      (export "e" (func $e))
      (export "f" (func $f))
      (export "g" (func $g))
      (export "h" (func $h))
      (export "i" (func $i))
      (export "j" (func $j))
      (export "k" (func $k))
      (export "l" (func $l))
      (export "m" (func $m))
      (export "n" (func $n))
      (export "o" (func $o))
      (export "p" (func $p))
      (export "q" (func $q))
      (export "r" (func $r))
      (export "s" (func $s))
      (export "t" (func $t))
      (export "u" (func $u))
      (export "canonical_abi_realloc" (func $canonical_abi_realloc))
    )
    (core instance (;0;) (instantiate 0))
    (alias core export 0 "memory" (core memory (;0;)))
    (alias core export 0 "canonical_abi_realloc" (core func (;0;)))
    (alias core export 0 "a" (core func (;1;)))
    (alias core export 0 "b" (core func (;2;)))
    (alias core export 0 "c" (core func (;3;)))
    (alias core export 0 "d" (core func (;4;)))
    (alias core export 0 "e" (core func (;5;)))
    (alias core export 0 "f" (core func (;6;)))
    (alias core export 0 "g" (core func (;7;)))
    (alias core export 0 "h" (core func (;8;)))
    (alias core export 0 "i" (core func (;9;)))
    (alias core export 0 "j" (core func (;10;)))
    (alias core export 0 "k" (core func (;11;)))
    (alias core export 0 "l" (core func (;12;)))
    (alias core export 0 "m" (core func (;13;)))
    (alias core export 0 "n" (core func (;14;)))
    (alias core export 0 "o" (core func (;15;)))
    (alias core export 0 "p" (core func (;16;)))
    (alias core export 0 "q" (core func (;17;)))
    (alias core export 0 "r" (core func (;18;)))
    (alias core export 0 "s" (core func (;19;)))
    (alias core export 0 "t" (core func (;20;)))
    (alias core export 0 "u" (core func (;21;)))
    (func (;0;) (type $t0) (canon lift (core func 1)))
    (func (;1;) (type $t1) (canon lift (core func 2)))
    (func (;2;) (type $t2) (canon lift (core func 3)))
    (func (;3;) (type $t3) (canon lift (core func 4)))
    (func (;4;) (type $t4) (canon lift (core func 5)))
    (func (;5;) (type $t5) (canon lift (core func 6)))
    (func (;6;) (type $t6) (canon lift (core func 7)))
    (func (;7;) (type $t7) (canon lift (core func 8)))
    (func (;8;) (type $t8) (canon lift (core func 9)))
    (func (;9;) (type $t9) (canon lift (core func 10)))
    (func (;10;) (type $t10) (canon lift (core func 11)))
    (func (;11;) (type $t11) (canon lift (core func 12)))
    (func (;12;) (type $t12) (canon lift (core func 13) (memory 0) (realloc 0) string-encoding=utf8))
    (func (;13;) (type $t14) (canon lift (core func 14) (memory 0) (realloc 0) string-encoding=utf8))
    (func (;14;) (type $t16) (canon lift (core func 15) (memory 0) (realloc 0) string-encoding=utf8))
    (func (;15;) (type $t18) (canon lift (core func 16) (memory 0) (realloc 0) string-encoding=utf8))
    (func (;16;) (type $t20) (canon lift (core func 17)))
    (func (;17;) (type $t22) (canon lift (core func 18)))
    (func (;18;) (type $t24) (canon lift (core func 19) (memory 0) (realloc 0) string-encoding=utf8))
    (func (;19;) (type $t27) (canon lift (core func 20) (memory 0) (realloc 0) string-encoding=utf8))
    (func (;20;) (type $t29) (canon lift (core func 21) (memory 0) (realloc 0) string-encoding=utf8))
    (export (;21;) "a" (func 0))
    (export (;22;) "b" (func 1))
    (export (;23;) "c" (func 2))
    (export (;24;) "d" (func 3))
    (export (;25;) "e" (func 4))
    (export (;26;) "f" (func 5))
    (export (;27;) "g" (func 6))
    (export (;28;) "h" (func 7))
    (export (;29;) "i" (func 8))
    (export (;30;) "j" (func 9))
    (export (;31;) "k" (func 10))
    (export (;32;) "l" (func 11))
    (export (;33;) "m" (func 12))
    (export (;34;) "n" (func 13))
    (export (;35;) "o" (func 14))
    (export (;36;) "p" (func 15))
    (export (;37;) "q" (func 16))
    (export (;38;) "r" (func 17))
    (export (;39;) "s" (func 18))
    (export (;40;) "t" (func 19))
    (export (;41;) "u" (func 20))
  )
  (instance (;0;) (instantiate 2))
  (instance (;1;) (instantiate 1
      (with "a" (instance 0))
    )
  )
  (instance (;2;) (instantiate 1
      (with "a" (instance 0))
    )
  )
  (alias export 2 "x" (instance (;3;)))
  (alias export 1 "x" (instance (;4;)))
  (instance (;5;) (instantiate 0
      (with "b1" (instance 3))
      (with "b2" (instance 4))
    )
  )
  (alias export 5 "m1" (func (;0;)))
  (export (;1;) "m1" (func 0))
  (alias export 5 "m2" (func (;2;)))
  (export (;3;) "m2" (func 2))
)
