(component
  (core module $main (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (memory (;0;) 1)
    (export "__wasm_init_task" (func 0))
    (export "__wasm_init_async_task" (func 1))
    (export "[async-lift-stackful]foo" (func 2))
    (export "bar" (func 3))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 4))
    (func (;0;) (type 0)
      unreachable
    )
    (func (;1;) (type 0)
      unreachable
    )
    (func (;2;) (type 0)
      unreachable
    )
    (func (;3;) (type 0)
      unreachable
    )
    (func (;4;) (type 1) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core module $init-task-wrappers (;1;)
    (type (;0;) (func))
    (type (;1;) (func))
    (import "" "__wasm_init_task" (func (;0;) (type 0)))
    (import "" "__wasm_init_async_task" (func (;1;) (type 0)))
    (import "" "import-func-foo" (func (;2;) (type 1)))
    (import "" "import-func-bar" (func (;3;) (type 1)))
    (export "[async-lift-stackful]foo" (func 3))
    (export "bar" (func 5))
    (func (;4;) (type 1)
      call 1
      call 2
    )
    (func (;5;) (type 1)
      call 0
      call 4
    )
  )
  (alias core export $main "__wasm_init_task" (core func $__wasm_init_task (;0;)))
  (alias core export $main "__wasm_init_async_task" (core func $__wasm_init_async_task (;1;)))
  (alias core export $main "[async-lift-stackful]foo" (core func $"[async-lift-stackful]foo" (;2;)))
  (alias core export $main "bar" (core func $bar (;3;)))
  (core instance $init-task-wrappers-args (;1;)
    (export "__wasm_init_task" (func $__wasm_init_task))
    (export "__wasm_init_async_task" (func $__wasm_init_async_task))
    (export "import-func-foo" (func $"[async-lift-stackful]foo"))
    (export "import-func-bar" (func $bar))
  )
  (core instance $init-task-wrappers-instance (;2;) (instantiate $init-task-wrappers
      (with "" (instance $init-task-wrappers-args))
    )
  )
  (alias core export $init-task-wrappers-instance "[async-lift-stackful]foo" (core func $"#core-func4 [async-lift-stackful]foo" (@name "[async-lift-stackful]foo") (;4;)))
  (alias core export $init-task-wrappers-instance "bar" (core func $"#core-func5 bar" (@name "bar") (;5;)))
  (type (;0;) (func))
  (alias core export $main "cabi_realloc" (core func $cabi_realloc (;6;)))
  (func $foo (;0;) (type 0) (canon lift (core func $"#core-func4 [async-lift-stackful]foo") async))
  (export $"#func1 foo" (@name "foo") (;1;) "foo" (func $foo))
  (func $bar (;2;) (type 0) (canon lift (core func $"#core-func5 bar")))
  (export $"#func3 bar" (@name "bar") (;3;) "bar" (func $bar))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)