(module
  (func (export "__wasm_task_hook") (param i32) unreachable)
  (func (export "[async-lift-stackful]async-stackful") unreachable)
  (func (export "[async-lift]async-callback") (result i32) unreachable)
  (func (export "[callback][async-lift]async-callback") (param i32 i32 i32) (result i32) unreachable)
  (func (export "sync") unreachable)
  (func (export "cabi_post_sync") unreachable)
  (func (export "_initialize"))
  (func (export "[async-lift-stackful]async-stackful-argret") (param i32 i32) unreachable)
  (func (export "[async-lift]async-callback-argret") (param i32 i32) (result i32) unreachable)
  (func (export "[callback][async-lift]async-callback-argret") (param i32 i32 i32) (result i32) unreachable)
  (func (export "sync-argret") (param i32 i32) (result i32) unreachable)
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
  (func (export "x#sync") unreachable)
  (func (export "x#[dtor]r") (param i32) unreachable)
)
