(component
  (type (;0;) (func))
  (import "foo" (relative-url "path/to/package" integrity "asdfkja;sldglj") (func (;0;) (type 0)))
  (type (;1;) (func))
  (import "bar" (url "path/to/package" integrity "asdlfkj") (func (;1;) (type 1)))
  (import "baz" integrity "asd;lfkj" (func (;2;) (type 1)))
  (type (;2;) (func))
  (import (locked-dep "moo:bar@1.0.0" integrity "asdlfkj") (func (;3;) (type 2)))
  (import (locked-dep "moo:bar" integrity "asdlfkj") (func (;3;) (type 2)))
  (type (;3;) (func))
  (import (unlocked-dep "goo:bar@{>=1.0.0 <3.0.0}") (func (;4;) (type 3)))
  (import (unlocked-dep "goo:bar@{<3.0.0}") (func (;4;) (type 3)))
  (import (unlocked-dep "goo:bar@{>=1.0.0}") (func (;4;) (type 3)))
  (import (unlocked-dep "goo:bar@*") (func (;4;) (type 3)))
  (import (unlocked-dep "goo:bar") (func (;4;) (type 3)))
)