(component
  (type (;0;)
    (instance
      (type (;0;) u8)
      (export "a" (type (eq 0)))
      (alias outer 0 0 (type (;1;)))
      (export "b" (type (eq 1)))
      (type (;2;) (func (param "a" 0) (result 1)))
      (export "f" (func (type 2)))
    )
  )
  (import "foo" (instance (;0;) (type 0)))
  (type (;1;)
    (instance
      (type (;0;) u8)
      (export "a" (type (eq 0)))
      (alias outer 0 0 (type (;1;)))
      (export "b" (type (eq 1)))
      (type (;2;) (func (param "a" 0) (result 1)))
      (export "f" (func (type 2)))
    )
  )
  (export "foo" (type 1))
)