(component
  (core module $main (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (result i32)))
    (type (;3;) (func (param i32)))
    (table (;0;) 1 funcref)
    (memory (;0;) 17)
    (global (;0;) i32 i32.const 1048592)
    (global (;1;) i32 i32.const 1)
    (global (;2;) i32 i32.const 1048608)
    (global (;3;) i32 i32.const 1)
    (export "c:memory_base" (global 0))
    (export "c:table_base" (global 1))
    (export "foo:memory_base" (global 2))
    (export "foo:table_base" (global 3))
    (export "c:__wasm_get_tls_base" (func 0))
    (export "c:__wasm_set_tls_base" (func 1))
    (export "foo:__wasm_get_tls_base" (func 2))
    (export "foo:__wasm_set_tls_base" (func 3))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (func (;0;) (type 0) (result i32)
      i32.const 1048584
      i32.load offset=4
    )
    (func (;1;) (type 1) (param i32)
      i32.const 1048584
      local.get 0
      i32.store offset=4
    )
    (func (;2;) (type 2) (result i32)
      i32.const 1048584
      i32.load
    )
    (func (;3;) (type 3) (param i32)
      i32.const 1048584
      local.get 0
      i32.store
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $c (;1;)
    (@dylink.0
      (mem-info (memory 16 4))
    )
    (type $void (;0;) (func))
    (type $get (;1;) (func (result i32)))
    (type $set (;2;) (func (param i32)))
    (type (;3;) (func (param i32) (result i32)))
    (import "env" "memory" (memory (;0;) 1))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "env" "__memory_base" (global $__memory_base (;0;) i32))
    (import "env" "__table_base" (global $__table_base (;1;) i32))
    (import "env" "__wasm_get_stack_pointer" (func $get_sp (;0;) (type $get)))
    (import "env" "__wasm_set_stack_pointer" (func $set_sp (;1;) (type $set)))
    (import "env" "__wasm_get_tls_base" (func $get_tls (;2;) (type $get)))
    (import "env" "__wasm_set_tls_base" (func $set_tls (;3;) (type $set)))
    (global (;2;) i32 i32.const 148)
    (global (;3;) i32 i32.const 4)
    (export "__tls_size" (global 2))
    (export "__tls_align" (global 3))
    (export "__wasm_init_tls" (func 4))
    (export "abort" (func $abort))
    (func (;4;) (type $set) (param i32)
      unreachable
    )
    (func $malloc (;5;) (type 3) (param i32) (result i32)
      unreachable
    )
    (func $abort (;6;) (type $void)
      unreachable
    )
  )
  (core module $foo (;2;)
    (@dylink.0
      (mem-info (memory 8 4))
      (needed "c")
    )
    (type $void (;0;) (func))
    (type $get (;1;) (func (result i32)))
    (type $set (;2;) (func (param i32)))
    (import "env" "memory" (memory (;0;) 1))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "env" "__memory_base" (global $__memory_base (;0;) i32))
    (import "env" "__table_base" (global $__table_base (;1;) i32))
    (import "env" "__wasm_get_tls_base" (func $get_tls (;0;) (type $get)))
    (import "env" "__wasm_set_tls_base" (func $set_tls (;1;) (type $set)))
    (import "env" "abort" (func $abort (;2;) (type $void)))
    (global (;2;) i32 i32.const 32)
    (global (;3;) i32 i32.const 16)
    (export "__tls_size" (global 2))
    (export "__tls_align" (global 3))
    (export "__wasm_init_tls" (func 3))
    (export "test:test/test#foo" (func $foo))
    (func (;3;) (type $set) (param i32)
      unreachable
    )
    (func $foo (;4;) (type $get) (result i32)
      call $get_tls
      i32.load
    )
  )
  (core module $__init (;3;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (import "env" "memory" (memory (;0;) 0))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (start 0)
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 1) func)
    (func (;0;) (type 0))
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (alias core export $main "__indirect_function_table" (core table $__indirect_function_table (;0;)))
  (alias core export $main "c:memory_base" (core global $c:memory_base (;0;)))
  (alias core export $main "c:table_base" (core global $c:table_base (;1;)))
  (core func $"context.get 0" (;0;) (canon context.get i32 0))
  (core func $"context.set 0" (;1;) (canon context.set i32 0))
  (alias core export $main "c:__wasm_get_tls_base" (core func $c:__wasm_get_tls_base (;2;)))
  (alias core export $main "c:__wasm_set_tls_base" (core func $c:__wasm_set_tls_base (;3;)))
  (core instance $env (;1;)
    (export "memory" (memory $memory))
    (export "__indirect_function_table" (table $__indirect_function_table))
    (export "__memory_base" (global $c:memory_base))
    (export "__table_base" (global $c:table_base))
    (export "__wasm_get_stack_pointer" (func $"context.get 0"))
    (export "__wasm_set_stack_pointer" (func $"context.set 0"))
    (export "__wasm_get_tls_base" (func $c:__wasm_get_tls_base))
    (export "__wasm_set_tls_base" (func $c:__wasm_set_tls_base))
  )
  (core instance $c (;2;) (instantiate $c
      (with "env" (instance $env))
    )
  )
  (alias core export $main "foo:memory_base" (core global $foo:memory_base (;2;)))
  (alias core export $main "foo:table_base" (core global $foo:table_base (;3;)))
  (alias core export $main "foo:__wasm_get_tls_base" (core func $foo:__wasm_get_tls_base (;4;)))
  (alias core export $main "foo:__wasm_set_tls_base" (core func $foo:__wasm_set_tls_base (;5;)))
  (alias core export $c "abort" (core func $abort (;6;)))
  (core instance $"#core-instance3 env" (@name "env") (;3;)
    (export "memory" (memory $memory))
    (export "__indirect_function_table" (table $__indirect_function_table))
    (export "__memory_base" (global $foo:memory_base))
    (export "__table_base" (global $foo:table_base))
    (export "__wasm_get_tls_base" (func $foo:__wasm_get_tls_base))
    (export "__wasm_set_tls_base" (func $foo:__wasm_set_tls_base))
    (export "abort" (func $abort))
  )
  (core instance $foo (;4;) (instantiate $foo
      (with "env" (instance $"#core-instance3 env"))
    )
  )
  (core instance $__init (;5;) (instantiate $__init
      (with "env" (instance $main))
    )
  )
  (type (;0;) (func (result s32)))
  (alias core export $foo "test:test/test#foo" (core func $test:test/test#foo (;7;)))
  (func $foo (;0;) (type 0) (canon lift (core func $test:test/test#foo)))
  (component $test:test/test-shim-component (;0;)
    (type (;0;) (func (result s32)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (result s32)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance $test:test/test-shim-instance (;0;) (instantiate $test:test/test-shim-component
      (with "import-func-foo" (func $foo))
    )
  )
  (export $test:test/test (;1;) "test:test/test" (instance $test:test/test-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
