(component
  (type (;0;) (func (param "x" u8)))
  (type (;1;) (func (param "x" s8)))
  (type (;2;) (func (param "x" u16)))
  (type (;3;) (func (param "x" s16)))
  (type (;4;) (func (param "x" u32)))
  (type (;5;) (func (param "x" s32)))
  (type (;6;) (func (param "x" u64)))
  (type (;7;) (func (param "x" s64)))
  (type (;8;) (func (param "p1" u8) (param "p2" s8) (param "p3" u16) (param "p4" s16) (param "p5" u32) (param "p6" s32) (param "p7" u64) (param "p8" s64)))
  (type (;9;) (func (result u8)))
  (type (;10;) (func (result s8)))
  (type (;11;) (func (result u16)))
  (type (;12;) (func (result s16)))
  (type (;13;) (func (result u32)))
  (type (;14;) (func (result s32)))
  (type (;15;) (func (result u64)))
  (type (;16;) (func (result s64)))
  (type (;17;) (tuple s64 u8))
  (type (;18;) (func (result 17)))
  (type (;19;) (func (result "a" s64) (result "b" u8)))
  (type (;20;)
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "a1" (func (type 0)))
      (alias outer 1 1 (type (;1;)))
      (export "a2" (func (type 1)))
      (alias outer 1 2 (type (;2;)))
      (export "a3" (func (type 2)))
      (alias outer 1 3 (type (;3;)))
      (export "a4" (func (type 3)))
      (alias outer 1 4 (type (;4;)))
      (export "a5" (func (type 4)))
      (alias outer 1 5 (type (;5;)))
      (export "a6" (func (type 5)))
      (alias outer 1 6 (type (;6;)))
      (export "a7" (func (type 6)))
      (alias outer 1 7 (type (;7;)))
      (export "a8" (func (type 7)))
      (alias outer 1 8 (type (;8;)))
      (export "a9" (func (type 8)))
      (alias outer 1 9 (type (;9;)))
      (export "r1" (func (type 9)))
      (alias outer 1 10 (type (;10;)))
      (export "r2" (func (type 10)))
      (alias outer 1 11 (type (;11;)))
      (export "r3" (func (type 11)))
      (alias outer 1 12 (type (;12;)))
      (export "r4" (func (type 12)))
      (alias outer 1 13 (type (;13;)))
      (export "r5" (func (type 13)))
      (alias outer 1 14 (type (;14;)))
      (export "r6" (func (type 14)))
      (alias outer 1 15 (type (;15;)))
      (export "r7" (func (type 15)))
      (alias outer 1 16 (type (;16;)))
      (export "r8" (func (type 16)))
      (alias outer 1 18 (type (;17;)))
      (export "pair-ret" (func (type 17)))
      (alias outer 1 19 (type (;18;)))
      (export "multi-ret" (func (type 18)))
    )
  )
  (import "integers" (instance (;0;) (type 20)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i64)))
    (type (;2;) (func (param i32 i32 i32 i32 i32 i32 i64 i64)))
    (type (;3;) (func (result i32)))
    (type (;4;) (func (result i64)))
    (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
    (import "integers" "a1" (func (;0;) (type 0)))
    (import "integers" "a2" (func (;1;) (type 0)))
    (import "integers" "a3" (func (;2;) (type 0)))
    (import "integers" "a4" (func (;3;) (type 0)))
    (import "integers" "a5" (func (;4;) (type 0)))
    (import "integers" "a6" (func (;5;) (type 0)))
    (import "integers" "a7" (func (;6;) (type 1)))
    (import "integers" "a8" (func (;7;) (type 1)))
    (import "integers" "a9" (func (;8;) (type 2)))
    (import "integers" "r1" (func (;9;) (type 3)))
    (import "integers" "r2" (func (;10;) (type 3)))
    (import "integers" "r3" (func (;11;) (type 3)))
    (import "integers" "r4" (func (;12;) (type 3)))
    (import "integers" "r5" (func (;13;) (type 3)))
    (import "integers" "r6" (func (;14;) (type 3)))
    (import "integers" "r7" (func (;15;) (type 4)))
    (import "integers" "r8" (func (;16;) (type 4)))
    (import "integers" "pair-ret" (func (;17;) (type 0)))
    (import "integers" "multi-ret" (func (;18;) (type 0)))
    (func (;19;) (type 5) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 19))
  )
  (core module (;1;)
    (type (;0;) (func (param i32)))
    (func $indirect-integers-pair-ret (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (func $indirect-integers-multi-ret (;1;) (type 0) (param i32)
      local.get 0
      i32.const 1
      call_indirect (type 0)
    )
    (table (;0;) 2 2 funcref)
    (export "0" (func $indirect-integers-pair-ret))
    (export "1" (func $indirect-integers-multi-ret))
    (export "$imports" (table 0))
  )
  (core module (;2;)
    (type (;0;) (func (param i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "$imports" (table (;0;) 2 2 funcref))
    (elem (;0;) (i32.const 0) func 0 1)
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (alias core export 0 "1" (core func (;1;)))
  (alias export 0 "a1" (func (;0;)))
  (core func (;2;) (canon lower (func 0)))
  (alias export 0 "a2" (func (;1;)))
  (core func (;3;) (canon lower (func 1)))
  (alias export 0 "a3" (func (;2;)))
  (core func (;4;) (canon lower (func 2)))
  (alias export 0 "a4" (func (;3;)))
  (core func (;5;) (canon lower (func 3)))
  (alias export 0 "a5" (func (;4;)))
  (core func (;6;) (canon lower (func 4)))
  (alias export 0 "a6" (func (;5;)))
  (core func (;7;) (canon lower (func 5)))
  (alias export 0 "a7" (func (;6;)))
  (core func (;8;) (canon lower (func 6)))
  (alias export 0 "a8" (func (;7;)))
  (core func (;9;) (canon lower (func 7)))
  (alias export 0 "a9" (func (;8;)))
  (core func (;10;) (canon lower (func 8)))
  (alias export 0 "r1" (func (;9;)))
  (core func (;11;) (canon lower (func 9)))
  (alias export 0 "r2" (func (;10;)))
  (core func (;12;) (canon lower (func 10)))
  (alias export 0 "r3" (func (;11;)))
  (core func (;13;) (canon lower (func 11)))
  (alias export 0 "r4" (func (;12;)))
  (core func (;14;) (canon lower (func 12)))
  (alias export 0 "r5" (func (;13;)))
  (core func (;15;) (canon lower (func 13)))
  (alias export 0 "r6" (func (;14;)))
  (core func (;16;) (canon lower (func 14)))
  (alias export 0 "r7" (func (;15;)))
  (core func (;17;) (canon lower (func 15)))
  (alias export 0 "r8" (func (;16;)))
  (core func (;18;) (canon lower (func 16)))
  (core instance (;1;)
    (export "pair-ret" (func 0))
    (export "multi-ret" (func 1))
    (export "a1" (func 2))
    (export "a2" (func 3))
    (export "a3" (func 4))
    (export "a4" (func 5))
    (export "a5" (func 6))
    (export "a6" (func 7))
    (export "a7" (func 8))
    (export "a8" (func 9))
    (export "a9" (func 10))
    (export "r1" (func 11))
    (export "r2" (func 12))
    (export "r3" (func 13))
    (export "r4" (func 14))
    (export "r5" (func 15))
    (export "r6" (func 16))
    (export "r7" (func 17))
    (export "r8" (func 18))
  )
  (core instance (;2;) (instantiate 0
      (with "integers" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 2 "cabi_realloc" (core func (;19;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "pair-ret" (func (;17;)))
  (core func (;20;) (canon lower (func 17) (memory 0)))
  (alias export 0 "multi-ret" (func (;18;)))
  (core func (;21;) (canon lower (func 18) (memory 0)))
  (core instance (;3;)
    (export "$imports" (table 0))
    (export "0" (func 20))
    (export "1" (func 21))
  )
  (core instance (;4;) (instantiate 2
      (with "" (instance 3))
    )
  )
)