(component
  (type (;0;) (func (param "x" u8)))
  (type (;1;) (func (param "x" s8)))
  (type (;2;) (func (param "x" u16)))
  (type (;3;) (func (param "x" s16)))
  (type (;4;) (func (param "x" u32)))
  (type (;5;) (func (param "x" s32)))
  (type (;6;) (func (param "x" u64)))
  (type (;7;) (func (param "x" s64)))
  (type (;8;) (func (param "p1" u8) (param "p2" s8) (param "p3" u16) (param "p4" s16) (param "p5" u32) (param "p6" s32) (param "p7" u64) (param "p8" s64)))
  (type (;9;) (func (result u8)))
  (type (;10;) (func (result s8)))
  (type (;11;) (func (result u16)))
  (type (;12;) (func (result s16)))
  (type (;13;) (func (result u32)))
  (type (;14;) (func (result s32)))
  (type (;15;) (func (result u64)))
  (type (;16;) (func (result s64)))
  (type (;17;) (tuple s64 u8))
  (type (;18;) (func (result 17)))
  (export "a1" (type 0))
  (export "a2" (type 1))
  (export "a3" (type 2))
  (export "a4" (type 3))
  (export "a5" (type 4))
  (export "a6" (type 5))
  (export "a7" (type 6))
  (export "a8" (type 7))
  (export "a9" (type 8))
  (export "r1" (type 9))
  (export "r2" (type 10))
  (export "r3" (type 11))
  (export "r4" (type 12))
  (export "r5" (type 13))
  (export "r6" (type 14))
  (export "r7" (type 15))
  (export "r8" (type 16))
  (export "pair-ret" (type 18))
  (export "multi-ret" (type 18))
)