[package]
name = "wit-parser-fuzz"
publish = false
edition.workspace = true
rust-version.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { workspace = true, features = ['derive'] }
env_logger = { workspace = true }
libfuzzer-sys = { workspace = true }
log = { workspace = true }
wasmprinter = { workspace = true }
wit-parser = { workspace = true }

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"
test = false
doc = false
