(component
  (type (;0;) (func))
  (type (;1;) (func (param "a" s8) (param "b" s16) (param "c" s32) (param "d" s64) (result string)))
  (type (;2;) (tuple s8 s16 s32 s64))
  (type (;3;) (func (result (type 2))))
  (type (;4;) (flags "a" "b" "c"))
  (type (;5;) (func (param "x" (type 4))))
  (type (;6;) (variant (case "a" unit) (case "b" string) (case "c" s64)))
  (type (;7;) (func (param "x" string) (result (type 6))))
  (type (;8;) (func (param "x" (type 6)) (result string)))
  (module (;0;)
    (type (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func))
    (type (;3;) (func (param i32 i32 i32 i64) (result i32)))
    (type (;4;) (func (result i32)))
    (type (;5;) (func (param i32 i32) (result i32)))
    (type (;6;) (func (param i32 i64 i32) (result i32)))
    (type (;7;) (func (param i32)))
    (func (;0;) (type 0) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;1;) (type 1) (param i32 i32 i32)
      unreachable
    )
    (func (;2;) (type 2)
      unreachable
    )
    (func (;3;) (type 3) (param i32 i32 i32 i64) (result i32)
      unreachable
    )
    (func (;4;) (type 4) (result i32)
      unreachable
    )
    (func (;5;) (type 2)
      unreachable
    )
    (func (;6;) (type 5) (param i32 i32) (result i32)
      unreachable
    )
    (func (;7;) (type 6) (param i32 i64 i32) (result i32)
      unreachable
    )
    (func (;8;) (type 7) (param i32)
      unreachable
    )
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "canonical_abi_realloc" (func 0))
    (export "canonical_abi_free" (func 1))
    (export "a" (func 2))
    (export "b" (func 3))
    (export "c" (func 4))
    (export "foo#a" (func 5))
    (export "foo#b" (func 6))
    (export "foo#c" (func 7))
    (export "bar#a" (func 8))
  )
  (instance (;0;) (instantiate (module 0)))
  (alias export (instance 0) "a" (func (;0;)))
  (alias export (instance 0) "b" (func (;1;)))
  (alias export (instance 0) "c" (func (;2;)))
  (func (;3;) (canon.lift (type 0) (func 0)))
  (func (;4;) (canon.lift (type 1) utf8 (into (instance 0)) (func 1)))
  (func (;5;) (canon.lift (type 3) (func 2)))
  (alias export (instance 0) "bar#a" (func (;6;)))
  (func (;7;) (canon.lift (type 5) (func 6)))
  (instance (;1;)
    (export "a" (func 7))
  )
  (alias export (instance 0) "foo#a" (func (;8;)))
  (alias export (instance 0) "foo#b" (func (;9;)))
  (alias export (instance 0) "foo#c" (func (;10;)))
  (func (;11;) (canon.lift (type 0) (func 8)))
  (func (;12;) (canon.lift (type 7) utf8 (into (instance 0)) (func 9)))
  (func (;13;) (canon.lift (type 8) utf8 (into (instance 0)) (func 10)))
  (instance (;2;)
    (export "a" (func 11))
    (export "b" (func 12))
    (export "c" (func 13))
  )
  (export "a" (func 3))
  (export "b" (func 4))
  (export "c" (func 5))
  (export "bar" (instance 1))
  (export "foo" (instance 2))
)