(module
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
  (func (export "a: func() -> ()") unreachable)
  (func (export "b: func(a: s8, b: s16, c: s32, d: s64) -> string") (param i32 i32 i32 i64) (result i32) unreachable)
  (func (export "c: func() -> tuple<s8, s16, s32, s64>") (result i32) unreachable)
  (func (export "foo#a: func() -> ()") unreachable)
  (func (export "foo#b: func(x: string) -> variant { a, b(string), c(s64) }") (param i32 i32) (result i32) unreachable)
  (func (export "foo#c: func(x: variant { a, b(string), c(s64) }) -> string") (param i32 i64 i32) (result i32) unreachable)
  (func (export "bar#a: func(x: flags { a, b, c }) -> ()") (param i32) unreachable)
)