(component
  (core module $main (;0;)
    (type (;0;) (func (result i64)))
    (type (;1;) (func (param i64)))
    (import "env" "__wasm_get_stack_pointer" (func (;0;) (type 0)))
    (import "env" "__wasm_set_stack_pointer" (func (;1;) (type 1)))
    (import "env" "__wasm_get_tls_base" (func (;2;) (type 0)))
    (import "env" "__wasm_set_tls_base" (func (;3;) (type 1)))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core func $"context.get 0" (;0;) (canon context.get i64 0))
  (core func $"context.set 0" (;1;) (canon context.set i64 0))
  (core func $"context.get 1" (;2;) (canon context.get i64 1))
  (core func $"context.set 1" (;3;) (canon context.set i64 1))
  (core instance $env (;0;)
    (export "__wasm_get_stack_pointer" (func $"context.get 0"))
    (export "__wasm_set_stack_pointer" (func $"context.set 0"))
    (export "__wasm_get_tls_base" (func $"context.get 1"))
    (export "__wasm_set_tls_base" (func $"context.set 1"))
  )
  (core instance $main (;1;) (instantiate $main
      (with "env" (instance $env))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
