(component
  (core module $main (;0;)
    (type (;0;) (func (result i64)))
    (type (;1;) (func (param i64)))
    (import "env" "__wasm_get_stack_pointer" (func (;0;) (type 0)))
    (import "env" "__wasm_set_stack_pointer" (func (;1;) (type 1)))
    (import "env" "__wasm_get_tls_base" (func (;2;) (type 0)))
    (import "env" "__wasm_set_tls_base" (func (;3;) (type 1)))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core func $"context.get 0" (;0;) (canon context.get i64 0))
  (core func $"context.set 0" (;1;) (canon context.set i64 0))
  (core module $wit-component:tls-base (;1;)
    (type (;0;) (func (result i64)))
    (type (;1;) (func (param i64)))
    (global (;0;) (mut i64) i64.const 0)
    (export "get" (func 0))
    (export "set" (func 1))
    (func (;0;) (type 0) (result i64)
      global.get 0
    )
    (func (;1;) (type 1) (param i64)
      local.get 0
      global.set 0
    )
  )
  (core instance $wit-component:tls-base (;0;) (instantiate $wit-component:tls-base))
  (alias core export $wit-component:tls-base "get" (core func $tls-base-get (;2;)))
  (alias core export $wit-component:tls-base "set" (core func $tls-base-set (;3;)))
  (core instance $env (;1;)
    (export "__wasm_get_stack_pointer" (func $"context.get 0"))
    (export "__wasm_set_stack_pointer" (func $"context.set 0"))
    (export "__wasm_get_tls_base" (func $tls-base-get))
    (export "__wasm_set_tls_base" (func $tls-base-set))
  )
  (core instance $main (;2;) (instantiate $main
      (with "env" (instance $env))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
