(component
  (core module (;0;)
    (type (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (func (;0;) (type 0) (param i32 i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      i32.const 1
      call_indirect (type 0)
    )
    (table (;0;) 2 funcref)
    (memory (;0;) 17)
    (global (;0;) (mut i32) i32.const 1048576)
    (global (;1;) i32 i32.const 1048592)
    (global (;2;) i32 i32.const 1)
    (global (;3;) (mut i32) i32.const 1048592)
    (global (;4;) (mut i32) i32.const 1114112)
    (export "__stack_pointer" (global 0))
    (export "foo:memory_base" (global 1))
    (export "foo:table_base" (global 2))
    (export "__heap_base" (global 3))
    (export "__heap_end" (global 4))
    (export "cabi_realloc" (func 0))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;1;)
    (@dylink.0
      (mem-info (memory 0 4))
    )
    (type (;0;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32)))
    (import "env" "cabi_realloc" (func $cabi_realloc.0 (;0;) (type 0)))
    (func $cabi_realloc.1 (;1;) (type 0) (param i32 i32 i32 i32) (result i32)
      i32.const -257976192
    )
    (func $foo (;2;) (type 2) (param i32 i32))
    (export "cabi_realloc" (func $cabi_realloc.1))
    (export "test:test/test#foo" (func $foo))
  )
  (core module (;2;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (import "env" "memory" (memory (;0;) 0))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "foo" "cabi_realloc" (func (;0;) (type 2)))
    (func (;1;) (type 0))
    (start 1)
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 1) func 0)
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 0))
  (alias core export 0 "memory" (core memory (;0;)))
  (alias core export 0 "cabi_realloc" (core func (;0;)))
  (alias core export 0 "__heap_base" (core global (;0;)))
  (alias core export 0 "__heap_end" (core global (;1;)))
  (core instance (;1;)
    (export "__heap_base" (global 0))
    (export "__heap_end" (global 1))
  )
  (core instance (;2;))
  (alias core export 0 "memory" (core memory (;1;)))
  (alias core export 0 "__indirect_function_table" (core table (;0;)))
  (alias core export 0 "__stack_pointer" (core global (;2;)))
  (alias core export 0 "foo:memory_base" (core global (;3;)))
  (alias core export 0 "foo:table_base" (core global (;4;)))
  (alias core export 0 "cabi_realloc" (core func (;1;)))
  (core instance (;3;)
    (export "memory" (memory 1))
    (export "__indirect_function_table" (table 0))
    (export "__stack_pointer" (global 2))
    (export "__memory_base" (global 3))
    (export "__table_base" (global 4))
    (export "cabi_realloc" (func 1))
  )
  (core instance (;4;) (instantiate 1
      (with "GOT.mem" (instance 1))
      (with "GOT.func" (instance 2))
      (with "env" (instance 3))
    )
  )
  (alias core export 4 "cabi_realloc" (core func (;2;)))
  (alias core export 4 "cabi_realloc" (core func (;3;)))
  (core instance (;5;) (instantiate 2
      (with "env" (instance 0))
      (with "foo" (instance 4))
    )
  )
  (type (;0;) (func (param "x" string)))
  (alias core export 4 "test:test/test#foo" (core func (;4;)))
  (func (;0;) (type 0) (canon lift (core func 4) (memory 0) (realloc 2) string-encoding=utf8))
  (component (;0;)
    (type (;0;) (func (param "x" string)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (param "x" string)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance (;0;) (instantiate 0
      (with "import-func-foo" (func 0))
    )
  )
  (export (;1;) "test:test/test" (instance 0))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
