(component
  (type (;0;) (func))
  (type (;1;)
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "foo" (func (type 0)))
    )
  )
  (import "foo" (instance (;0;) (type 1)))
  (core module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (import "foo" "foo" (func (;0;) (type 0)))
    (func (;1;) (type 0)
      unreachable
    )
    (func (;2;) (type 1) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "bar#bar" (func 1))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 2))
  )
  (alias export 0 "foo" (func (;0;)))
  (core func (;0;) (canon lower (func 0)))
  (core instance (;0;)
    (export "foo" (func 0))
  )
  (core instance (;1;) (instantiate 0
      (with "foo" (instance 0))
    )
  )
  (alias core export 1 "memory" (core memory (;0;)))
  (alias core export 1 "cabi_realloc" (core func (;1;)))
  (alias core export 1 "bar#bar" (core func (;2;)))
  (func (;1;) (type 0) (canon lift (core func 2)))
  (instance (;1;)
    (export "bar" (func 1))
  )
  (export "bar" (instance 1))
)