(component
  (core module $main (;0;)
    (table (;0;) 2 funcref)
    (memory (;0;) 17)
    (global (;0;) i32 i32.const 1048584)
    (global (;1;) i32 i32.const 2)
    (export "foo:memory_base" (global 0))
    (export "foo:table_base" (global 1))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $foo (;1;)
    (@dylink.0)
    (type (;0;) (func (param i32 i32) (result i32)))
    (type (;1;) (func))
    (import "$root" "[thread-new-indirect-v0]" (func (;0;) (type 0)))
    (export "hi" (func 1))
    (func (;1;) (type 1))
  )
  (core module $__init (;2;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (import "env" "memory" (memory (;0;) 0))
    (import "env" "__indirect_function_table" (table (;0;) 0 funcref))
    (start 0)
    (elem (;0;) (i32.const 1) func)
    (elem (;1;) (i32.const 2) func)
    (func (;0;) (type 0))
    (data (;0;) (i32.const 1048576) "\00\00\00\00\00\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $wit-component-shim-module (;3;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func $thread.new-indirect))
    (export "$imports" (table 0))
    (func $thread.new-indirect (;0;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (core instance $main (;1;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (alias core export $wit-component-shim-instance "0" (core func $thread.new-indirect (;0;)))
  (core instance $$root (;2;)
    (export "[thread-new-indirect-v0]" (func $thread.new-indirect))
  )
  (core instance $foo (;3;) (instantiate $foo
      (with "$root" (instance $$root))
    )
  )
  (core module $wit-component-fixup (;4;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (import "actual" "0" (func (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core type $thread-start (;0;) (func (param i32)))
  (alias core export $main "__indirect_function_table" (core table $indirect-function-table (;0;)))
  (core func $"#core-func1 thread.new-indirect" (@name "thread.new-indirect") (;1;) (canon thread.new-indirect $thread-start $indirect-function-table))
  (core instance $actual (;4;)
    (export "0" (func $"#core-func1 thread.new-indirect"))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "shim" (instance $wit-component-shim-instance))
      (with "actual" (instance $actual))
    )
  )
  (core instance $__init (;6;) (instantiate $__init
      (with "env" (instance $main))
    )
  )
  (type (;0;) (func))
  (alias core export $foo "hi" (core func $hi (;2;)))
  (func $hi (;0;) (type 0) (canon lift (core func $hi)))
  (export $"#func1 hi" (@name "hi") (;1;) "hi" (func $hi))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
