interface foo {
  use wasi.clocks.{timestamp}
  use wasi.filesystem.{stat}
}

world my-world {
  import wasi-fs: wasi.filesystem
  import wasi-clocks: wasi.clocks

  export saas: corp.saas
}

interface bar {
  use some-pkg.some-doc.{from-default}
  use some-pkg.some-doc.some-interface.{another-type}
  use some-pkg.some-doc.some-interface.{}
  use some-pkg.some-doc.another-interface.{yet-another-type}
  use different-pkg.the-doc.{}
}

world bars-world {
  import foo: some-pkg.some-doc
  import bar: another-pkg.other-doc.other-interface
}

interface use1 {
  use foreign-pkg.the-doc.{some-type}
}
interface use2 {
  use foreign-pkg.the-doc.{some-type}
}
