package root

interface foo {
  use wasi/clocks.{timestamp}
  use wasi/filesystem.{stat}
}

world my-world {
  import wasi/filesystem
  import wasi/clocks

  export corp/saas
}

use wasi/filesystem as filesystem
use wasi/clocks as clocks

world my-world2 {
  import filesystem
  import clocks
  export foo
  export corp/saas
}

interface bar {
  use filesystem.{}
  use some-pkg/the-default.{from-default}
  use some-pkg/some-interface.{another-type}
  use some-pkg/some-interface.{}
  use some-pkg/another-interface.{yet-another-type}
  use different-pkg/i.{}
}

world bars-world {
  import some-pkg/the-default
  import another-pkg/other-interface
}

interface use1 {
  use foreign-pkg/the-default.{some-type}
}
interface use2 {
  use foreign-pkg/the-default.{some-type}
}
