(component
  (type (;0;) (record))
  (type (;1;) (record (field "a" u32) (field "b" u32)))
  (type (;2;) (flags "a" "b" "c" "d" "e" "f" "g" "h" "i"))
  (type (;3;) (record (field "a" 1) (field "b" u32) (field "c" 0) (field "d" string) (field "e" 2)))
  (type (;4;) s32)
  (type (;5;) (tuple 4))
  (type (;6;) (tuple char u32))
  (type (;7;) (func (param "x" 6)))
  (type (;8;) (func (result 6)))
  (type (;9;) (func (param "x" 0)))
  (type (;10;) (func (result 0)))
  (type (;11;) (func (param "x" 1)))
  (type (;12;) (func (result 1)))
  (type (;13;) (func (param "x" 2)))
  (type (;14;) (func (result 2)))
  (type (;15;) (func (param "x" 3)))
  (type (;16;) (func (result 3)))
  (type (;17;) (func (param "e" 5) (result s32)))
  (type (;18;) 
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "empty"  (type (eq 0)))
      (alias outer 1 1 (type (;1;)))
      (export "scalars"  (type (eq 1)))
      (alias outer 1 2 (type (;2;)))
      (export "really-flags"  (type (eq 2)))
      (alias outer 1 3 (type (;3;)))
      (export "aggregates"  (type (eq 3)))
      (alias outer 1 4 (type (;4;)))
      (export "int-typedef"  (type (eq 4)))
      (alias outer 1 5 (type (;5;)))
      (export "tuple-typedef2"  (type (eq 5)))
      (alias outer 1 7 (type (;6;)))
      (export "tuple-arg" (func (type 6)))
      (alias outer 1 8 (type (;7;)))
      (export "tuple-result" (func (type 7)))
      (alias outer 1 9 (type (;8;)))
      (export "empty-arg" (func (type 8)))
      (alias outer 1 10 (type (;9;)))
      (export "empty-result" (func (type 9)))
      (alias outer 1 11 (type (;10;)))
      (export "scalar-arg" (func (type 10)))
      (alias outer 1 12 (type (;11;)))
      (export "scalar-result" (func (type 11)))
      (alias outer 1 13 (type (;12;)))
      (export "flags-arg" (func (type 12)))
      (alias outer 1 14 (type (;13;)))
      (export "flags-result" (func (type 13)))
      (alias outer 1 15 (type (;14;)))
      (export "aggregate-arg" (func (type 14)))
      (alias outer 1 16 (type (;15;)))
      (export "aggregate-result" (func (type 15)))
      (alias outer 1 17 (type (;16;)))
      (export "typedef-inout" (func (type 16)))
    )
  )
  (import "records" (instance (;0;) (type 18)))
  (core module (;0;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func))
    (type (;3;) (func (result i32)))
    (type (;4;) (func (param i32 i32 i32 i32 i32 i32)))
    (type (;5;) (func (param i32) (result i32)))
    (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
    (import "records" "tuple-arg" (func (;0;) (type 0)))
    (import "records" "tuple-result" (func (;1;) (type 1)))
    (import "records" "empty-arg" (func (;2;) (type 2)))
    (import "records" "empty-result" (func (;3;) (type 2)))
    (import "records" "scalar-arg" (func (;4;) (type 0)))
    (import "records" "scalar-result" (func (;5;) (type 1)))
    (import "records" "flags-arg" (func (;6;) (type 1)))
    (import "records" "flags-result" (func (;7;) (type 3)))
    (import "records" "aggregate-arg" (func (;8;) (type 4)))
    (import "records" "aggregate-result" (func (;9;) (type 1)))
    (import "records" "typedef-inout" (func (;10;) (type 5)))
    (func (;11;) (type 6) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 11))
  )
  (core module (;1;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32 i32 i32 i32 i32)))
    (func (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (func (;1;) (type 0) (param i32)
      local.get 0
      i32.const 1
      call_indirect (type 0)
    )
    (func (;2;) (type 1) (param i32 i32 i32 i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      local.get 4
      local.get 5
      i32.const 2
      call_indirect (type 1)
    )
    (func (;3;) (type 0) (param i32)
      local.get 0
      i32.const 3
      call_indirect (type 0)
    )
    (table (;0;) 4 4 funcref)
    (export "0" (func 0))
    (export "1" (func 1))
    (export "2" (func 2))
    (export "3" (func 3))
    (export "$imports" (table 0))
  )
  (core module (;2;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32 i32 i32 i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "2" (func (;2;) (type 1)))
    (import "" "3" (func (;3;) (type 0)))
    (import "" "$imports" (table (;0;) 4 4 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2 3)
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (alias core export 0 "1" (core func (;1;)))
  (alias core export 0 "2" (core func (;2;)))
  (alias core export 0 "3" (core func (;3;)))
  (alias export 0 "tuple-arg" (func (;0;)))
  (core func (;4;) (canon lower (func 0)))
  (alias export 0 "empty-arg" (func (;1;)))
  (core func (;5;) (canon lower (func 1)))
  (alias export 0 "empty-result" (func (;2;)))
  (core func (;6;) (canon lower (func 2)))
  (alias export 0 "scalar-arg" (func (;3;)))
  (core func (;7;) (canon lower (func 3)))
  (alias export 0 "flags-arg" (func (;4;)))
  (core func (;8;) (canon lower (func 4)))
  (alias export 0 "flags-result" (func (;5;)))
  (core func (;9;) (canon lower (func 5)))
  (alias export 0 "typedef-inout" (func (;6;)))
  (core func (;10;) (canon lower (func 6)))
  (core instance (;1;) 
    (export "tuple-result" (func 0))
    (export "scalar-result" (func 1))
    (export "aggregate-arg" (func 2))
    (export "aggregate-result" (func 3))
    (export "tuple-arg" (func 4))
    (export "empty-arg" (func 5))
    (export "empty-result" (func 6))
    (export "scalar-arg" (func 7))
    (export "flags-arg" (func 8))
    (export "flags-result" (func 9))
    (export "typedef-inout" (func 10))
  )
  (core instance (;2;) (instantiate 0
      (with "records" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 2 "cabi_realloc" (core func (;11;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "tuple-result" (func (;7;)))
  (core func (;12;) (canon lower (func 7) (memory 0)))
  (alias export 0 "scalar-result" (func (;8;)))
  (core func (;13;) (canon lower (func 8) (memory 0)))
  (alias export 0 "aggregate-arg" (func (;9;)))
  (core func (;14;) (canon lower (func 9) (memory 0) string-encoding=utf8))
  (alias export 0 "aggregate-result" (func (;10;)))
  (core func (;15;) (canon lower (func 10) (memory 0) (realloc 11) string-encoding=utf8))
  (core instance (;3;) 
    (export "$imports" (table 0))
    (export "0" (func 12))
    (export "1" (func 13))
    (export "2" (func 14))
    (export "3" (func 15))
  )
  (core instance (;4;) (instantiate 2
      (with "" (instance 3))
    )
  )
)