(component
  (type (;0;) (tuple char u32))
  (type (;1;) (func (param "x" (type 0))))
  (type (;2;) (func (result (type 0))))
  (type (;3;) (record))
  (type (;4;) (func (param "x" (type 3))))
  (type (;5;) (func (result (type 3))))
  (type (;6;) (record (field "a" u32) (field "b" u32)))
  (type (;7;) (func (param "x" (type 6))))
  (type (;8;) (func (result (type 6))))
  (type (;9;) (flags "a" "b" "c" "d" "e" "f" "g" "h" "i"))
  (type (;10;) (func (param "x" (type 9))))
  (type (;11;) (func (result (type 9))))
  (type (;12;) (record (field "a" (type 6)) (field "b" u32) (field "c" (type 3)) (field "d" string) (field "e" (type 9))))
  (type (;13;) (func (param "x" (type 12))))
  (type (;14;) (func (result (type 12))))
  (type (;15;) s32)
  (type (;16;) (tuple (type 15)))
  (type (;17;) (func (param "e" (type 16)) (result s32)))
  (export "tuple-arg" (type 1))
  (export "tuple-result" (type 2))
  (export "empty" (type 3))
  (export "empty-arg" (type 4))
  (export "empty-result" (type 5))
  (export "scalars" (type 6))
  (export "scalar-arg" (type 7))
  (export "scalar-result" (type 8))
  (export "really-flags" (type 9))
  (export "flags-arg" (type 10))
  (export "flags-result" (type 11))
  (export "aggregates" (type 12))
  (export "aggregate-arg" (type 13))
  (export "aggregate-result" (type 14))
  (export "int-typedef" (type 15))
  (export "tuple-typedef2" (type 16))
  (export "typedef-inout" (type 17))
)