(component
  (type $ty-a:b/c@0.1.1 (;0;)
    (instance
      (type (;0;) (func (param "x" string)))
      (export (;0;) "x" (func (type 0)))
      (type (;1;) (func))
      (export (;1;) "y" (func (type 1)))
    )
  )
  (import "a:b/c@0.1" (versionsuffix ".1") (instance $a:b/c@0.1 (;0;) (type $ty-a:b/c@0.1.1)))
  (core module $main (;0;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func))
    (type (;2;) (func (param i32 i32 i32 i32) (result i32)))
    (import "a:b/c@0.1.0" "x" (func (;0;) (type 0)))
    (import "a:b/c@0.1.0" "y" (func (;1;) (type 1)))
    (import "a:b/c@0.1.1" "x" (func (;2;) (type 0)))
    (import "a:b/c@0.1.1" "y" (func (;3;) (type 1)))
    (memory (;0;) 1)
    (export "a:b/c@0.1.0#x" (func 4))
    (export "cabi_realloc" (func 5))
    (export "memory" (memory 0))
    (func (;4;) (type 0) (param i32 i32)
      unreachable
    )
    (func (;5;) (type 2) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (param i32 i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func $indirect-a:b/c@0.1.0-x))
    (export "$imports" (table 0))
    (func $indirect-a:b/c@0.1.0-x (;0;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias core export $wit-component-shim-instance "0" (core func $indirect-a:b/c@0.1.0-x (;0;)))
  (alias export $a:b/c@0.1 "y" (func $y (;0;)))
  (core func $y (;1;) (canon lower (func $y)))
  (core instance $a:b/c@0.1.0 (;1;)
    (export "x" (func $indirect-a:b/c@0.1.0-x))
    (export "y" (func $y))
  )
  (alias export $a:b/c@0.1 "y" (func $"#func1 y" (@name "y") (;1;)))
  (core func $"#core-func2 y" (@name "y") (;2;) (canon lower (func $"#func1 y")))
  (core instance $a:b/c@0.1.1 (;2;)
    (export "x" (func $indirect-a:b/c@0.1.0-x))
    (export "y" (func $"#core-func2 y"))
  )
  (core instance $main (;3;) (instantiate $main
      (with "a:b/c@0.1.0" (instance $a:b/c@0.1.0))
      (with "a:b/c@0.1.1" (instance $a:b/c@0.1.1))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func (param i32 i32)))
    (import "actual" "0" (func $0 (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func $0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (alias export $a:b/c@0.1 "x" (func $x (;2;)))
  (core func $"#core-func3 indirect-a:b/c@0.1.0-x" (@name "indirect-a:b/c@0.1.0-x") (;3;) (canon lower (func $x) (memory $memory) string-encoding=utf8))
  (core instance $actual (;4;)
    (export "0" (func $"#core-func3 indirect-a:b/c@0.1.0-x"))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "actual" (instance $actual))
      (with "shim" (instance $wit-component-shim-instance))
    )
  )
  (type (;1;) (func (param "x" string)))
  (alias core export $main "a:b/c@0.1.0#x" (core func $a:b/c@0.1.0#x (;4;)))
  (alias core export $main "cabi_realloc" (core func $cabi_realloc (;5;)))
  (func $"#func3 x" (@name "x") (;3;) (type 1) (canon lift (core func $a:b/c@0.1.0#x) (memory $memory) (realloc $cabi_realloc) string-encoding=utf8))
  (component $a:b/c@0.1-shim-component (;0;)
    (type (;0;) (func (param "x" string)))
    (import "import-func-x" (func (;0;) (type 0)))
    (type (;1;) (func (param "x" string)))
    (export (;1;) "x" (func 0) (func (type 1)))
  )
  (instance $a:b/c@0.1-shim-instance (;1;) (instantiate $a:b/c@0.1-shim-component
      (with "import-func-x" (func $"#func3 x"))
    )
  )
  (export $"#instance2 a:b/c@0.1" (@name "a:b/c@0.1") (;2;) "a:b/c@0.1" (versionsuffix ".0") (instance $a:b/c@0.1-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
