interface other-name {
  record foo {
  }

}

interface name {
  use self.other-name.{foo}
  a: func(f: foo)
}

default world component {
  export other-name: self.other-name
  export name: self.name
}
