(component
  (type (;0;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (func (param "x" string) (result string)))
          (export "m" (func (type 0)))
        )
      )
      (import "b1" (instance (type 0)))
      (import "b2" (instance (type 0)))
      (type (;1;) (func (param "x" string) (result string)))
      (export "m1" (func (type 1)))
      (export "m2" (func (type 1)))
    )
  )
  (type (;1;)
    (component
      (type (;0;)
        (instance
          (type (;0;) (func))
          (export "a" (func (type 0)))
          (type (;1;) (func (param "x" s8)))
          (export "b" (func (type 1)))
          (type (;2;) (func (param "x" u8)))
          (export "c" (func (type 2)))
          (type (;3;) (func (param "x" s16)))
          (export "d" (func (type 3)))
          (type (;4;) (func (param "x" u16)))
          (export "e" (func (type 4)))
          (type (;5;) (func (param "x" s32)))
          (export "f" (func (type 5)))
          (type (;6;) (func (param "x" u32)))
          (export "g" (func (type 6)))
          (type (;7;) (func (param "x" s64)))
          (export "h" (func (type 7)))
          (type (;8;) (func (param "x" u64)))
          (export "i" (func (type 8)))
          (type (;9;) (func (param "x" float32)))
          (export "j" (func (type 9)))
          (type (;10;) (func (param "x" float64)))
          (export "k" (func (type 10)))
          (type (;11;) (func (param "x" bool)))
          (export "l" (func (type 11)))
          (type (;12;) (func (param "x" string)))
          (export "m" (func (type 12)))
          (type (;13;) (record (field "a" s8) (field "b" u8) (field "c" s16) (field "d" u16) (field "e" s32) (field "f" u32) (field "g" s64) (field "h" u64) (field "i" float32) (field "j" float64) (field "k" bool) (field "l" string)))
          (export "record1" (type (eq 13)))
          (type (;14;) (func (param "x" 13)))
          (export "n" (func (type 15)))
          (type (;15;) (list 13))
          (type (;16;) (func (param "x" 16)))
          (export "o" (func (type 17)))
          (type (;17;) (tuple 13 string))
          (type (;18;) (func (param "x" 18)))
          (export "p" (func (type 19)))
          (type (;19;) (flags "a" "b" "c"))
          (export "flags1" (type (eq 20)))
          (type (;20;) (func (param "x" 20)))
          (export "q" (func (type 22)))
          (type (;21;) (enum "a" "b" "c"))
          (export "enum1" (type (eq 23)))
          (type (;22;) (func (param "x" 23)))
          (export "r" (func (type 25)))
          (type (;23;) (union s8 string 13))
          (export "union1" (type (eq 26)))
          (type (;24;) (func (param "x" 26)))
          (export "s" (func (type 28)))
          (type (;25;) (variant (case "a" s8) (case "b" u8) (case "c" s16) (case "d" u16) (case "e" s32) (case "f" u32) (case "g" s64) (case "h" u64) (case "i" float32) (case "j" float64) (case "k" bool) (case "l" string) (case "m" 13)))
          (export "variant1" (type (eq 29)))
          (type (;26;) (option 29))
          (type (;27;) (func (param "x" 31)))
          (export "t" (func (type 32)))
          (type (;28;) (result 13 (error string)))
          (type (;29;) (func (result 33)))
          (export "u" (func (type 34)))
        )
      )
      (import "a" (instance (type 0)))
      (type (;1;)
        (instance
          (type (;0;) (func (param "x" string) (result string)))
          (export "m" (func (type 0)))
        )
      )
      (export "x" (instance (type 1)))
    )
  )
  (type (;2;)
    (component
      (type (;0;) (record (field "a" s8) (field "b" u8) (field "c" s16) (field "d" u16) (field "e" s32) (field "f" u32) (field "g" s64) (field "h" u64) (field "i" float32) (field "j" float64) (field "k" bool) (field "l" string)))
      (export "record1" (type (eq 0)))
      (type (;1;) (flags "a" "b" "c"))
      (export "flags1" (type (eq 2)))
      (type (;2;) (enum "a" "b" "c"))
      (export "enum1" (type (eq 4)))
      (type (;3;) (union s8 string 0))
      (export "union1" (type (eq 6)))
      (type (;4;) (variant (case "a" s8) (case "b" u8) (case "c" s16) (case "d" u16) (case "e" s32) (case "f" u32) (case "g" s64) (case "h" u64) (case "i" float32) (case "j" float64) (case "k" bool) (case "l" string) (case "m" 0)))
      (export "variant1" (type (eq 8)))
      (type (;5;) (func))
      (export "a" (func (type 10)))
      (type (;6;) (func (param "x" s8)))
      (export "b" (func (type 11)))
      (type (;7;) (func (param "x" u8)))
      (export "c" (func (type 12)))
      (type (;8;) (func (param "x" s16)))
      (export "d" (func (type 13)))
      (type (;9;) (func (param "x" u16)))
      (export "e" (func (type 14)))
      (type (;10;) (func (param "x" s32)))
      (export "f" (func (type 15)))
      (type (;11;) (func (param "x" u32)))
      (export "g" (func (type 16)))
      (type (;12;) (func (param "x" s64)))
      (export "h" (func (type 17)))
      (type (;13;) (func (param "x" u64)))
      (export "i" (func (type 18)))
      (type (;14;) (func (param "x" float32)))
      (export "j" (func (type 19)))
      (type (;15;) (func (param "x" float64)))
      (export "k" (func (type 20)))
      (type (;16;) (func (param "x" bool)))
      (export "l" (func (type 21)))
      (type (;17;) (func (param "x" string)))
      (export "m" (func (type 22)))
      (type (;18;) (func (param "x" 0)))
      (export "n" (func (type 23)))
      (type (;19;) (list 0))
      (type (;20;) (func (param "x" 24)))
      (export "o" (func (type 25)))
      (type (;21;) (tuple 0 string))
      (type (;22;) (func (param "x" 26)))
      (export "p" (func (type 27)))
      (type (;23;) (func (param "x" 2)))
      (export "q" (func (type 28)))
      (type (;24;) (func (param "x" 4)))
      (export "r" (func (type 29)))
      (type (;25;) (func (param "x" 6)))
      (export "s" (func (type 30)))
      (type (;26;) (option 8))
      (type (;27;) (func (param "x" 31)))
      (export "t" (func (type 32)))
      (type (;28;) (result 0 (error string)))
      (type (;29;) (func (result 33)))
      (export "u" (func (type 34)))
    )
  )
  (import "input" (component (;0;) (type 0)))
  (import "b" (component (;1;) (type 1)))
  (import "a" (component (;2;) (type 2)))
  (instance (;0;) (instantiate 2))
  (instance (;1;) (instantiate 1
      (with "a" (instance 0))
    )
  )
  (instance (;2;) (instantiate 1
      (with "a" (instance 0))
    )
  )
  (alias export 2 "x" (instance (;3;)))
  (alias export 1 "x" (instance (;4;)))
  (instance (;5;) (instantiate 0
      (with "b1" (instance 3))
      (with "b2" (instance 4))
    )
  )
  (alias export 5 "m1" (func (;0;)))
  (alias export 5 "m2" (func (;1;)))
  (export (;2;) "m1" (func 0))
  (export (;3;) "m2" (func 1))
)
