(component
  (core module (;0;)
    (type (;0;) (func (param i32) (result i32)))
    (func (;0;) (type 0) (param i32) (result i32)
      unreachable
    )
    (export "foo#c" (func 0))
  )
  (core instance (;0;) (instantiate 0))
  (type (;0;) u8)
  (type (;1;) (func (param "a" 0) (result 0)))
  (alias core export 0 "foo#c" (core func (;0;)))
  (func (;0;) (type 1) (canon lift (core func 0)))
  (component (;0;)
    (alias outer 1 1 (type (;0;)))
    (import "c" (func (;0;) (type 0)))
    (type (;1;) u8)
    (export (;2;) "a" (type 1))
    (export (;3;) "b" (type 2))
    (type (;4;) (func (param "a" 2) (result 3)))
    (export (;1;) "c" (func 0) (func (type 4)))
  )
  (instance (;0;) (instantiate 0
      (with "c" (func 0))
    )
  )
  (export (;1;) "foo" (instance 0))
)