(component
  (type (;0;)
    (instance
      (type (;0;) (record))
      (export (;1;) "r1" (type (eq 0)))
      (type (;2;) (record (field "x" 1)))
      (export (;3;) "r2" (type (eq 2)))
    )
  )
  (import (interface "foo:foo/name") (instance (;0;) (type 0)))
  (core module (;0;)
    (type (;0;) (func))
    (func (;0;) (type 0))
    (export "name#a" (func 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core instance (;0;) (instantiate 0))
  (component (;0;)
    (type (;0;) (record))
    (export (;1;) "r1" (type 0))
    (type (;2;) (record (field "x" 1)))
    (export (;3;) "r2" (type 2))
  )
  (instance (;1;) (instantiate 0))
  (export (;2;) (interface "foo:foo/name") (instance 1))
  (type (;1;) (func))
  (alias core export 0 "name#a" (core func (;0;)))
  (func (;0;) (type 1) (canon lift (core func 0)))
  (alias export 2 "r1" (type (;2;)))
  (alias export 2 "r2" (type (;3;)))
  (component (;1;)
    (type (;0;) (record))
    (import "import-type-r1" (type (;1;) (eq 0)))
    (type (;2;) (record (field "x" 1)))
    (import "import-type-r2" (type (;3;) (eq 2)))
    (type (;4;) (func))
    (import "import-func-a" (func (;0;) (type 4)))
    (type (;5;) (func))
    (export (;1;) "a" (func 0) (func (type 5)))
    (export (;6;) "r2" (type 3))
  )
  (instance (;3;) (instantiate 1
      (with "import-func-a" (func 0))
      (with "import-type-r1" (type 2))
      (with "import-type-r2" (type 3))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
  (export (;4;) "name" (instance 3))
)