(component
  (type $ty-test:test/test (;0;)
    (instance
      (type (;0;) (func (param "v" s32) (result s32)))
      (export (;0;) "foo" (func (type 0)))
    )
  )
  (import "test:test/test" (instance $test:test/test (;0;) (type $ty-test:test/test)))
  (core module $main (;0;)
    (table (;0;) 4 funcref)
    (memory (;0;) 17)
    (global (;0;) i32 i32.const 1048688)
    (global (;1;) i32 i32.const 4)
    (export "foo:memory_base" (global 0))
    (export "foo:table_base" (global 1))
    (export "__indirect_function_table" (table 0))
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module $foo (;1;)
    (@dylink.0
      (mem-info (memory 0 4))
    )
    (type (;0;) (func (param i32) (result i32)))
    (import "test:test/test" "foo" (func $import_foo (;0;) (type 0)))
    (global $what (;0;) i32 i32.const 42)
    (export "test:test/test#foo" (func $foo))
    (export "bar" (func $foo))
    (export "baz" (func $foo))
    (export "what" (global $what))
    (func $foo (;1;) (type 0) (param i32) (result i32)
      unreachable
    )
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "memory" (core memory $memory (;0;)))
  (alias export $test:test/test "foo" (func $foo (;0;)))
  (core func $foo (;0;) (canon lower (func $foo)))
  (core instance $test:test/test (;1;)
    (export "foo" (func $foo))
  )
  (core instance $foo (;2;) (instantiate $foo
      (with "test:test/test" (instance $test:test/test))
    )
  )
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func))
    (type (;1;) (func (param i32) (result i32)))
    (import "main" "memory" (memory (;0;) 0))
    (import "main" "__indirect_function_table" (table (;0;) 0 funcref))
    (import "main" "foo:memory_base" (global $foo:memory_base (;0;) i32))
    (import "foo" "what" (global $what (;1;) i32))
    (import "foo" "bar" (func $bar (;0;) (type 1)))
    (import "foo" "baz" (func $baz (;1;) (type 1)))
    (import "foo" "test:test/test#foo" (func $test:test/test#foo (;2;) (type 1)))
    (start $start)
    (elem (;0;) (i32.const 1) func $bar $baz $test:test/test#foo)
    (elem (;1;) (i32.const 4) func)
    (func $start (;3;) (type 0)
      i32.const 1048656
      global.get $foo:memory_base
      global.get $what
      i32.add
      i32.store
    )
    (data (;0;) (i32.const 1048576) "foo\00bar\00baz\00test:test/test#foo\00\00what\03\00\00\00\04\00\10\00\01\00\00\00\03\00\00\00\08\00\10\00\02\00\00\00\12\00\00\00\0c\00\10\00\03\00\00\00\04\00\00\00 \00\10\00\00\00\00\00\03\00\00\00\00\00\10\00\04\00\00\00$\00\10\00\01\00\00\00T\00\10\00")
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $fixup (;3;) (instantiate $wit-component-fixup
      (with "main" (instance $main))
      (with "foo" (instance $foo))
    )
  )
  (type (;1;) (func (param "v" s32) (result s32)))
  (alias core export $foo "test:test/test#foo" (core func $test:test/test#foo (;1;)))
  (func $"#func1 foo" (@name "foo") (;1;) (type 1) (canon lift (core func $test:test/test#foo)))
  (component $test:test/test-shim-component (;0;)
    (type (;0;) (func (param "v" s32) (result s32)))
    (import "import-func-foo" (func (;0;) (type 0)))
    (type (;1;) (func (param "v" s32) (result s32)))
    (export (;1;) "foo" (func 0) (func (type 1)))
  )
  (instance $test:test/test-shim-instance (;1;) (instantiate $test:test/test-shim-component
      (with "import-func-foo" (func $"#func1 foo"))
    )
  )
  (export $"#instance2 test:test/test" (@name "test:test/test") (;2;) "test:test/test" (instance $test:test/test-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
