(component
  (type (;0;) (record (field "s" string)))
  (type (;1;) (record (field "s" u32)))
  (type (;2;) (variant (case "s" string)))
  (type (;3;) (variant (case "s" u32)))
  (type (;4;) (func (param "x" 0)))
  (type (;5;) (func (param "x" 2)))
  (type (;6;) (func (param "x" 1)))
  (type (;7;) (func (param "x" 3)))
  (type (;8;)
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "r" (type (eq 0)))
      (alias outer 1 1 (type (;1;)))
      (export "r-no-string" (type (eq 1)))
      (alias outer 1 2 (type (;2;)))
      (export "v" (type (eq 2)))
      (alias outer 1 3 (type (;3;)))
      (export "v-no-string" (type (eq 3)))
      (alias outer 1 4 (type (;4;)))
      (export "a" (func (type 4)))
      (alias outer 1 5 (type (;5;)))
      (export "b" (func (type 5)))
      (alias outer 1 6 (type (;6;)))
      (export "c" (func (type 6)))
      (alias outer 1 7 (type (;7;)))
      (export "d" (func (type 7)))
    )
  )
  (import "foo" (instance (;0;) (type 8)))
  (core module (;0;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func (param i32)))
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (import "foo" "a" (func (;0;) (type 0)))
    (import "foo" "b" (func (;1;) (type 1)))
    (import "foo" "c" (func (;2;) (type 2)))
    (import "foo" "d" (func (;3;) (type 0)))
    (func (;4;) (type 3) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 4))
  )
  (core module (;1;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (func $indirect-foo-a (;0;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (func $indirect-foo-b (;1;) (type 1) (param i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 1
      call_indirect (type 1)
    )
    (table (;0;) 2 2 funcref)
    (export "0" (func $indirect-foo-a))
    (export "1" (func $indirect-foo-b))
    (export "$imports" (table 0))
  )
  (core module (;2;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 1)))
    (import "" "$imports" (table (;0;) 2 2 funcref))
    (elem (;0;) (i32.const 0) func 0 1)
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (alias core export 0 "1" (core func (;1;)))
  (alias export 0 "c" (func (;0;)))
  (core func (;2;) (canon lower (func 0)))
  (alias export 0 "d" (func (;1;)))
  (core func (;3;) (canon lower (func 1)))
  (core instance (;1;)
    (export "a" (func 0))
    (export "b" (func 1))
    (export "c" (func 2))
    (export "d" (func 3))
  )
  (core instance (;2;) (instantiate 0
      (with "foo" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 2 "cabi_realloc" (core func (;4;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "a" (func (;2;)))
  (core func (;5;) (canon lower (func 2) (memory 0) string-encoding=utf8))
  (alias export 0 "b" (func (;3;)))
  (core func (;6;) (canon lower (func 3) (memory 0) string-encoding=utf8))
  (core instance (;3;)
    (export "$imports" (table 0))
    (export "0" (func 5))
    (export "1" (func 6))
  )
  (core instance (;4;) (instantiate 2
      (with "" (instance 3))
    )
  )
)