(component
  (type (;0;)
    (instance
      (type (;0;) (record (field "s" string)))
      (export "r" (type (eq 0)))
      (type (;1;) (func (param "x" 0)))
      (export "a" (func (type 2)))
      (type (;2;) (variant (case "s" string)))
      (export "v" (type (eq 3)))
      (type (;3;) (func (param "x" 3)))
      (export "b" (func (type 5)))
      (type (;4;) (record (field "s" u32)))
      (export "r-no-string" (type (eq 6)))
      (type (;5;) (func (param "x" 6)))
      (export "c" (func (type 8)))
      (type (;6;) (variant (case "s" u32)))
      (export "v-no-string" (type (eq 9)))
      (type (;7;) (func (param "x" 9)))
      (export "d" (func (type 11)))
    )
  )
  (import "foo" (instance (;0;) (type 0)))
)