(component
  (type (;0;)
    (instance
      (type (;0;) (record (field "s" string)))
      (export (;1;) "r" (type (eq 0)))
      (type (;2;) (func (param "x" 0)))
      (export (;0;) "a" (func (type 2)))
      (type (;3;) (variant (case "s" string)))
      (export (;4;) "v" (type (eq 3)))
      (type (;5;) (func (param "x" 3)))
      (export (;1;) "b" (func (type 5)))
      (type (;6;) (record (field "s" u32)))
      (export (;7;) "r-no-string" (type (eq 6)))
      (type (;8;) (func (param "x" 6)))
      (export (;2;) "c" (func (type 8)))
      (type (;9;) (variant (case "s" u32)))
      (export (;10;) "v-no-string" (type (eq 9)))
      (type (;11;) (func (param "x" 9)))
      (export (;3;) "d" (func (type 11)))
    )
  )
  (import "foo" (instance (;0;) (type 0)))
)