(component
  (type (;0;) (record (field "s" string)))
  (type (;1;) (record (field "s" u32)))
  (type (;2;) (variant (case "s" string)))
  (type (;3;) (variant (case "s" u32)))
  (type (;4;) (func (param "x" 0)))
  (type (;5;) (func (param "x" 2)))
  (type (;6;) (func (param "x" 1)))
  (type (;7;) (func (param "x" 3)))
  (type (;8;)
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "r" (type (eq 0)))
      (alias outer 1 1 (type (;1;)))
      (export "r-no-string" (type (eq 1)))
      (alias outer 1 2 (type (;2;)))
      (export "v" (type (eq 2)))
      (alias outer 1 3 (type (;3;)))
      (export "v-no-string" (type (eq 3)))
      (alias outer 1 4 (type (;4;)))
      (export "a" (func (type 4)))
      (alias outer 1 5 (type (;5;)))
      (export "b" (func (type 5)))
      (alias outer 1 6 (type (;6;)))
      (export "c" (func (type 6)))
      (alias outer 1 7 (type (;7;)))
      (export "d" (func (type 7)))
    )
  )
  (import "foo" (instance (;0;) (type 8)))
)