(component
  (type (;0;)
    (instance
      (export (;0;) "r" (type (sub resource)))
      (type (;1;) (own 0))
      (type (;2;) (func (result 1)))
      (export (;0;) "[constructor]r" (func (type 2)))
      (type (;3;) (borrow 0))
      (type (;4;) (func (param "self" 3)))
      (export (;1;) "[method]r.x" (func (type 4)))
      (type (;5;) (func (param "x" string)))
      (export (;2;) "x" (func (type 5)))
      (type (;6;) (func))
      (export (;3;) "y" (func (type 6)))
    )
  )
  (import "a:b/c@0.1.1" (instance (;0;) (type 0)))
  (core module (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32)))
    (type (;3;) (func))
    (import "a:b/c@0.1.0" "[constructor]r" (func (;0;) (type 0)))
    (import "a:b/c@0.1.0" "[resource-drop]r" (func (;1;) (type 1)))
    (import "a:b/c@0.1.0" "x" (func (;2;) (type 2)))
    (import "a:b/c@0.1.1" "[constructor]r" (func (;3;) (type 0)))
    (import "a:b/c@0.1.1" "[resource-drop]r" (func (;4;) (type 1)))
    (import "a:b/c@0.1.1" "[method]r.x" (func (;5;) (type 1)))
    (import "a:b/c@0.1.1" "x" (func (;6;) (type 2)))
    (import "a:b/c@0.1.1" "y" (func (;7;) (type 3)))
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32 i32)))
    (table (;0;) 1 1 funcref)
    (export "1" (func $indirect-a:b/c@0.1.1-x))
    (export "$imports" (table 0))
    (func $indirect-a:b/c@0.1.1-x (;0;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32 i32)))
    (import "" "1" (func (;0;) (type 0)))
    (import "" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 1))
  (alias export 0 "[constructor]r" (func (;0;)))
  (core func (;0;) (canon lower (func 0)))
  (alias export 0 "r" (type (;1;)))
  (core func (;1;) (canon resource.drop 1))
  (alias core export 0 "1" (core func (;2;)))
  (core instance (;1;)
    (export "[constructor]r" (func 0))
    (export "[resource-drop]r" (func 1))
    (export "x" (func 2))
  )
  (alias export 0 "[constructor]r" (func (;1;)))
  (core func (;3;) (canon lower (func 1)))
  (alias export 0 "r" (type (;2;)))
  (core func (;4;) (canon resource.drop 2))
  (alias export 0 "[method]r.x" (func (;2;)))
  (core func (;5;) (canon lower (func 2)))
  (alias export 0 "y" (func (;3;)))
  (core func (;6;) (canon lower (func 3)))
  (core instance (;2;)
    (export "[constructor]r" (func 3))
    (export "[resource-drop]r" (func 4))
    (export "[method]r.x" (func 5))
    (export "x" (func 2))
    (export "y" (func 6))
  )
  (core instance (;3;) (instantiate 0
      (with "a:b/c@0.1.0" (instance 1))
      (with "a:b/c@0.1.1" (instance 2))
    )
  )
  (alias core export 3 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "x" (func (;4;)))
  (core func (;7;) (canon lower (func 4) (memory 0) string-encoding=utf8))
  (core instance (;4;)
    (export "$imports" (table 0))
    (export "1" (func 7))
  )
  (core instance (;5;) (instantiate 2
      (with "" (instance 4))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
