[package]
name = "wit-component-fuzz"
version = "0.0.1"
publish = false
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
arbitrary = { workspace = true, features = ['derive'] }
env_logger = { workspace = true }
libfuzzer-sys = { workspace = true }
log = { workspace = true }
test-helpers = { path = '../test-helpers' }
wasmprinter = { workspace = true }
wit-component = { workspace = true }
wit-parser = { workspace = true }

[[bin]]
name = "roundtrip-wit"
path = "fuzz_targets/roundtrip-wit.rs"
test = false
doc = false
