(component
  (type $ty-a (;0;)
    (instance
      (type (;0;) (func))
      (export (;0;) "f" (func (type 0)))
    )
  )
  (import "a" (instance $a (;0;) (type $ty-a)))
  (type $ty-b (;1;)
    (instance
      (type (;0;) (func))
      (export (;0;) "f" (func (type 0)))
    )
  )
  (import "b" (implements "a:b/i") (instance $b (;1;) (type $ty-b)))
  (type $ty-c (;2;)
    (instance
      (type (;0;) (func))
      (export (;0;) "f" (func (type 0)))
    )
  )
  (import "c" (implements "a:b/i") (instance $c (;2;) (type $ty-c)))
  (core module $main (;0;)
    (type (;0;) (func))
    (import "a" "f" (func (;0;) (type 0)))
    (import "b" "f" (func (;1;) (type 0)))
    (import "c" "f" (func (;2;) (type 0)))
    (export "a#f" (func 3))
    (export "b#f" (func 4))
    (export "c#f" (func 5))
    (func (;3;) (type 0))
    (func (;4;) (type 0))
    (func (;5;) (type 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (alias export $a "f" (func $f (;0;)))
  (core func $f (;0;) (canon lower (func $f)))
  (core instance $a (;0;)
    (export "f" (func $f))
  )
  (alias export $b "f" (func $"#func1 f" (@name "f") (;1;)))
  (core func $"#core-func1 f" (@name "f") (;1;) (canon lower (func $"#func1 f")))
  (core instance $b (;1;)
    (export "f" (func $"#core-func1 f"))
  )
  (alias export $c "f" (func $"#func2 f" (@name "f") (;2;)))
  (core func $"#core-func2 f" (@name "f") (;2;) (canon lower (func $"#func2 f")))
  (core instance $c (;2;)
    (export "f" (func $"#core-func2 f"))
  )
  (core instance $main (;3;) (instantiate $main
      (with "a" (instance $a))
      (with "b" (instance $b))
      (with "c" (instance $c))
    )
  )
  (type (;3;) (func))
  (alias core export $main "a#f" (core func $a#f (;3;)))
  (func $"#func3 f" (@name "f") (;3;) (type 3) (canon lift (core func $a#f)))
  (component $a-shim-component (;0;)
    (type (;0;) (func))
    (import "import-func-f" (func (;0;) (type 0)))
    (type (;1;) (func))
    (export (;1;) "f" (func 0) (func (type 1)))
  )
  (instance $a-shim-instance (;3;) (instantiate $a-shim-component
      (with "import-func-f" (func $"#func3 f"))
    )
  )
  (export $"#instance4 a" (@name "a") (;4;) "a" (instance $a-shim-instance))
  (alias core export $main "b#f" (core func $b#f (;4;)))
  (func $"#func4 f" (@name "f") (;4;) (type 3) (canon lift (core func $b#f)))
  (component $b-shim-component (;1;)
    (type (;0;) (func))
    (import "import-func-f" (func (;0;) (type 0)))
    (type (;1;) (func))
    (export (;1;) "f" (func 0) (func (type 1)))
  )
  (instance $b-shim-instance (;5;) (instantiate $b-shim-component
      (with "import-func-f" (func $"#func4 f"))
    )
  )
  (export $"#instance6 b" (@name "b") (;6;) "b" (implements "a:b/i") (instance $b-shim-instance))
  (alias core export $main "c#f" (core func $c#f (;5;)))
  (func $"#func5 f" (@name "f") (;5;) (type 3) (canon lift (core func $c#f)))
  (component $c-shim-component (;2;)
    (type (;0;) (func))
    (import "import-func-f" (func (;0;) (type 0)))
    (type (;1;) (func))
    (export (;1;) "f" (func 0) (func (type 1)))
  )
  (instance $c-shim-instance (;7;) (instantiate $c-shim-component
      (with "import-func-f" (func $"#func5 f"))
    )
  )
  (export $"#instance8 c" (@name "c") (;8;) "c" (implements "a:b/i") (instance $c-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
