(component
  (type (;0;) (func))
  (type (;1;) (list string))
  (type (;2;) (func (param "x" (type 1))))
  (type (;3;) (record (field "s" string)))
  (type (;4;) (func (param "x" (type 3))))
  (type (;5;) (variant (case "s" string)))
  (type (;6;) (func (param "x" (type 5))))
  (type (;7;) (record (field "s" u32)))
  (type (;8;) (func (param "x" (type 7))))
  (type (;9;) (variant (case "s" u32)))
  (type (;10;) (func (param "x" (type 9))))
  (type (;11;) (list (type 3)))
  (type (;12;) (func (param "x" (type 11))))
  (type (;13;) (list (type 5)))
  (type (;14;) (func (param "x" (type 13))))
  (type (;15;) (list u32))
  (type (;16;) (func (param "x" (type 15))))
  (type (;17;) (func (param "x" u32)))
  (type (;18;) (tuple u32 u32))
  (type (;19;) (func (result (type 18))))
  (type (;20;) (func (result string)))
  (type (;21;) (func (result (type 15))))
  (type (;22;) (func (result u32)))
  (type (;23;) (func (result (type 5))))
  (type (;24;) (list (type 9)))
  (type (;25;) (func (result (type 24))))
  (type (;26;) 
    (instance
      (alias outer 1 0 (type (;0;)))
      (export "a" (type 0))
      (alias outer 1 2 (type (;1;)))
      (export "b" (type 1))
      (alias outer 1 3 (type (;2;)))
      (export "r" (type 2))
      (alias outer 1 4 (type (;3;)))
      (export "c" (type 3))
      (alias outer 1 5 (type (;4;)))
      (export "v" (type 4))
      (alias outer 1 6 (type (;5;)))
      (export "d" (type 5))
      (alias outer 1 7 (type (;6;)))
      (export "r-no-string" (type 6))
      (alias outer 1 8 (type (;7;)))
      (export "e" (type 7))
      (alias outer 1 9 (type (;8;)))
      (export "v-no-string" (type 8))
      (alias outer 1 10 (type (;9;)))
      (export "f" (type 9))
      (alias outer 1 12 (type (;10;)))
      (export "g" (type 10))
      (alias outer 1 14 (type (;11;)))
      (export "h" (type 11))
      (alias outer 1 16 (type (;12;)))
      (export "i" (type 12))
      (alias outer 1 17 (type (;13;)))
      (export "j" (type 13))
      (alias outer 1 19 (type (;14;)))
      (export "k" (type 14))
      (alias outer 1 20 (type (;15;)))
      (export "l" (type 15))
      (alias outer 1 21 (type (;16;)))
      (export "m" (type 16))
      (alias outer 1 22 (type (;17;)))
      (export "n" (type 17))
      (alias outer 1 23 (type (;18;)))
      (export "o" (type 18))
      (alias outer 1 25 (type (;19;)))
      (export "p" (type 19))
    )
  )
  (module (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32 i32)))
    (type (;2;) (func (param i32 i32 i32)))
    (type (;3;) (func (param i32)))
    (type (;4;) (func (result i32)))
    (type (;5;) (func (param i32 i32 i32 i32) (result i32)))
    (import "foo" "a" (func (;0;) (type 0)))
    (import "foo" "b" (func (;1;) (type 1)))
    (import "foo" "c" (func (;2;) (type 1)))
    (import "foo" "d" (func (;3;) (type 2)))
    (import "foo" "e" (func (;4;) (type 3)))
    (import "foo" "f" (func (;5;) (type 1)))
    (import "foo" "g" (func (;6;) (type 1)))
    (import "foo" "h" (func (;7;) (type 1)))
    (import "foo" "i" (func (;8;) (type 1)))
    (import "foo" "j" (func (;9;) (type 3)))
    (import "foo" "k" (func (;10;) (type 3)))
    (import "foo" "l" (func (;11;) (type 3)))
    (import "foo" "m" (func (;12;) (type 3)))
    (import "foo" "n" (func (;13;) (type 4)))
    (import "foo" "o" (func (;14;) (type 3)))
    (import "foo" "p" (func (;15;) (type 3)))
    (func (;16;) (type 5) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (func (;17;) (type 2) (param i32 i32 i32)
      unreachable
    )
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "canonical_abi_realloc" (func 16))
    (export "canonical_abi_free" (func 17))
  )
  (import "foo" (instance (;0;) (type 26)))
  (module (;1;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func (param i32)))
    (func (;0;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (func (;1;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 1
      call_indirect (type 0)
    )
    (func (;2;) (type 1) (param i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 2
      call_indirect (type 1)
    )
    (func (;3;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 3
      call_indirect (type 0)
    )
    (func (;4;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 4
      call_indirect (type 0)
    )
    (func (;5;) (type 0) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 5
      call_indirect (type 0)
    )
    (func (;6;) (type 2) (param i32)
      local.get 0
      i32.const 6
      call_indirect (type 2)
    )
    (func (;7;) (type 2) (param i32)
      local.get 0
      i32.const 7
      call_indirect (type 2)
    )
    (func (;8;) (type 2) (param i32)
      local.get 0
      i32.const 8
      call_indirect (type 2)
    )
    (func (;9;) (type 2) (param i32)
      local.get 0
      i32.const 9
      call_indirect (type 2)
    )
    (func (;10;) (type 2) (param i32)
      local.get 0
      i32.const 10
      call_indirect (type 2)
    )
    (table (;0;) 11 11 funcref)
    (export "0" (func 0))
    (export "1" (func 1))
    (export "2" (func 2))
    (export "3" (func 3))
    (export "4" (func 4))
    (export "5" (func 5))
    (export "6" (func 6))
    (export "7" (func 7))
    (export "8" (func 8))
    (export "9" (func 9))
    (export "10" (func 10))
    (export "$imports" (table 0))
  )
  (module (;2;)
    (type (;0;) (func (param i32 i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func (param i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "2" (func (;2;) (type 1)))
    (import "" "3" (func (;3;) (type 0)))
    (import "" "4" (func (;4;) (type 0)))
    (import "" "5" (func (;5;) (type 0)))
    (import "" "6" (func (;6;) (type 2)))
    (import "" "7" (func (;7;) (type 2)))
    (import "" "8" (func (;8;) (type 2)))
    (import "" "9" (func (;9;) (type 2)))
    (import "" "10" (func (;10;) (type 2)))
    (import "" "$imports" (table (;0;) 11 11 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2 3 4 5 6 7 8 9 10)
  )
  (instance (;1;) (instantiate (module 1)))
  (alias export (instance 0) "a" (func (;0;)))
  (alias export (instance 1) "0" (func (;1;)))
  (alias export (instance 1) "1" (func (;2;)))
  (alias export (instance 1) "2" (func (;3;)))
  (alias export (instance 0) "e" (func (;4;)))
  (alias export (instance 0) "f" (func (;5;)))
  (alias export (instance 1) "3" (func (;6;)))
  (alias export (instance 1) "4" (func (;7;)))
  (alias export (instance 1) "5" (func (;8;)))
  (alias export (instance 0) "j" (func (;9;)))
  (alias export (instance 1) "6" (func (;10;)))
  (alias export (instance 1) "7" (func (;11;)))
  (alias export (instance 1) "8" (func (;12;)))
  (alias export (instance 0) "n" (func (;13;)))
  (alias export (instance 1) "9" (func (;14;)))
  (alias export (instance 1) "10" (func (;15;)))
  (func (;16;) (canon.lower (func 0)))
  (func (;17;) (canon.lower (func 4)))
  (func (;18;) (canon.lower (func 5)))
  (func (;19;) (canon.lower (func 9)))
  (func (;20;) (canon.lower (func 13)))
  (instance (;2;) core
    (export "a" (func 16))
    (export "b" (func 1))
    (export "c" (func 2))
    (export "d" (func 3))
    (export "e" (func 17))
    (export "f" (func 18))
    (export "g" (func 6))
    (export "h" (func 7))
    (export "i" (func 8))
    (export "j" (func 19))
    (export "k" (func 10))
    (export "l" (func 11))
    (export "m" (func 12))
    (export "n" (func 20))
    (export "o" (func 14))
    (export "p" (func 15))
  )
  (instance (;3;) (instantiate (module 0)
      (with "foo" (instance 2))
    )
  )
  (alias export (instance 1) "$imports" (table (;0;)))
  (alias export (instance 0) "b" (func (;21;)))
  (alias export (instance 0) "c" (func (;22;)))
  (alias export (instance 0) "d" (func (;23;)))
  (alias export (instance 0) "g" (func (;24;)))
  (alias export (instance 0) "h" (func (;25;)))
  (alias export (instance 0) "i" (func (;26;)))
  (alias export (instance 0) "k" (func (;27;)))
  (alias export (instance 0) "l" (func (;28;)))
  (alias export (instance 0) "m" (func (;29;)))
  (alias export (instance 0) "o" (func (;30;)))
  (alias export (instance 0) "p" (func (;31;)))
  (func (;32;) (canon.lower utf8 (into (instance 3)) (func 21)))
  (func (;33;) (canon.lower utf8 (into (instance 3)) (func 22)))
  (func (;34;) (canon.lower utf8 (into (instance 3)) (func 23)))
  (func (;35;) (canon.lower utf8 (into (instance 3)) (func 24)))
  (func (;36;) (canon.lower utf8 (into (instance 3)) (func 25)))
  (func (;37;) (canon.lower (into (instance 3)) (func 26)))
  (func (;38;) (canon.lower (into (instance 3)) (func 27)))
  (func (;39;) (canon.lower utf8 (into (instance 3)) (func 28)))
  (func (;40;) (canon.lower (into (instance 3)) (func 29)))
  (func (;41;) (canon.lower utf8 (into (instance 3)) (func 30)))
  (func (;42;) (canon.lower (into (instance 3)) (func 31)))
  (instance (;4;) core
    (export "$imports" (table 0))
    (export "0" (func 32))
    (export "1" (func 33))
    (export "2" (func 34))
    (export "3" (func 35))
    (export "4" (func 36))
    (export "5" (func 37))
    (export "6" (func 38))
    (export "7" (func 39))
    (export "8" (func 40))
    (export "9" (func 41))
    (export "10" (func 42))
  )
  (instance (;5;) (instantiate (module 2)
      (with "" (instance 4))
    )
  )
)