(module
  (import "foo" "a: func() -> ()" (func))
  (import "foo" "b: func(x: list<string>) -> ()" (func (param i32 i32)))
  (import "foo" "c: func(x: record { s: string }) -> ()" (func (param i32 i32)))
  (import "foo" "d: func(x: variant { s(string) }) -> ()" (func (param i32 i32 i32)))
  (import "foo" "e: func(x: record { s: u32 }) -> ()" (func (param i32)))
  (import "foo" "f: func(x: variant { s(u32) }) -> ()" (func (param i32 i32)))
  (import "foo" "g: func(x: list<record { s: string }>) -> ()" (func (param i32 i32)))
  (import "foo" "h: func(x: list<variant { s(string) }>) -> ()" (func (param i32 i32)))
  (import "foo" "i: func(x: list<u32>) -> ()" (func (param i32 i32)))
  (import "foo" "j: func(x: u32) -> ()" (func (param i32)))
  (import "foo" "k: func() -> tuple<u32, u32>" (func (param i32)))
  (import "foo" "l: func() -> string" (func (param i32)))
  (import "foo" "m: func() -> list<u32>" (func (param i32)))
  (import "foo" "n: func() -> u32" (func (result i32)))
  (import "foo" "o: func() -> variant { s(string) }" (func (param i32)))
  (import "foo" "p: func() -> list<variant { s(u32) }>" (func (param i32)))
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
)