(module
  (import "foo/foo" "a" (func))
  (import "foo/foo" "b" (func (param i32 i32)))
  (import "foo/foo" "c" (func (param i32 i32)))
  (import "foo/foo" "d" (func (param i32 i32 i32)))
  (import "foo/foo" "e" (func (param i32)))
  (import "foo/foo" "f" (func (param i32 i32)))
  (import "foo/foo" "g" (func (param i32 i32)))
  (import "foo/foo" "h" (func (param i32 i32)))
  (import "foo/foo" "i" (func (param i32 i32)))
  (import "foo/foo" "j" (func (param i32)))
  (import "foo/foo" "k" (func (param i32)))
  (import "foo/foo" "l" (func (param i32)))
  (import "foo/foo" "m" (func (param i32)))
  (import "foo/foo" "n" (func (result i32)))
  (import "foo/foo" "o" (func (param i32)))
  (import "foo/foo" "p" (func (param i32)))
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
)
