(component
  (core module $main (;0;)
    (type (;0;) (func))
    (export "the_entrypoint" (func 0))
    (export "x#y" (func 1))
    (func (;0;) (type 0))
    (func (;1;) (type 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component:adapter:old (;1;)
    (type (;0;) (func))
    (import "__main_module__" "the_entrypoint" (func $entry (;0;) (type 0)))
    (export "foo:foo/new#entrypoint" (func $entry))
  )
  (core instance $main (;0;) (instantiate $main))
  (alias core export $main "the_entrypoint" (core func $the_entrypoint (;0;)))
  (core instance $__main_module__ (;1;)
    (export "the_entrypoint" (func $the_entrypoint))
  )
  (core instance $old (;2;) (instantiate $wit-component:adapter:old
      (with "__main_module__" (instance $__main_module__))
    )
  )
  (type (;0;) (func))
  (alias core export $main "x#y" (core func $x#y (;1;)))
  (func $y (;0;) (type 0) (canon lift (core func $x#y)))
  (component $x-shim-component (;0;)
    (type (;0;) (func))
    (import "import-func-y" (func (;0;) (type 0)))
    (type (;1;) (func))
    (export (;1;) "y" (func 0) (func (type 1)))
  )
  (instance $x-shim-instance (;0;) (instantiate $x-shim-component
      (with "import-func-y" (func $y))
    )
  )
  (export $x (;1;) "x" (instance $x-shim-instance))
  (alias core export $old "foo:foo/new#entrypoint" (core func $foo:foo/new#entrypoint (;2;)))
  (func $entrypoint (;1;) (type 0) (canon lift (core func $foo:foo/new#entrypoint)))
  (component $foo:foo/new-shim-component (;1;)
    (type (;0;) (func))
    (import "import-func-entrypoint" (func (;0;) (type 0)))
    (type (;1;) (func))
    (export (;1;) "entrypoint" (func 0) (func (type 1)))
  )
  (instance $foo:foo/new-shim-instance (;2;) (instantiate $foo:foo/new-shim-component
      (with "import-func-entrypoint" (func $entrypoint))
    )
  )
  (export $foo:foo/new (;3;) "foo:foo/new" (instance $foo:foo/new-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
