(module
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
  (func (export "a: func() -> ()") unreachable)
  (func (export "b: func(x: list<string>) -> ()") (param i32 i32) unreachable)
  (func (export "c: func(x: record { s: string }) -> ()") (param i32 i32) unreachable)
  (func (export "d: func(x: variant { s(string) }) -> ()") (param i32 i32 i32) unreachable)
  (func (export "e: func(x: record { s: u32 }) -> ()") (param i32) unreachable)
  (func (export "f: func(x: variant { s(u32) }) -> ()") (param i32 i32) unreachable)
  (func (export "g: func(x: list<record { s: string }>) -> ()") (param i32 i32) unreachable)
  (func (export "h: func(x: list<variant { s(string) }>) -> ()") (param i32 i32) unreachable)
  (func (export "i: func(x: list<u32>) -> ()") (param i32 i32) unreachable)
  (func (export "j: func(x: u32) -> ()") (param i32) unreachable)
  (func (export "k: func() -> tuple<u32, u32>") (result i32) unreachable)
  (func (export "l: func() -> string") (result i32) unreachable)
  (func (export "m: func() -> list<u32>") (result i32) unreachable)
  (func (export "n: func() -> u32") (result i32) unreachable)
  (func (export "o: func() -> variant { s(string) }") (result i32) unreachable)
  (func (export "p: func() -> list<variant { s(u32) }>") (result i32) unreachable)
)