(module
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
  (func (export "foo#a") unreachable)
  (func (export "foo#b") (param i32 i32) unreachable)
  (func (export "foo#c") (param i32 i32) unreachable)
  (func (export "foo#d") (param i32 i32 i32) unreachable)
  (func (export "foo#e") (param i32) unreachable)
  (func (export "foo#f") (param i32 i32) unreachable)
  (func (export "foo#g") (param i32 i32) unreachable)
  (func (export "foo#h") (param i32 i32) unreachable)
  (func (export "foo#i") (param i32 i32) unreachable)
  (func (export "foo#j") (param i32) unreachable)
  (func (export "foo#k") (result i32) unreachable)
  (func (export "foo#l") (result i32) unreachable)
  (func (export "cabi_post_foo#l") (param i32) unreachable)
  (func (export "foo#m") (result i32) unreachable)
  (func (export "cabi_post_foo#m") (param i32) unreachable)
  (func (export "foo#n") (result i32) unreachable)
  (func (export "foo#o") (result i32) unreachable)
  (func (export "cabi_post_foo#o") (param i32) unreachable)
  (func (export "foo#p") (result i32) unreachable)
  (func (export "cabi_post_foo#p") (param i32) unreachable)
)
