(module
  (memory (export "memory") 1)
  (func (export "canonical_abi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
  (func (export "a") unreachable)
  (func (export "b") (param i32 i32) unreachable)
  (func (export "c") (param i32 i32) unreachable)
  (func (export "d") (param i32 i32 i32) unreachable)
  (func (export "e") (param i32) unreachable)
  (func (export "f") (param i32 i32) unreachable)
  (func (export "g") (param i32 i32) unreachable)
  (func (export "h") (param i32 i32) unreachable)
  (func (export "i") (param i32 i32) unreachable)
  (func (export "j") (param i32) unreachable)
  (func (export "k") (result i32) unreachable)
  (func (export "l") (result i32) unreachable)
  (func (export "m") (result i32) unreachable)
  (func (export "n") (result i32) unreachable)
  (func (export "o") (result i32) unreachable)
  (func (export "p") (result i32) unreachable)
)