(component
  (type (;0;)
    (instance
      (export (;0;) "a" (type (sub resource)))
      (type (;1;) (own 0))
      (type (;2;) (result 1 (error u32)))
      (type (;3;) (func (result 2)))
      (export (;0;) "[constructor]a" (func (type 3)))
    )
  )
  (import "foo" (instance (;0;) (type 0)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (import "foo" "[constructor]a" (func (;0;) (type 0)))
    (import "foo" "[resource-drop]a" (func (;1;) (type 0)))
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func $"indirect-foo-[constructor]a"))
    (export "$imports" (table 0))
    (func $"indirect-foo-[constructor]a" (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (alias export 0 "a" (type (;1;)))
  (core func (;1;) (canon resource.drop 1))
  (core instance (;1;)
    (export "[constructor]a" (func 0))
    (export "[resource-drop]a" (func 1))
  )
  (core instance (;2;) (instantiate 0
      (with "foo" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "[constructor]a" (func (;0;)))
  (core func (;2;) (canon lower (func 0) (memory 0)))
  (core instance (;3;)
    (export "$imports" (table 0))
    (export "0" (func 2))
  )
  (core instance (;4;) (instantiate 2
      (with "" (instance 3))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
