(component
  (core module $main (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32) (result i32)))
    (import "env" "__wasm_get_stack_pointer" (func (;0;) (type 0)))
    (import "env" "__wasm_set_stack_pointer" (func (;1;) (type 1)))
    (import "env" "__wasm_get_tls_base" (func (;2;) (type 0)))
    (import "env" "__wasm_set_tls_base" (func (;3;) (type 1)))
    (import "$root" "[thread-new-indirect-v0]" (func (;4;) (type 2)))
    (table (;0;) 1 funcref)
    (export "__indirect_function_table" (table 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func $thread.new-indirect))
    (export "$imports" (table 0))
    (func $thread.new-indirect (;0;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (core func $"context.get 0" (;0;) (canon context.get i32 0))
  (core func $"context.set 0" (;1;) (canon context.set i32 0))
  (core func $"context.get 1" (;2;) (canon context.get i32 1))
  (core func $"context.set 1" (;3;) (canon context.set i32 1))
  (core instance $env (;1;)
    (export "__wasm_get_stack_pointer" (func $"context.get 0"))
    (export "__wasm_set_stack_pointer" (func $"context.set 0"))
    (export "__wasm_get_tls_base" (func $"context.get 1"))
    (export "__wasm_set_tls_base" (func $"context.set 1"))
  )
  (alias core export $wit-component-shim-instance "0" (core func $thread.new-indirect (;4;)))
  (core instance $$root (;2;)
    (export "[thread-new-indirect-v0]" (func $thread.new-indirect))
  )
  (core instance $main (;3;) (instantiate $main
      (with "env" (instance $env))
      (with "$root" (instance $$root))
    )
  )
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (import "actual" "0" (func (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core type $thread-start (;0;) (func (param i32)))
  (alias core export $main "__indirect_function_table" (core table $indirect-function-table (;0;)))
  (core func $"#core-func5 thread.new-indirect" (@name "thread.new-indirect") (;5;) (canon thread.new-indirect $thread-start $indirect-function-table))
  (core instance $actual (;4;)
    (export "0" (func $"#core-func5 thread.new-indirect"))
  )
  (core instance $fixup (;5;) (instantiate $wit-component-fixup
      (with "shim" (instance $wit-component-shim-instance))
      (with "actual" (instance $actual))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
