(component
  (type (;0;) (func))
  (import "foo" (func $foo (;0;) (type 0)))
  (type (;1;) (func (result string)))
  (import "bar" (func $bar (;1;) (type 1)))
  (core module $main (;0;)
    (type (;0;) (func))
    (type (;1;) (func (param i32)))
    (type (;2;) (func (param i32 i32) (result i32)))
    (type (;3;) (func (param i32 i32 i32 i32) (result i32)))
    (import "$root" "foo" (func (;0;) (type 0)))
    (import "$root" "bar" (func (;1;) (type 1)))
    (memory (;0;) 1)
    (export "baz" (func 2))
    (export "foo2" (func 3))
    (export "cabi_post_foo2" (func 4))
    (export "cabi_realloc" (func 5))
    (export "memory" (memory 0))
    (func (;2;) (type 0))
    (func (;3;) (type 2) (param i32 i32) (result i32)
      unreachable
    )
    (func (;4;) (type 1) (param i32)
      unreachable
    )
    (func (;5;) (type 3) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (param i32)))
    (table (;0;) 1 1 funcref)
    (export "0" (func $indirect-$root-bar))
    (export "$imports" (table 0))
    (func $indirect-$root-bar (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (core func $foo (;0;) (canon lower (func $foo)))
  (alias core export $wit-component-shim-instance "0" (core func $indirect-$root-bar (;1;)))
  (core instance $$root (;1;)
    (export "foo" (func $foo))
    (export "bar" (func $indirect-$root-bar))
  )
  (core instance $main (;2;) (instantiate $main
      (with "$root" (instance $$root))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func (param i32)))
    (import "actual" "0" (func (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func 0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (alias core export $main "cabi_realloc" (core func $realloc (;2;)))
  (core func $"#core-func3 indirect-$root-bar" (@name "indirect-$root-bar") (;3;) (canon lower (func $bar) (memory $memory) (realloc $realloc) string-encoding=utf8))
  (core instance $actual (;3;)
    (export "0" (func $"#core-func3 indirect-$root-bar"))
  )
  (core instance $fixup (;4;) (instantiate $wit-component-fixup
      (with "shim" (instance $wit-component-shim-instance))
      (with "actual" (instance $actual))
    )
  )
  (alias core export $main "baz" (core func $baz (;4;)))
  (func $baz (;2;) (type 0) (canon lift (core func $baz)))
  (export $"#func3 baz" (@name "baz") (;3;) "baz" (func $baz))
  (type (;2;) (list u8))
  (type (;3;) (option 2))
  (type (;4;) (func (param "x" string) (result 3)))
  (alias core export $main "foo2" (core func $foo2 (;5;)))
  (alias core export $main "cabi_post_foo2" (core func $cabi_post_foo2 (;6;)))
  (func $foo2 (;4;) (type 4) (canon lift (core func $foo2) (memory $memory) (realloc $realloc) string-encoding=utf8 (post-return $cabi_post_foo2)))
  (export $"#func5 foo2" (@name "foo2") (;5;) "foo2" (func $foo2))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
