(component
  (type $ty-new (;0;)
    (instance
      (type (;0;) (func))
      (export (;0;) "thunk" (func (type 0)))
    )
  )
  (import "new" (instance $new (;0;) (type $ty-new)))
  (core module $main (;0;)
    (type (;0;) (func))
    (import "old" "thunk" (func (;0;) (type 0)))
    (memory (;0;) 65536 (pagesize 0x1))
    (export "memory" (memory 0))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component:adapter:old (;1;)
    (type (;0;) (func))
    (import "env" "memory" (memory (;0;) 0 (pagesize 0x1)))
    (import "new" "thunk" (func $thunk (;0;) (type 0)))
    (export "thunk" (func 1))
    (func (;1;) (type 0)
      i32.const 0
      i32.load
      drop
      call $thunk
    )
  )
  (core module $wit-component-shim-module (;2;)
    (type (;0;) (func))
    (table (;0;) 1 1 funcref)
    (export "0" (func $adapt-old-thunk))
    (export "$imports" (table 0))
    (func $adapt-old-thunk (;0;) (type 0)
      i32.const 0
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias core export $wit-component-shim-instance "0" (core func $adapt-old-thunk (;0;)))
  (core instance $old (;1;)
    (export "thunk" (func $adapt-old-thunk))
  )
  (core instance $main (;2;) (instantiate $main
      (with "old" (instance $old))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core instance $env (;3;)
    (export "memory" (memory $memory))
  )
  (alias export $new "thunk" (func $thunk (;0;)))
  (core func $thunk (;1;) (canon lower (func $thunk)))
  (core instance $new (;4;)
    (export "thunk" (func $thunk))
  )
  (core instance $"#core-instance5 old" (@name "old") (;5;) (instantiate $wit-component:adapter:old
      (with "env" (instance $env))
      (with "new" (instance $new))
    )
  )
  (core module $wit-component-fixup (;3;)
    (type (;0;) (func))
    (import "actual" "0" (func $0 (;0;) (type 0)))
    (import "shim" "$imports" (table (;0;) 1 1 funcref))
    (elem (;0;) (i32.const 0) func $0)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (alias core export $"#core-instance5 old" "thunk" (core func $"#core-func2 thunk" (@name "thunk") (;2;)))
  (core instance $actual (;6;)
    (export "0" (func $"#core-func2 thunk"))
  )
  (core instance $fixup (;7;) (instantiate $wit-component-fixup
      (with "actual" (instance $actual))
      (with "shim" (instance $wit-component-shim-instance))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
