(component
  (type (;0;)
    (instance
      (type (;0;) (enum "a"))
      (export (;1;) "e1" (type (eq 0)))
      (type (;2;) (func (param "x" 0)))
      (export (;0;) "e1-arg" (func (type 2)))
      (type (;3;) (func (result 0)))
      (export (;1;) "e1-result" (func (type 3)))
      (type (;4;) (union u32 float32))
      (export (;5;) "u1" (type (eq 4)))
      (type (;6;) (func (param "x" 4)))
      (export (;2;) "u1-arg" (func (type 6)))
      (type (;7;) (func (result 4)))
      (export (;3;) "u1-result" (func (type 7)))
      (type (;8;) (record))
      (export (;9;) "empty" (type (eq 8)))
      (type (;10;) (variant (case "a") (case "b" 4) (case "c" 0) (case "d" string) (case "e" 8) (case "f") (case "g" u32)))
      (export (;11;) "v1" (type (eq 10)))
      (type (;12;) (func (param "x" 10)))
      (export (;4;) "v1-arg" (func (type 12)))
      (type (;13;) (func (result 10)))
      (export (;5;) "v1-result" (func (type 13)))
      (type (;14;) (func (param "x" bool)))
      (export (;6;) "bool-arg" (func (type 14)))
      (type (;15;) (func (result bool)))
      (export (;7;) "bool-result" (func (type 15)))
      (type (;16;) (option bool))
      (type (;17;) (tuple))
      (type (;18;) (option 17))
      (type (;19;) (option u32))
      (type (;20;) (option 0))
      (type (;21;) (option float32))
      (type (;22;) (option 4))
      (type (;23;) (option 16))
      (type (;24;) (func (param "a" 16) (param "b" 18) (param "c" 19) (param "d" 20) (param "e" 21) (param "f" 22) (param "g" 23)))
      (export (;8;) "option-arg" (func (type 24)))
      (type (;25;) (tuple 16 18 19 20 21 22 23))
      (type (;26;) (func (result 25)))
      (export (;9;) "option-result" (func (type 26)))
      (type (;27;) (variant (case "a" s32) (case "b" float32)))
      (export (;28;) "casts1" (type (eq 27)))
      (type (;29;) (variant (case "a" float64) (case "b" float32)))
      (export (;30;) "casts2" (type (eq 29)))
      (type (;31;) (variant (case "a" float64) (case "b" u64)))
      (export (;32;) "casts3" (type (eq 31)))
      (type (;33;) (variant (case "a" u32) (case "b" s64)))
      (export (;34;) "casts4" (type (eq 33)))
      (type (;35;) (variant (case "a" float32) (case "b" s64)))
      (export (;36;) "casts5" (type (eq 35)))
      (type (;37;) (tuple float32 u32))
      (type (;38;) (tuple u32 u32))
      (type (;39;) (variant (case "a" 37) (case "b" 38)))
      (export (;40;) "casts6" (type (eq 39)))
      (type (;41;) (tuple 27 29 31 33 35 39))
      (type (;42;) (func (param "a" 27) (param "b" 29) (param "c" 31) (param "d" 33) (param "e" 35) (param "f" 39) (result 41)))
      (export (;10;) "casts" (func (type 42)))
      (type (;43;) (result))
      (type (;44;) (result (error 0)))
      (type (;45;) (result 0))
      (type (;46;) (result 17 (error 17)))
      (type (;47;) (result u32 (error 10)))
      (type (;48;) (list u8))
      (type (;49;) (result string (error 48)))
      (type (;50;) (func (param "a" 43) (param "b" 44) (param "c" 45) (param "d" 46) (param "e" 47) (param "f" 49)))
      (export (;11;) "expected-arg" (func (type 50)))
      (type (;51;) (tuple 43 44 45 46 47 49))
      (type (;52;) (func (result 51)))
      (export (;12;) "expected-result" (func (type 52)))
      (type (;53;) (enum "bad1" "bad2"))
      (export (;54;) "my-errno" (type (eq 53)))
      (type (;55;) (result s32 (error 53)))
      (type (;56;) (func (result 55)))
      (export (;13;) "return-expected-sugar" (func (type 56)))
      (type (;57;) (result (error 53)))
      (type (;58;) (func (result 57)))
      (export (;14;) "return-expected-sugar2" (func (type 58)))
      (type (;59;) (result 53 (error 53)))
      (type (;60;) (func (result 59)))
      (export (;15;) "return-expected-sugar3" (func (type 60)))
      (type (;61;) (tuple s32 u32))
      (type (;62;) (result 61 (error 53)))
      (type (;63;) (func (result 62)))
      (export (;16;) "return-expected-sugar4" (func (type 63)))
      (type (;64;) (option s32))
      (type (;65;) (func (result 64)))
      (export (;17;) "return-option-sugar" (func (type 65)))
      (type (;66;) (option 53))
      (type (;67;) (func (result 66)))
      (export (;18;) "return-option-sugar2" (func (type 67)))
      (type (;68;) (result u32 (error s32)))
      (type (;69;) (func (result 68)))
      (export (;19;) "expected-simple" (func (type 69)))
    )
  )
  (import "variants" (instance (;0;) (type 0)))
  (core module (;0;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (result i32)))
    (type (;2;) (func (param i32 i32)))
    (type (;3;) (func (param i32 i32 i32)))
    (type (;4;) (func (param i32 i32 i32 i32 i32 i32 i32 i32 f32 i32 i32 i32 i32 i32 i32)))
    (type (;5;) (func (param i32 i32 i32 i64 i32 i64 i32 i64 i32 i64 i32 i32 i32 i32)))
    (type (;6;) (func (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)))
    (type (;7;) (func (param i32 i32 i32 i32) (result i32)))
    (import "variants" "e1-arg" (func (;0;) (type 0)))
    (import "variants" "e1-result" (func (;1;) (type 1)))
    (import "variants" "u1-arg" (func (;2;) (type 2)))
    (import "variants" "u1-result" (func (;3;) (type 0)))
    (import "variants" "v1-arg" (func (;4;) (type 3)))
    (import "variants" "v1-result" (func (;5;) (type 0)))
    (import "variants" "bool-arg" (func (;6;) (type 0)))
    (import "variants" "bool-result" (func (;7;) (type 1)))
    (import "variants" "option-arg" (func (;8;) (type 4)))
    (import "variants" "option-result" (func (;9;) (type 0)))
    (import "variants" "casts" (func (;10;) (type 5)))
    (import "variants" "expected-arg" (func (;11;) (type 6)))
    (import "variants" "expected-result" (func (;12;) (type 0)))
    (import "variants" "return-expected-sugar" (func (;13;) (type 0)))
    (import "variants" "return-expected-sugar2" (func (;14;) (type 0)))
    (import "variants" "return-expected-sugar3" (func (;15;) (type 0)))
    (import "variants" "return-expected-sugar4" (func (;16;) (type 0)))
    (import "variants" "return-option-sugar" (func (;17;) (type 0)))
    (import "variants" "return-option-sugar2" (func (;18;) (type 0)))
    (import "variants" "expected-simple" (func (;19;) (type 0)))
    (func (;20;) (type 7) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (memory (;0;) 0)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 20))
  )
  (core module (;1;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func (param i32 i32 i32 i64 i32 i64 i32 i64 i32 i64 i32 i32 i32 i32)))
    (type (;3;) (func (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)))
    (func $indirect-variants-u1-result (;0;) (type 0) (param i32)
      local.get 0
      i32.const 0
      call_indirect (type 0)
    )
    (func $indirect-variants-v1-arg (;1;) (type 1) (param i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 1
      call_indirect (type 1)
    )
    (func $indirect-variants-v1-result (;2;) (type 0) (param i32)
      local.get 0
      i32.const 2
      call_indirect (type 0)
    )
    (func $indirect-variants-option-result (;3;) (type 0) (param i32)
      local.get 0
      i32.const 3
      call_indirect (type 0)
    )
    (func $indirect-variants-casts (;4;) (type 2) (param i32 i32 i32 i64 i32 i64 i32 i64 i32 i64 i32 i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      local.get 4
      local.get 5
      local.get 6
      local.get 7
      local.get 8
      local.get 9
      local.get 10
      local.get 11
      local.get 12
      local.get 13
      i32.const 4
      call_indirect (type 2)
    )
    (func $indirect-variants-expected-arg (;5;) (type 3) (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      local.get 4
      local.get 5
      local.get 6
      local.get 7
      local.get 8
      local.get 9
      local.get 10
      local.get 11
      local.get 12
      i32.const 5
      call_indirect (type 3)
    )
    (func $indirect-variants-expected-result (;6;) (type 0) (param i32)
      local.get 0
      i32.const 6
      call_indirect (type 0)
    )
    (func $indirect-variants-return-expected-sugar (;7;) (type 0) (param i32)
      local.get 0
      i32.const 7
      call_indirect (type 0)
    )
    (func $indirect-variants-return-expected-sugar2 (;8;) (type 0) (param i32)
      local.get 0
      i32.const 8
      call_indirect (type 0)
    )
    (func $indirect-variants-return-expected-sugar3 (;9;) (type 0) (param i32)
      local.get 0
      i32.const 9
      call_indirect (type 0)
    )
    (func $indirect-variants-return-expected-sugar4 (;10;) (type 0) (param i32)
      local.get 0
      i32.const 10
      call_indirect (type 0)
    )
    (func $indirect-variants-return-option-sugar (;11;) (type 0) (param i32)
      local.get 0
      i32.const 11
      call_indirect (type 0)
    )
    (func $indirect-variants-return-option-sugar2 (;12;) (type 0) (param i32)
      local.get 0
      i32.const 12
      call_indirect (type 0)
    )
    (func $indirect-variants-expected-simple (;13;) (type 0) (param i32)
      local.get 0
      i32.const 13
      call_indirect (type 0)
    )
    (table (;0;) 14 14 funcref)
    (export "0" (func $indirect-variants-u1-result))
    (export "1" (func $indirect-variants-v1-arg))
    (export "2" (func $indirect-variants-v1-result))
    (export "3" (func $indirect-variants-option-result))
    (export "4" (func $indirect-variants-casts))
    (export "5" (func $indirect-variants-expected-arg))
    (export "6" (func $indirect-variants-expected-result))
    (export "7" (func $indirect-variants-return-expected-sugar))
    (export "8" (func $indirect-variants-return-expected-sugar2))
    (export "9" (func $indirect-variants-return-expected-sugar3))
    (export "10" (func $indirect-variants-return-expected-sugar4))
    (export "11" (func $indirect-variants-return-option-sugar))
    (export "12" (func $indirect-variants-return-option-sugar2))
    (export "13" (func $indirect-variants-expected-simple))
    (export "$imports" (table 0))
  )
  (core module (;2;)
    (type (;0;) (func (param i32)))
    (type (;1;) (func (param i32 i32 i32)))
    (type (;2;) (func (param i32 i32 i32 i64 i32 i64 i32 i64 i32 i64 i32 i32 i32 i32)))
    (type (;3;) (func (param i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32 i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 1)))
    (import "" "2" (func (;2;) (type 0)))
    (import "" "3" (func (;3;) (type 0)))
    (import "" "4" (func (;4;) (type 2)))
    (import "" "5" (func (;5;) (type 3)))
    (import "" "6" (func (;6;) (type 0)))
    (import "" "7" (func (;7;) (type 0)))
    (import "" "8" (func (;8;) (type 0)))
    (import "" "9" (func (;9;) (type 0)))
    (import "" "10" (func (;10;) (type 0)))
    (import "" "11" (func (;11;) (type 0)))
    (import "" "12" (func (;12;) (type 0)))
    (import "" "13" (func (;13;) (type 0)))
    (import "" "$imports" (table (;0;) 14 14 funcref))
    (elem (;0;) (i32.const 0) func 0 1 2 3 4 5 6 7 8 9 10 11 12 13)
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (alias core export 0 "1" (core func (;1;)))
  (alias core export 0 "2" (core func (;2;)))
  (alias core export 0 "3" (core func (;3;)))
  (alias core export 0 "4" (core func (;4;)))
  (alias core export 0 "5" (core func (;5;)))
  (alias core export 0 "6" (core func (;6;)))
  (alias core export 0 "7" (core func (;7;)))
  (alias core export 0 "8" (core func (;8;)))
  (alias core export 0 "9" (core func (;9;)))
  (alias core export 0 "10" (core func (;10;)))
  (alias core export 0 "11" (core func (;11;)))
  (alias core export 0 "12" (core func (;12;)))
  (alias core export 0 "13" (core func (;13;)))
  (alias export 0 "e1-arg" (func (;0;)))
  (core func (;14;) (canon lower (func 0)))
  (alias export 0 "e1-result" (func (;1;)))
  (core func (;15;) (canon lower (func 1)))
  (alias export 0 "u1-arg" (func (;2;)))
  (core func (;16;) (canon lower (func 2)))
  (alias export 0 "bool-arg" (func (;3;)))
  (core func (;17;) (canon lower (func 3)))
  (alias export 0 "bool-result" (func (;4;)))
  (core func (;18;) (canon lower (func 4)))
  (alias export 0 "option-arg" (func (;5;)))
  (core func (;19;) (canon lower (func 5)))
  (core instance (;1;)
    (export "u1-result" (func 0))
    (export "v1-arg" (func 1))
    (export "v1-result" (func 2))
    (export "option-result" (func 3))
    (export "casts" (func 4))
    (export "expected-arg" (func 5))
    (export "expected-result" (func 6))
    (export "return-expected-sugar" (func 7))
    (export "return-expected-sugar2" (func 8))
    (export "return-expected-sugar3" (func 9))
    (export "return-expected-sugar4" (func 10))
    (export "return-option-sugar" (func 11))
    (export "return-option-sugar2" (func 12))
    (export "expected-simple" (func 13))
    (export "e1-arg" (func 14))
    (export "e1-result" (func 15))
    (export "u1-arg" (func 16))
    (export "bool-arg" (func 17))
    (export "bool-result" (func 18))
    (export "option-arg" (func 19))
  )
  (core instance (;2;) (instantiate 0
      (with "variants" (instance 1))
    )
  )
  (alias core export 2 "memory" (core memory (;0;)))
  (alias core export 2 "cabi_realloc" (core func (;20;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias export 0 "u1-result" (func (;6;)))
  (core func (;21;) (canon lower (func 6) (memory 0)))
  (alias export 0 "v1-arg" (func (;7;)))
  (core func (;22;) (canon lower (func 7) (memory 0) string-encoding=utf8))
  (alias export 0 "v1-result" (func (;8;)))
  (core func (;23;) (canon lower (func 8) (memory 0) (realloc 20) string-encoding=utf8))
  (alias export 0 "option-result" (func (;9;)))
  (core func (;24;) (canon lower (func 9) (memory 0)))
  (alias export 0 "casts" (func (;10;)))
  (core func (;25;) (canon lower (func 10) (memory 0)))
  (alias export 0 "expected-arg" (func (;11;)))
  (core func (;26;) (canon lower (func 11) (memory 0) string-encoding=utf8))
  (alias export 0 "expected-result" (func (;12;)))
  (core func (;27;) (canon lower (func 12) (memory 0) (realloc 20) string-encoding=utf8))
  (alias export 0 "return-expected-sugar" (func (;13;)))
  (core func (;28;) (canon lower (func 13) (memory 0)))
  (alias export 0 "return-expected-sugar2" (func (;14;)))
  (core func (;29;) (canon lower (func 14) (memory 0)))
  (alias export 0 "return-expected-sugar3" (func (;15;)))
  (core func (;30;) (canon lower (func 15) (memory 0)))
  (alias export 0 "return-expected-sugar4" (func (;16;)))
  (core func (;31;) (canon lower (func 16) (memory 0)))
  (alias export 0 "return-option-sugar" (func (;17;)))
  (core func (;32;) (canon lower (func 17) (memory 0)))
  (alias export 0 "return-option-sugar2" (func (;18;)))
  (core func (;33;) (canon lower (func 18) (memory 0)))
  (alias export 0 "expected-simple" (func (;19;)))
  (core func (;34;) (canon lower (func 19) (memory 0)))
  (core instance (;3;)
    (export "$imports" (table 0))
    (export "0" (func 21))
    (export "1" (func 22))
    (export "2" (func 23))
    (export "3" (func 24))
    (export "4" (func 25))
    (export "5" (func 26))
    (export "6" (func 27))
    (export "7" (func 28))
    (export "8" (func 29))
    (export "9" (func 30))
    (export "10" (func 31))
    (export "11" (func 32))
    (export "12" (func 33))
    (export "13" (func 34))
  )
  (core instance (;4;) (instantiate 2
      (with "" (instance 3))
    )
  )
)