(component
  (type (;0;)
    (instance
      (type (;0;) (enum "a"))
      (export "e1" (type (eq 0)))
      (type (;1;) (func (param "x" 0)))
      (export "e1-arg" (func (type 2)))
      (type (;2;) (func (result 0)))
      (export "e1-result" (func (type 3)))
      (type (;3;) (union u32 float32))
      (export "u1" (type (eq 4)))
      (type (;4;) (func (param "x" 4)))
      (export "u1-arg" (func (type 6)))
      (type (;5;) (func (result 4)))
      (export "u1-result" (func (type 7)))
      (type (;6;) (record))
      (export "empty" (type (eq 8)))
      (type (;7;) (variant (case "a") (case "b" 4) (case "c" 0) (case "d" string) (case "e" 8) (case "f") (case "g" u32)))
      (export "v1" (type (eq 10)))
      (type (;8;) (func (param "x" 10)))
      (export "v1-arg" (func (type 12)))
      (type (;9;) (func (result 10)))
      (export "v1-result" (func (type 13)))
      (type (;10;) (func (param "x" bool)))
      (export "bool-arg" (func (type 14)))
      (type (;11;) (func (result bool)))
      (export "bool-result" (func (type 15)))
      (type (;12;) (option bool))
      (type (;13;) (tuple))
      (type (;14;) (option 17))
      (type (;15;) (option u32))
      (type (;16;) (option 0))
      (type (;17;) (option float32))
      (type (;18;) (option 4))
      (type (;19;) (option 16))
      (type (;20;) (func (param "a" 16) (param "b" 18) (param "c" 19) (param "d" 20) (param "e" 21) (param "f" 22) (param "g" 23)))
      (export "option-arg" (func (type 24)))
      (type (;21;) (tuple 16 18 19 20 21 22 23))
      (type (;22;) (func (result 25)))
      (export "option-result" (func (type 26)))
      (type (;23;) (variant (case "a" s32) (case "b" float32)))
      (export "casts1" (type (eq 27)))
      (type (;24;) (variant (case "a" float64) (case "b" float32)))
      (export "casts2" (type (eq 29)))
      (type (;25;) (variant (case "a" float64) (case "b" u64)))
      (export "casts3" (type (eq 31)))
      (type (;26;) (variant (case "a" u32) (case "b" s64)))
      (export "casts4" (type (eq 33)))
      (type (;27;) (variant (case "a" float32) (case "b" s64)))
      (export "casts5" (type (eq 35)))
      (type (;28;) (tuple float32 u32))
      (type (;29;) (tuple u32 u32))
      (type (;30;) (variant (case "a" 37) (case "b" 38)))
      (export "casts6" (type (eq 39)))
      (type (;31;) (tuple 27 29 31 33 35 39))
      (type (;32;) (func (param "a" 27) (param "b" 29) (param "c" 31) (param "d" 33) (param "e" 35) (param "f" 39) (result 41)))
      (export "casts" (func (type 42)))
      (type (;33;) (result))
      (type (;34;) (result (error 0)))
      (type (;35;) (result 0))
      (type (;36;) (result 17 (error 17)))
      (type (;37;) (result u32 (error 10)))
      (type (;38;) (list u8))
      (type (;39;) (result string (error 48)))
      (type (;40;) (func (param "a" 43) (param "b" 44) (param "c" 45) (param "d" 46) (param "e" 47) (param "f" 49)))
      (export "expected-arg" (func (type 50)))
      (type (;41;) (tuple 43 44 45 46 47 49))
      (type (;42;) (func (result 51)))
      (export "expected-result" (func (type 52)))
      (type (;43;) (enum "bad1" "bad2"))
      (export "my-errno" (type (eq 53)))
      (type (;44;) (result s32 (error 53)))
      (type (;45;) (func (result 55)))
      (export "return-expected-sugar" (func (type 56)))
      (type (;46;) (result (error 53)))
      (type (;47;) (func (result 57)))
      (export "return-expected-sugar2" (func (type 58)))
      (type (;48;) (result 53 (error 53)))
      (type (;49;) (func (result 59)))
      (export "return-expected-sugar3" (func (type 60)))
      (type (;50;) (tuple s32 u32))
      (type (;51;) (result 61 (error 53)))
      (type (;52;) (func (result 62)))
      (export "return-expected-sugar4" (func (type 63)))
      (type (;53;) (option s32))
      (type (;54;) (func (result 64)))
      (export "return-option-sugar" (func (type 65)))
      (type (;55;) (option 53))
      (type (;56;) (func (result 66)))
      (export "return-option-sugar2" (func (type 67)))
      (type (;57;) (result u32 (error s32)))
      (type (;58;) (func (result 68)))
      (export "expected-simple" (func (type 69)))
    )
  )
  (import "variants" (instance (;0;) (type 0)))
)