(component
  (type (;0;) (enum "a"))
  (type (;1;) (func (param "x" (type 0))))
  (type (;2;) (func (result (type 0))))
  (type (;3;) (union u32 float32))
  (type (;4;) (func (param "x" (type 3))))
  (type (;5;) (func (result (type 3))))
  (type (;6;) (record))
  (type (;7;) (variant (case "a" unit) (case "b" (type 3)) (case "c" (type 0)) (case "d" string) (case "e" (type 6)) (case "f" unit) (case "g" u32)))
  (type (;8;) (func (param "x" (type 7))))
  (type (;9;) (func (result (type 7))))
  (type (;10;) (func (param "x" bool)))
  (type (;11;) (func (result bool)))
  (type (;12;) (option bool))
  (type (;13;) (tuple))
  (type (;14;) (option (type 13)))
  (type (;15;) (option u32))
  (type (;16;) (option (type 0)))
  (type (;17;) (option float32))
  (type (;18;) (option (type 3)))
  (type (;19;) (option (type 12)))
  (type (;20;) (func (param "a" (type 12)) (param "b" (type 14)) (param "c" (type 15)) (param "d" (type 16)) (param "e" (type 17)) (param "f" (type 18)) (param "g" (type 19))))
  (type (;21;) (tuple (type 12) (type 14) (type 15) (type 16) (type 17) (type 18) (type 19)))
  (type (;22;) (func (result (type 21))))
  (type (;23;) (variant (case "a" s32) (case "b" float32)))
  (type (;24;) (variant (case "a" float64) (case "b" float32)))
  (type (;25;) (variant (case "a" float64) (case "b" u64)))
  (type (;26;) (variant (case "a" u32) (case "b" s64)))
  (type (;27;) (variant (case "a" float32) (case "b" s64)))
  (type (;28;) (tuple float32 u32))
  (type (;29;) (tuple u32 u32))
  (type (;30;) (variant (case "a" (type 28)) (case "b" (type 29))))
  (type (;31;) (tuple (type 23) (type 24) (type 25) (type 26) (type 27) (type 30)))
  (type (;32;) (func (param "a" (type 23)) (param "b" (type 24)) (param "c" (type 25)) (param "d" (type 26)) (param "e" (type 27)) (param "f" (type 30)) (result (type 31))))
  (type (;33;) (expected unit unit))
  (type (;34;) (expected unit (type 0)))
  (type (;35;) (expected (type 0) unit))
  (type (;36;) (expected (type 13) (type 13)))
  (type (;37;) (expected u32 (type 7)))
  (type (;38;) (list u8))
  (type (;39;) (expected string (type 38)))
  (type (;40;) (func (param "a" (type 33)) (param "b" (type 34)) (param "c" (type 35)) (param "d" (type 36)) (param "e" (type 37)) (param "f" (type 39))))
  (type (;41;) (tuple (type 33) (type 34) (type 35) (type 36) (type 37) (type 39)))
  (type (;42;) (func (result (type 41))))
  (type (;43;) (enum "bad1" "bad2"))
  (type (;44;) (expected s32 (type 43)))
  (type (;45;) (func (result (type 44))))
  (type (;46;) (expected unit (type 43)))
  (type (;47;) (func (result (type 46))))
  (type (;48;) (expected (type 43) (type 43)))
  (type (;49;) (func (result (type 48))))
  (type (;50;) (tuple s32 u32))
  (type (;51;) (expected (type 50) (type 43)))
  (type (;52;) (func (result (type 51))))
  (type (;53;) (option s32))
  (type (;54;) (func (result (type 53))))
  (type (;55;) (option (type 43)))
  (type (;56;) (func (result (type 55))))
  (type (;57;) (expected u32 s32))
  (type (;58;) (func (result (type 57))))
  (export "e1" (type 0))
  (export "e1-arg" (type 1))
  (export "e1-result" (type 2))
  (export "u1" (type 3))
  (export "u1-arg" (type 4))
  (export "u1-result" (type 5))
  (export "empty" (type 6))
  (export "v1" (type 7))
  (export "v1-arg" (type 8))
  (export "v1-result" (type 9))
  (export "bool-arg" (type 10))
  (export "bool-result" (type 11))
  (export "option-arg" (type 20))
  (export "option-result" (type 22))
  (export "casts1" (type 23))
  (export "casts2" (type 24))
  (export "casts3" (type 25))
  (export "casts4" (type 26))
  (export "casts5" (type 27))
  (export "casts6" (type 30))
  (export "casts" (type 32))
  (export "expected-arg" (type 40))
  (export "expected-result" (type 42))
  (export "my-errno" (type 43))
  (export "return-expected-sugar" (type 45))
  (export "return-expected-sugar2" (type 47))
  (export "return-expected-sugar3" (type 49))
  (export "return-expected-sugar4" (type 52))
  (export "return-option-sugar" (type 54))
  (export "return-option-sugar2" (type 56))
  (export "expected-simple" (type 58))
)