(component
  (import "a" (type (;0;) (sub resource)))
  (type (;1;) (own 0))
  (type (;2;) (func (result 1)))
  (import "[constructor]a" (func (;0;) (type 2)))
  (import "[static]a.other-new" (func (;1;) (type 2)))
  (core module (;0;)
    (type (;0;) (func (result i32)))
    (type (;1;) (func (param i32)))
    (import "$root" "[constructor]a" (func (;0;) (type 0)))
    (import "$root" "[static]a.other-new" (func (;1;) (type 0)))
    (import "$root" "[resource-drop-own]a" (func (;2;) (type 1)))
    (import "$root" "[resource-drop-borrow]a" (func (;3;) (type 1)))
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (type (;3;) (own 0))
  (core func (;0;) (canon resource.drop 3))
  (type (;4;) (borrow 0))
  (core func (;1;) (canon resource.drop 4))
  (core func (;2;) (canon lower (func 0)))
  (core func (;3;) (canon lower (func 1)))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
  (core instance (;0;)
    (export "[resource-drop-own]a" (func 0))
    (export "[resource-drop-borrow]a" (func 1))
    (export "[constructor]a" (func 2))
    (export "[static]a.other-new" (func 3))
  )
  (core instance (;1;) (instantiate 0
      (with "$root" (instance 0))
    )
  )
)