(component
  (type $ty-foo:foo/bar (;0;)
    (instance
      (type (;0;) (future u32))
      (type (;1;) (future 0))
      (type (;2;) (stream string))
      (type (;3;) (func async (param "x" 1) (param "y" u32) (result 2)))
      (export (;0;) "foo" (func (type 3)))
    )
  )
  (import "foo:foo/bar" (instance $foo:foo/bar (;0;) (type $ty-foo:foo/bar)))
  (type (;1;) (future u32))
  (type (;2;) (future 1))
  (type (;3;) (stream string))
  (type (;4;) (func async (param "x" 2) (param "y" u32) (result 3)))
  (import "foo" (func $foo (;0;) (type 4)))
  (core module $main (;0;)
    (type (;0;) (func (param i32 i32 i32) (result i32)))
    (type (;1;) (func (result i64)))
    (type (;2;) (func (param i32) (result i32)))
    (type (;3;) (func (param i32)))
    (type (;4;) (func (param i32 i32) (result i32)))
    (type (;5;) (func (param i32 i32)))
    (type (;6;) (func (param i32 i32 i32 i32) (result i32)))
    (import "$root" "[async-lower]foo" (func (;0;) (type 0)))
    (import "foo:foo/bar" "[async-lower]foo" (func (;1;) (type 0)))
    (import "$root" "[stream-new-2]foo" (func (;2;) (type 1)))
    (import "$root" "[stream-read-2]foo" (func (;3;) (type 0)))
    (import "$root" "[stream-write-2]foo" (func (;4;) (type 0)))
    (import "$root" "[stream-cancel-read-2]foo" (func (;5;) (type 2)))
    (import "$root" "[stream-cancel-write-2]foo" (func (;6;) (type 2)))
    (import "$root" "[stream-drop-readable-2]foo" (func (;7;) (type 3)))
    (import "$root" "[stream-drop-writable-2]foo" (func (;8;) (type 3)))
    (import "foo:foo/bar" "[stream-new-2]foo" (func (;9;) (type 1)))
    (import "foo:foo/bar" "[stream-read-2]foo" (func (;10;) (type 0)))
    (import "foo:foo/bar" "[stream-write-2]foo" (func (;11;) (type 0)))
    (import "foo:foo/bar" "[stream-cancel-read-2]foo" (func (;12;) (type 2)))
    (import "foo:foo/bar" "[stream-cancel-write-2]foo" (func (;13;) (type 2)))
    (import "foo:foo/bar" "[stream-drop-readable-2]foo" (func (;14;) (type 3)))
    (import "foo:foo/bar" "[stream-drop-writable-2]foo" (func (;15;) (type 3)))
    (import "$root" "[future-new-0]foo" (func (;16;) (type 1)))
    (import "$root" "[future-read-0]foo" (func (;17;) (type 4)))
    (import "$root" "[future-write-0]foo" (func (;18;) (type 4)))
    (import "$root" "[future-cancel-read-0]foo" (func (;19;) (type 2)))
    (import "$root" "[future-cancel-write-0]foo" (func (;20;) (type 2)))
    (import "$root" "[future-drop-readable-0]foo" (func (;21;) (type 3)))
    (import "$root" "[future-drop-writable-0]foo" (func (;22;) (type 3)))
    (import "foo:foo/bar" "[future-new-0]foo" (func (;23;) (type 1)))
    (import "foo:foo/bar" "[future-read-0]foo" (func (;24;) (type 4)))
    (import "foo:foo/bar" "[future-write-0]foo" (func (;25;) (type 4)))
    (import "foo:foo/bar" "[future-cancel-read-0]foo" (func (;26;) (type 2)))
    (import "foo:foo/bar" "[future-cancel-write-0]foo" (func (;27;) (type 2)))
    (import "foo:foo/bar" "[future-drop-readable-0]foo" (func (;28;) (type 3)))
    (import "foo:foo/bar" "[future-drop-writable-0]foo" (func (;29;) (type 3)))
    (import "$root" "[future-new-1]foo" (func (;30;) (type 1)))
    (import "$root" "[future-read-1]foo" (func (;31;) (type 4)))
    (import "$root" "[future-write-1]foo" (func (;32;) (type 4)))
    (import "$root" "[future-cancel-read-1]foo" (func (;33;) (type 2)))
    (import "$root" "[future-cancel-write-1]foo" (func (;34;) (type 2)))
    (import "$root" "[future-drop-readable-1]foo" (func (;35;) (type 3)))
    (import "$root" "[future-drop-writable-1]foo" (func (;36;) (type 3)))
    (import "foo:foo/bar" "[future-new-1]foo" (func (;37;) (type 1)))
    (import "foo:foo/bar" "[future-read-1]foo" (func (;38;) (type 4)))
    (import "foo:foo/bar" "[future-write-1]foo" (func (;39;) (type 4)))
    (import "foo:foo/bar" "[future-cancel-read-1]foo" (func (;40;) (type 2)))
    (import "foo:foo/bar" "[future-cancel-write-1]foo" (func (;41;) (type 2)))
    (import "foo:foo/bar" "[future-drop-readable-1]foo" (func (;42;) (type 3)))
    (import "foo:foo/bar" "[future-drop-writable-1]foo" (func (;43;) (type 3)))
    (import "[export]$root" "[stream-new-2]foo" (func (;44;) (type 1)))
    (import "[export]$root" "[stream-read-2]foo" (func (;45;) (type 0)))
    (import "[export]$root" "[stream-write-2]foo" (func (;46;) (type 0)))
    (import "[export]$root" "[stream-cancel-read-2]foo" (func (;47;) (type 2)))
    (import "[export]$root" "[stream-cancel-write-2]foo" (func (;48;) (type 2)))
    (import "[export]$root" "[stream-drop-readable-2]foo" (func (;49;) (type 3)))
    (import "[export]$root" "[stream-drop-writable-2]foo" (func (;50;) (type 3)))
    (import "[export]foo:foo/bar" "[stream-new-2]foo" (func (;51;) (type 1)))
    (import "[export]foo:foo/bar" "[stream-read-2]foo" (func (;52;) (type 0)))
    (import "[export]foo:foo/bar" "[stream-write-2]foo" (func (;53;) (type 0)))
    (import "[export]foo:foo/bar" "[stream-cancel-read-2]foo" (func (;54;) (type 2)))
    (import "[export]foo:foo/bar" "[stream-cancel-write-2]foo" (func (;55;) (type 2)))
    (import "[export]foo:foo/bar" "[stream-drop-readable-2]foo" (func (;56;) (type 3)))
    (import "[export]foo:foo/bar" "[stream-drop-writable-2]foo" (func (;57;) (type 3)))
    (import "[export]$root" "[future-new-0]foo" (func (;58;) (type 1)))
    (import "[export]$root" "[future-read-0]foo" (func (;59;) (type 4)))
    (import "[export]$root" "[future-write-0]foo" (func (;60;) (type 4)))
    (import "[export]$root" "[future-cancel-read-0]foo" (func (;61;) (type 2)))
    (import "[export]$root" "[future-cancel-write-0]foo" (func (;62;) (type 2)))
    (import "[export]$root" "[future-drop-readable-0]foo" (func (;63;) (type 3)))
    (import "[export]$root" "[future-drop-writable-0]foo" (func (;64;) (type 3)))
    (import "[export]foo:foo/bar" "[future-new-0]foo" (func (;65;) (type 1)))
    (import "[export]foo:foo/bar" "[future-read-0]foo" (func (;66;) (type 4)))
    (import "[export]foo:foo/bar" "[future-write-0]foo" (func (;67;) (type 4)))
    (import "[export]foo:foo/bar" "[future-cancel-read-0]foo" (func (;68;) (type 2)))
    (import "[export]foo:foo/bar" "[future-cancel-write-0]foo" (func (;69;) (type 2)))
    (import "[export]foo:foo/bar" "[future-drop-readable-0]foo" (func (;70;) (type 3)))
    (import "[export]foo:foo/bar" "[future-drop-writable-0]foo" (func (;71;) (type 3)))
    (import "[export]$root" "[future-new-1]foo" (func (;72;) (type 1)))
    (import "[export]$root" "[future-read-1]foo" (func (;73;) (type 4)))
    (import "[export]$root" "[future-write-1]foo" (func (;74;) (type 4)))
    (import "[export]$root" "[future-cancel-read-1]foo" (func (;75;) (type 2)))
    (import "[export]$root" "[future-cancel-write-1]foo" (func (;76;) (type 2)))
    (import "[export]$root" "[future-drop-readable-1]foo" (func (;77;) (type 3)))
    (import "[export]$root" "[future-drop-writable-1]foo" (func (;78;) (type 3)))
    (import "[export]foo:foo/bar" "[future-new-1]foo" (func (;79;) (type 1)))
    (import "[export]foo:foo/bar" "[future-read-1]foo" (func (;80;) (type 4)))
    (import "[export]foo:foo/bar" "[future-write-1]foo" (func (;81;) (type 4)))
    (import "[export]foo:foo/bar" "[future-cancel-read-1]foo" (func (;82;) (type 2)))
    (import "[export]foo:foo/bar" "[future-cancel-write-1]foo" (func (;83;) (type 2)))
    (import "[export]foo:foo/bar" "[future-drop-readable-1]foo" (func (;84;) (type 3)))
    (import "[export]foo:foo/bar" "[future-drop-writable-1]foo" (func (;85;) (type 3)))
    (import "$root" "[error-context-debug-message-utf8]" (func (;86;) (type 5)))
    (memory (;0;) 1)
    (export "__wasm_task_hook" (func 87))
    (export "[async-lift-stackful]foo" (func 88))
    (export "[async-lift-stackful]foo:foo/bar#foo" (func 89))
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 90))
    (func (;87;) (type 3) (param i32)
      unreachable
    )
    (func (;88;) (type 5) (param i32 i32)
      unreachable
    )
    (func (;89;) (type 5) (param i32 i32)
      unreachable
    )
    (func (;90;) (type 6) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module $wit-component-shim-module (;1;)
    (type (;0;) (func (param i32 i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;2;) (func (param i32 i32) (result i32)))
    (type (;3;) (func (param i32 i32)))
    (table (;0;) 28 28 funcref)
    (export "0" (func $"indirect-$root-[async-lower]foo"))
    (export "1" (func $"$root-[stream-read-2]foo"))
    (export "2" (func $realloc-main-cabi_realloc))
    (export "3" (func $"$root-[stream-write-2]foo"))
    (export "4" (func $"$root-[future-read-0]foo"))
    (export "5" (func $"$root-[future-write-0]foo"))
    (export "6" (func $"$root-[future-read-1]foo"))
    (export "7" (func $"$root-[future-write-1]foo"))
    (export "8" (func $error-debug-message))
    (export "9" (func $"indirect-foo:foo/bar-[async-lower]foo"))
    (export "10" (func $"foo:foo/bar-[stream-read-2]foo"))
    (export "11" (func $"foo:foo/bar-[stream-write-2]foo"))
    (export "12" (func $"foo:foo/bar-[future-read-0]foo"))
    (export "13" (func $"foo:foo/bar-[future-write-0]foo"))
    (export "14" (func $"foo:foo/bar-[future-read-1]foo"))
    (export "15" (func $"foo:foo/bar-[future-write-1]foo"))
    (export "16" (func $"[export]$root-[stream-read-2]foo"))
    (export "17" (func $"[export]$root-[stream-write-2]foo"))
    (export "18" (func $"[export]$root-[future-read-0]foo"))
    (export "19" (func $"[export]$root-[future-write-0]foo"))
    (export "20" (func $"[export]$root-[future-read-1]foo"))
    (export "21" (func $"[export]$root-[future-write-1]foo"))
    (export "22" (func $"[export]foo:foo/bar-[stream-read-2]foo"))
    (export "23" (func $"[export]foo:foo/bar-[stream-write-2]foo"))
    (export "24" (func $"[export]foo:foo/bar-[future-read-0]foo"))
    (export "25" (func $"[export]foo:foo/bar-[future-write-0]foo"))
    (export "26" (func $"[export]foo:foo/bar-[future-read-1]foo"))
    (export "27" (func $"[export]foo:foo/bar-[future-write-1]foo"))
    (export "$imports" (table 0))
    (func $"indirect-$root-[async-lower]foo" (;0;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 0
      call_indirect (type 0)
    )
    (func $"$root-[stream-read-2]foo" (;1;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 1
      call_indirect (type 0)
    )
    (func $realloc-main-cabi_realloc (;2;) (type 1) (param i32 i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      i32.const 2
      call_indirect (type 1)
    )
    (func $"$root-[stream-write-2]foo" (;3;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 3
      call_indirect (type 0)
    )
    (func $"$root-[future-read-0]foo" (;4;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 4
      call_indirect (type 2)
    )
    (func $"$root-[future-write-0]foo" (;5;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 5
      call_indirect (type 2)
    )
    (func $"$root-[future-read-1]foo" (;6;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 6
      call_indirect (type 2)
    )
    (func $"$root-[future-write-1]foo" (;7;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 7
      call_indirect (type 2)
    )
    (func $error-debug-message (;8;) (type 3) (param i32 i32)
      local.get 0
      local.get 1
      i32.const 8
      call_indirect (type 3)
    )
    (func $"indirect-foo:foo/bar-[async-lower]foo" (;9;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 9
      call_indirect (type 0)
    )
    (func $"foo:foo/bar-[stream-read-2]foo" (;10;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 10
      call_indirect (type 0)
    )
    (func $"foo:foo/bar-[stream-write-2]foo" (;11;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 11
      call_indirect (type 0)
    )
    (func $"foo:foo/bar-[future-read-0]foo" (;12;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 12
      call_indirect (type 2)
    )
    (func $"foo:foo/bar-[future-write-0]foo" (;13;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 13
      call_indirect (type 2)
    )
    (func $"foo:foo/bar-[future-read-1]foo" (;14;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 14
      call_indirect (type 2)
    )
    (func $"foo:foo/bar-[future-write-1]foo" (;15;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 15
      call_indirect (type 2)
    )
    (func $"[export]$root-[stream-read-2]foo" (;16;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 16
      call_indirect (type 0)
    )
    (func $"[export]$root-[stream-write-2]foo" (;17;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 17
      call_indirect (type 0)
    )
    (func $"[export]$root-[future-read-0]foo" (;18;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 18
      call_indirect (type 2)
    )
    (func $"[export]$root-[future-write-0]foo" (;19;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 19
      call_indirect (type 2)
    )
    (func $"[export]$root-[future-read-1]foo" (;20;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 20
      call_indirect (type 2)
    )
    (func $"[export]$root-[future-write-1]foo" (;21;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 21
      call_indirect (type 2)
    )
    (func $"[export]foo:foo/bar-[stream-read-2]foo" (;22;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 22
      call_indirect (type 0)
    )
    (func $"[export]foo:foo/bar-[stream-write-2]foo" (;23;) (type 0) (param i32 i32 i32) (result i32)
      local.get 0
      local.get 1
      local.get 2
      i32.const 23
      call_indirect (type 0)
    )
    (func $"[export]foo:foo/bar-[future-read-0]foo" (;24;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 24
      call_indirect (type 2)
    )
    (func $"[export]foo:foo/bar-[future-write-0]foo" (;25;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 25
      call_indirect (type 2)
    )
    (func $"[export]foo:foo/bar-[future-read-1]foo" (;26;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 26
      call_indirect (type 2)
    )
    (func $"[export]foo:foo/bar-[future-write-1]foo" (;27;) (type 2) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 27
      call_indirect (type 2)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance $wit-component-shim-instance (;0;) (instantiate $wit-component-shim-module))
  (alias core export $wit-component-shim-instance "0" (core func $"indirect-$root-[async-lower]foo" (;0;)))
  (core func $stream.new (;1;) (canon stream.new 3))
  (alias core export $wit-component-shim-instance "1" (core func $"$root-[stream-read-2]foo" (;2;)))
  (alias core export $wit-component-shim-instance "3" (core func $"$root-[stream-write-2]foo" (;3;)))
  (core func $stream.cancel-read (;4;) (canon stream.cancel-read 3))
  (core func $stream.cancel-write (;5;) (canon stream.cancel-write 3))
  (core func $stream.drop-readable (;6;) (canon stream.drop-readable 3))
  (core func $stream.drop-writable (;7;) (canon stream.drop-writable 3))
  (core func $future.new (;8;) (canon future.new 1))
  (alias core export $wit-component-shim-instance "4" (core func $"$root-[future-read-0]foo" (;9;)))
  (alias core export $wit-component-shim-instance "5" (core func $"$root-[future-write-0]foo" (;10;)))
  (core func $future.cancel-read (;11;) (canon future.cancel-read 1))
  (core func $future.cancel-write (;12;) (canon future.cancel-write 1))
  (core func $future.drop-readable (;13;) (canon future.drop-readable 1))
  (core func $future.drop-writable (;14;) (canon future.drop-writable 1))
  (core func $"#core-func15 future.new" (@name "future.new") (;15;) (canon future.new 2))
  (alias core export $wit-component-shim-instance "6" (core func $"$root-[future-read-1]foo" (;16;)))
  (alias core export $wit-component-shim-instance "7" (core func $"$root-[future-write-1]foo" (;17;)))
  (core func $"#core-func18 future.cancel-read" (@name "future.cancel-read") (;18;) (canon future.cancel-read 2))
  (core func $"#core-func19 future.cancel-write" (@name "future.cancel-write") (;19;) (canon future.cancel-write 2))
  (core func $"#core-func20 future.drop-readable" (@name "future.drop-readable") (;20;) (canon future.drop-readable 2))
  (core func $"#core-func21 future.drop-writable" (@name "future.drop-writable") (;21;) (canon future.drop-writable 2))
  (alias core export $wit-component-shim-instance "8" (core func $error-debug-message (;22;)))
  (core instance $$root (;1;)
    (export "[async-lower]foo" (func $"indirect-$root-[async-lower]foo"))
    (export "[stream-new-2]foo" (func $stream.new))
    (export "[stream-read-2]foo" (func $"$root-[stream-read-2]foo"))
    (export "[stream-write-2]foo" (func $"$root-[stream-write-2]foo"))
    (export "[stream-cancel-read-2]foo" (func $stream.cancel-read))
    (export "[stream-cancel-write-2]foo" (func $stream.cancel-write))
    (export "[stream-drop-readable-2]foo" (func $stream.drop-readable))
    (export "[stream-drop-writable-2]foo" (func $stream.drop-writable))
    (export "[future-new-0]foo" (func $future.new))
    (export "[future-read-0]foo" (func $"$root-[future-read-0]foo"))
    (export "[future-write-0]foo" (func $"$root-[future-write-0]foo"))
    (export "[future-cancel-read-0]foo" (func $future.cancel-read))
    (export "[future-cancel-write-0]foo" (func $future.cancel-write))
    (export "[future-drop-readable-0]foo" (func $future.drop-readable))
    (export "[future-drop-writable-0]foo" (func $future.drop-writable))
    (export "[future-new-1]foo" (func $"#core-func15 future.new"))
    (export "[future-read-1]foo" (func $"$root-[future-read-1]foo"))
    (export "[future-write-1]foo" (func $"$root-[future-write-1]foo"))
    (export "[future-cancel-read-1]foo" (func $"#core-func18 future.cancel-read"))
    (export "[future-cancel-write-1]foo" (func $"#core-func19 future.cancel-write"))
    (export "[future-drop-readable-1]foo" (func $"#core-func20 future.drop-readable"))
    (export "[future-drop-writable-1]foo" (func $"#core-func21 future.drop-writable"))
    (export "[error-context-debug-message-utf8]" (func $error-debug-message))
  )
  (alias core export $wit-component-shim-instance "9" (core func $"indirect-foo:foo/bar-[async-lower]foo" (;23;)))
  (core func $"#core-func24 stream.new" (@name "stream.new") (;24;) (canon stream.new 3))
  (alias core export $wit-component-shim-instance "10" (core func $"foo:foo/bar-[stream-read-2]foo" (;25;)))
  (alias core export $wit-component-shim-instance "11" (core func $"foo:foo/bar-[stream-write-2]foo" (;26;)))
  (core func $"#core-func27 stream.cancel-read" (@name "stream.cancel-read") (;27;) (canon stream.cancel-read 3))
  (core func $"#core-func28 stream.cancel-write" (@name "stream.cancel-write") (;28;) (canon stream.cancel-write 3))
  (core func $"#core-func29 stream.drop-readable" (@name "stream.drop-readable") (;29;) (canon stream.drop-readable 3))
  (core func $"#core-func30 stream.drop-writable" (@name "stream.drop-writable") (;30;) (canon stream.drop-writable 3))
  (core func $"#core-func31 future.new" (@name "future.new") (;31;) (canon future.new 1))
  (alias core export $wit-component-shim-instance "12" (core func $"foo:foo/bar-[future-read-0]foo" (;32;)))
  (alias core export $wit-component-shim-instance "13" (core func $"foo:foo/bar-[future-write-0]foo" (;33;)))
  (core func $"#core-func34 future.cancel-read" (@name "future.cancel-read") (;34;) (canon future.cancel-read 1))
  (core func $"#core-func35 future.cancel-write" (@name "future.cancel-write") (;35;) (canon future.cancel-write 1))
  (core func $"#core-func36 future.drop-readable" (@name "future.drop-readable") (;36;) (canon future.drop-readable 1))
  (core func $"#core-func37 future.drop-writable" (@name "future.drop-writable") (;37;) (canon future.drop-writable 1))
  (type (;5;) (future 1))
  (core func $"#core-func38 future.new" (@name "future.new") (;38;) (canon future.new 5))
  (alias core export $wit-component-shim-instance "14" (core func $"foo:foo/bar-[future-read-1]foo" (;39;)))
  (alias core export $wit-component-shim-instance "15" (core func $"foo:foo/bar-[future-write-1]foo" (;40;)))
  (core func $"#core-func41 future.cancel-read" (@name "future.cancel-read") (;41;) (canon future.cancel-read 5))
  (core func $"#core-func42 future.cancel-write" (@name "future.cancel-write") (;42;) (canon future.cancel-write 5))
  (core func $"#core-func43 future.drop-readable" (@name "future.drop-readable") (;43;) (canon future.drop-readable 5))
  (core func $"#core-func44 future.drop-writable" (@name "future.drop-writable") (;44;) (canon future.drop-writable 5))
  (core instance $foo:foo/bar (;2;)
    (export "[async-lower]foo" (func $"indirect-foo:foo/bar-[async-lower]foo"))
    (export "[stream-new-2]foo" (func $"#core-func24 stream.new"))
    (export "[stream-read-2]foo" (func $"foo:foo/bar-[stream-read-2]foo"))
    (export "[stream-write-2]foo" (func $"foo:foo/bar-[stream-write-2]foo"))
    (export "[stream-cancel-read-2]foo" (func $"#core-func27 stream.cancel-read"))
    (export "[stream-cancel-write-2]foo" (func $"#core-func28 stream.cancel-write"))
    (export "[stream-drop-readable-2]foo" (func $"#core-func29 stream.drop-readable"))
    (export "[stream-drop-writable-2]foo" (func $"#core-func30 stream.drop-writable"))
    (export "[future-new-0]foo" (func $"#core-func31 future.new"))
    (export "[future-read-0]foo" (func $"foo:foo/bar-[future-read-0]foo"))
    (export "[future-write-0]foo" (func $"foo:foo/bar-[future-write-0]foo"))
    (export "[future-cancel-read-0]foo" (func $"#core-func34 future.cancel-read"))
    (export "[future-cancel-write-0]foo" (func $"#core-func35 future.cancel-write"))
    (export "[future-drop-readable-0]foo" (func $"#core-func36 future.drop-readable"))
    (export "[future-drop-writable-0]foo" (func $"#core-func37 future.drop-writable"))
    (export "[future-new-1]foo" (func $"#core-func38 future.new"))
    (export "[future-read-1]foo" (func $"foo:foo/bar-[future-read-1]foo"))
    (export "[future-write-1]foo" (func $"foo:foo/bar-[future-write-1]foo"))
    (export "[future-cancel-read-1]foo" (func $"#core-func41 future.cancel-read"))
    (export "[future-cancel-write-1]foo" (func $"#core-func42 future.cancel-write"))
    (export "[future-drop-readable-1]foo" (func $"#core-func43 future.drop-readable"))
    (export "[future-drop-writable-1]foo" (func $"#core-func44 future.drop-writable"))
  )
  (core func $"#core-func45 stream.new" (@name "stream.new") (;45;) (canon stream.new 3))
  (alias core export $wit-component-shim-instance "16" (core func $"[export]$root-[stream-read-2]foo" (;46;)))
  (alias core export $wit-component-shim-instance "17" (core func $"[export]$root-[stream-write-2]foo" (;47;)))
  (core func $"#core-func48 stream.cancel-read" (@name "stream.cancel-read") (;48;) (canon stream.cancel-read 3))
  (core func $"#core-func49 stream.cancel-write" (@name "stream.cancel-write") (;49;) (canon stream.cancel-write 3))
  (core func $"#core-func50 stream.drop-readable" (@name "stream.drop-readable") (;50;) (canon stream.drop-readable 3))
  (core func $"#core-func51 stream.drop-writable" (@name "stream.drop-writable") (;51;) (canon stream.drop-writable 3))
  (core func $"#core-func52 future.new" (@name "future.new") (;52;) (canon future.new 1))
  (alias core export $wit-component-shim-instance "18" (core func $"[export]$root-[future-read-0]foo" (;53;)))
  (alias core export $wit-component-shim-instance "19" (core func $"[export]$root-[future-write-0]foo" (;54;)))
  (core func $"#core-func55 future.cancel-read" (@name "future.cancel-read") (;55;) (canon future.cancel-read 1))
  (core func $"#core-func56 future.cancel-write" (@name "future.cancel-write") (;56;) (canon future.cancel-write 1))
  (core func $"#core-func57 future.drop-readable" (@name "future.drop-readable") (;57;) (canon future.drop-readable 1))
  (core func $"#core-func58 future.drop-writable" (@name "future.drop-writable") (;58;) (canon future.drop-writable 1))
  (core func $"#core-func59 future.new" (@name "future.new") (;59;) (canon future.new 2))
  (alias core export $wit-component-shim-instance "20" (core func $"[export]$root-[future-read-1]foo" (;60;)))
  (alias core export $wit-component-shim-instance "21" (core func $"[export]$root-[future-write-1]foo" (;61;)))
  (core func $"#core-func62 future.cancel-read" (@name "future.cancel-read") (;62;) (canon future.cancel-read 2))
  (core func $"#core-func63 future.cancel-write" (@name "future.cancel-write") (;63;) (canon future.cancel-write 2))
  (core func $"#core-func64 future.drop-readable" (@name "future.drop-readable") (;64;) (canon future.drop-readable 2))
  (core func $"#core-func65 future.drop-writable" (@name "future.drop-writable") (;65;) (canon future.drop-writable 2))
  (core instance $"[export]$root" (;3;)
    (export "[stream-new-2]foo" (func $"#core-func45 stream.new"))
    (export "[stream-read-2]foo" (func $"[export]$root-[stream-read-2]foo"))
    (export "[stream-write-2]foo" (func $"[export]$root-[stream-write-2]foo"))
    (export "[stream-cancel-read-2]foo" (func $"#core-func48 stream.cancel-read"))
    (export "[stream-cancel-write-2]foo" (func $"#core-func49 stream.cancel-write"))
    (export "[stream-drop-readable-2]foo" (func $"#core-func50 stream.drop-readable"))
    (export "[stream-drop-writable-2]foo" (func $"#core-func51 stream.drop-writable"))
    (export "[future-new-0]foo" (func $"#core-func52 future.new"))
    (export "[future-read-0]foo" (func $"[export]$root-[future-read-0]foo"))
    (export "[future-write-0]foo" (func $"[export]$root-[future-write-0]foo"))
    (export "[future-cancel-read-0]foo" (func $"#core-func55 future.cancel-read"))
    (export "[future-cancel-write-0]foo" (func $"#core-func56 future.cancel-write"))
    (export "[future-drop-readable-0]foo" (func $"#core-func57 future.drop-readable"))
    (export "[future-drop-writable-0]foo" (func $"#core-func58 future.drop-writable"))
    (export "[future-new-1]foo" (func $"#core-func59 future.new"))
    (export "[future-read-1]foo" (func $"[export]$root-[future-read-1]foo"))
    (export "[future-write-1]foo" (func $"[export]$root-[future-write-1]foo"))
    (export "[future-cancel-read-1]foo" (func $"#core-func62 future.cancel-read"))
    (export "[future-cancel-write-1]foo" (func $"#core-func63 future.cancel-write"))
    (export "[future-drop-readable-1]foo" (func $"#core-func64 future.drop-readable"))
    (export "[future-drop-writable-1]foo" (func $"#core-func65 future.drop-writable"))
  )
  (core func $"#core-func66 stream.new" (@name "stream.new") (;66;) (canon stream.new 3))
  (alias core export $wit-component-shim-instance "22" (core func $"[export]foo:foo/bar-[stream-read-2]foo" (;67;)))
  (alias core export $wit-component-shim-instance "23" (core func $"[export]foo:foo/bar-[stream-write-2]foo" (;68;)))
  (core func $"#core-func69 stream.cancel-read" (@name "stream.cancel-read") (;69;) (canon stream.cancel-read 3))
  (core func $"#core-func70 stream.cancel-write" (@name "stream.cancel-write") (;70;) (canon stream.cancel-write 3))
  (core func $"#core-func71 stream.drop-readable" (@name "stream.drop-readable") (;71;) (canon stream.drop-readable 3))
  (core func $"#core-func72 stream.drop-writable" (@name "stream.drop-writable") (;72;) (canon stream.drop-writable 3))
  (core func $"#core-func73 future.new" (@name "future.new") (;73;) (canon future.new 1))
  (alias core export $wit-component-shim-instance "24" (core func $"[export]foo:foo/bar-[future-read-0]foo" (;74;)))
  (alias core export $wit-component-shim-instance "25" (core func $"[export]foo:foo/bar-[future-write-0]foo" (;75;)))
  (core func $"#core-func76 future.cancel-read" (@name "future.cancel-read") (;76;) (canon future.cancel-read 1))
  (core func $"#core-func77 future.cancel-write" (@name "future.cancel-write") (;77;) (canon future.cancel-write 1))
  (core func $"#core-func78 future.drop-readable" (@name "future.drop-readable") (;78;) (canon future.drop-readable 1))
  (core func $"#core-func79 future.drop-writable" (@name "future.drop-writable") (;79;) (canon future.drop-writable 1))
  (type (;6;) (future 1))
  (core func $"#core-func80 future.new" (@name "future.new") (;80;) (canon future.new 6))
  (alias core export $wit-component-shim-instance "26" (core func $"[export]foo:foo/bar-[future-read-1]foo" (;81;)))
  (alias core export $wit-component-shim-instance "27" (core func $"[export]foo:foo/bar-[future-write-1]foo" (;82;)))
  (core func $"#core-func83 future.cancel-read" (@name "future.cancel-read") (;83;) (canon future.cancel-read 6))
  (core func $"#core-func84 future.cancel-write" (@name "future.cancel-write") (;84;) (canon future.cancel-write 6))
  (core func $"#core-func85 future.drop-readable" (@name "future.drop-readable") (;85;) (canon future.drop-readable 6))
  (core func $"#core-func86 future.drop-writable" (@name "future.drop-writable") (;86;) (canon future.drop-writable 6))
  (core instance $"[export]foo:foo/bar" (;4;)
    (export "[stream-new-2]foo" (func $"#core-func66 stream.new"))
    (export "[stream-read-2]foo" (func $"[export]foo:foo/bar-[stream-read-2]foo"))
    (export "[stream-write-2]foo" (func $"[export]foo:foo/bar-[stream-write-2]foo"))
    (export "[stream-cancel-read-2]foo" (func $"#core-func69 stream.cancel-read"))
    (export "[stream-cancel-write-2]foo" (func $"#core-func70 stream.cancel-write"))
    (export "[stream-drop-readable-2]foo" (func $"#core-func71 stream.drop-readable"))
    (export "[stream-drop-writable-2]foo" (func $"#core-func72 stream.drop-writable"))
    (export "[future-new-0]foo" (func $"#core-func73 future.new"))
    (export "[future-read-0]foo" (func $"[export]foo:foo/bar-[future-read-0]foo"))
    (export "[future-write-0]foo" (func $"[export]foo:foo/bar-[future-write-0]foo"))
    (export "[future-cancel-read-0]foo" (func $"#core-func76 future.cancel-read"))
    (export "[future-cancel-write-0]foo" (func $"#core-func77 future.cancel-write"))
    (export "[future-drop-readable-0]foo" (func $"#core-func78 future.drop-readable"))
    (export "[future-drop-writable-0]foo" (func $"#core-func79 future.drop-writable"))
    (export "[future-new-1]foo" (func $"#core-func80 future.new"))
    (export "[future-read-1]foo" (func $"[export]foo:foo/bar-[future-read-1]foo"))
    (export "[future-write-1]foo" (func $"[export]foo:foo/bar-[future-write-1]foo"))
    (export "[future-cancel-read-1]foo" (func $"#core-func83 future.cancel-read"))
    (export "[future-cancel-write-1]foo" (func $"#core-func84 future.cancel-write"))
    (export "[future-drop-readable-1]foo" (func $"#core-func85 future.drop-readable"))
    (export "[future-drop-writable-1]foo" (func $"#core-func86 future.drop-writable"))
  )
  (core instance $main (;5;) (instantiate $main
      (with "$root" (instance $$root))
      (with "foo:foo/bar" (instance $foo:foo/bar))
      (with "[export]$root" (instance $"[export]$root"))
      (with "[export]foo:foo/bar" (instance $"[export]foo:foo/bar"))
    )
  )
  (alias core export $main "memory" (core memory $memory (;0;)))
  (core module $wit-component-fixup (;2;)
    (type (;0;) (func (param i32 i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (type (;2;) (func (param i32 i32) (result i32)))
    (type (;3;) (func (param i32 i32)))
    (type (;4;) (func (param i32)))
    (import "actual" "0" (func $0 (;0;) (type 0)))
    (import "actual" "1" (func $1 (;1;) (type 0)))
    (import "actual" "2" (func $2 (;2;) (type 1)))
    (import "actual" "3" (func $3 (;3;) (type 0)))
    (import "actual" "4" (func $4 (;4;) (type 2)))
    (import "actual" "5" (func $5 (;5;) (type 2)))
    (import "actual" "6" (func $6 (;6;) (type 2)))
    (import "actual" "7" (func $7 (;7;) (type 2)))
    (import "actual" "8" (func $8 (;8;) (type 3)))
    (import "actual" "9" (func $9 (;9;) (type 0)))
    (import "actual" "10" (func $10 (;10;) (type 0)))
    (import "actual" "11" (func $11 (;11;) (type 0)))
    (import "actual" "12" (func $12 (;12;) (type 2)))
    (import "actual" "13" (func $13 (;13;) (type 2)))
    (import "actual" "14" (func $14 (;14;) (type 2)))
    (import "actual" "15" (func $15 (;15;) (type 2)))
    (import "actual" "16" (func $16 (;16;) (type 0)))
    (import "actual" "17" (func $17 (;17;) (type 0)))
    (import "actual" "18" (func $18 (;18;) (type 2)))
    (import "actual" "19" (func $19 (;19;) (type 2)))
    (import "actual" "20" (func $20 (;20;) (type 2)))
    (import "actual" "21" (func $21 (;21;) (type 2)))
    (import "actual" "22" (func $22 (;22;) (type 0)))
    (import "actual" "23" (func $23 (;23;) (type 0)))
    (import "actual" "24" (func $24 (;24;) (type 2)))
    (import "actual" "25" (func $25 (;25;) (type 2)))
    (import "actual" "26" (func $26 (;26;) (type 2)))
    (import "actual" "27" (func $27 (;27;) (type 2)))
    (import "main" "__wasm_task_hook" (func $__wasm_task_hook (;28;) (type 4)))
    (import "main" "[async-lift-stackful]foo" (func $"[async-lift-stackful]foo" (;29;) (type 3)))
    (import "main" "[async-lift-stackful]foo:foo/bar#foo" (func $"[async-lift-stackful]foo:foo/bar#foo" (;30;) (type 3)))
    (import "main" "cabi_realloc" (func $cabi_realloc (;31;) (type 1)))
    (import "shim" "$imports" (table (;0;) 28 28 funcref))
    (export "hook0" (func $"hook-[async-lift-stackful]foo"))
    (export "hook1" (func $"hook-[async-lift-stackful]foo:foo/bar#foo"))
    (export "hook2" (func $hook-cabi_realloc))
    (elem (;0;) (i32.const 0) func $0 $1 $hook-cabi_realloc $3 $4 $5 $6 $7 $8 $9 $10 $11 $12 $13 $14 $15 $16 $17 $18 $19 $20 $21 $22 $23 $24 $25 $26 $27)
    (func $"hook-[async-lift-stackful]foo" (;32;) (type 3) (param i32 i32)
      i32.const 2
      call $__wasm_task_hook
      local.get 0
      local.get 1
      call $"[async-lift-stackful]foo"
      i32.const 5
      call $__wasm_task_hook
    )
    (func $"hook-[async-lift-stackful]foo:foo/bar#foo" (;33;) (type 3) (param i32 i32)
      i32.const 2
      call $__wasm_task_hook
      local.get 0
      local.get 1
      call $"[async-lift-stackful]foo:foo/bar#foo"
      i32.const 5
      call $__wasm_task_hook
    )
    (func $hook-cabi_realloc (;34;) (type 1) (param i32 i32 i32 i32) (result i32)
      i32.const 12
      call $__wasm_task_hook
      local.get 0
      local.get 1
      local.get 2
      local.get 3
      call $cabi_realloc
      i32.const 13
      call $__wasm_task_hook
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core func $"#core-func87 indirect-$root-[async-lower]foo" (@name "indirect-$root-[async-lower]foo") (;87;) (canon lower (func $foo) (memory $memory) async))
  (alias core export $wit-component-shim-instance "2" (core func $realloc-main-cabi_realloc (;88;)))
  (core func $stream.read (;89;) (canon stream.read 3 (memory $memory) (realloc $realloc-main-cabi_realloc) string-encoding=utf8))
  (alias core export $main "cabi_realloc" (core func $cabi_realloc (;90;)))
  (core func $stream.write (;91;) (canon stream.write 3 (memory $memory) string-encoding=utf8))
  (core func $future.read (;92;) (canon future.read 1 (memory $memory)))
  (core func $future.write (;93;) (canon future.write 1 (memory $memory)))
  (core func $"#core-func94 future.read" (@name "future.read") (;94;) (canon future.read 2 (memory $memory)))
  (core func $"#core-func95 future.write" (@name "future.write") (;95;) (canon future.write 2 (memory $memory)))
  (core func $error-context.debug-message (;96;) (canon error-context.debug-message (memory $memory) (realloc $realloc-main-cabi_realloc) string-encoding=utf8))
  (alias export $foo:foo/bar "foo" (func $"#func1 foo" (@name "foo") (;1;)))
  (core func $"#core-func97 indirect-foo:foo/bar-[async-lower]foo" (@name "indirect-foo:foo/bar-[async-lower]foo") (;97;) (canon lower (func $"#func1 foo") (memory $memory) async))
  (core func $"#core-func98 stream.read" (@name "stream.read") (;98;) (canon stream.read 3 (memory $memory) (realloc $realloc-main-cabi_realloc) string-encoding=utf8))
  (core func $"#core-func99 stream.write" (@name "stream.write") (;99;) (canon stream.write 3 (memory $memory) string-encoding=utf8))
  (core func $"#core-func100 future.read" (@name "future.read") (;100;) (canon future.read 1 (memory $memory)))
  (core func $"#core-func101 future.write" (@name "future.write") (;101;) (canon future.write 1 (memory $memory)))
  (core func $"#core-func102 future.read" (@name "future.read") (;102;) (canon future.read 5 (memory $memory)))
  (core func $"#core-func103 future.write" (@name "future.write") (;103;) (canon future.write 5 (memory $memory)))
  (core func $"#core-func104 stream.read" (@name "stream.read") (;104;) (canon stream.read 3 (memory $memory) (realloc $realloc-main-cabi_realloc) string-encoding=utf8))
  (core func $"#core-func105 stream.write" (@name "stream.write") (;105;) (canon stream.write 3 (memory $memory) string-encoding=utf8))
  (core func $"#core-func106 future.read" (@name "future.read") (;106;) (canon future.read 1 (memory $memory)))
  (core func $"#core-func107 future.write" (@name "future.write") (;107;) (canon future.write 1 (memory $memory)))
  (core func $"#core-func108 future.read" (@name "future.read") (;108;) (canon future.read 2 (memory $memory)))
  (core func $"#core-func109 future.write" (@name "future.write") (;109;) (canon future.write 2 (memory $memory)))
  (core func $"#core-func110 stream.read" (@name "stream.read") (;110;) (canon stream.read 3 (memory $memory) (realloc $realloc-main-cabi_realloc) string-encoding=utf8))
  (core func $"#core-func111 stream.write" (@name "stream.write") (;111;) (canon stream.write 3 (memory $memory) string-encoding=utf8))
  (core func $"#core-func112 future.read" (@name "future.read") (;112;) (canon future.read 1 (memory $memory)))
  (core func $"#core-func113 future.write" (@name "future.write") (;113;) (canon future.write 1 (memory $memory)))
  (core func $"#core-func114 future.read" (@name "future.read") (;114;) (canon future.read 6 (memory $memory)))
  (core func $"#core-func115 future.write" (@name "future.write") (;115;) (canon future.write 6 (memory $memory)))
  (core instance $actual (;6;)
    (export "0" (func $"#core-func87 indirect-$root-[async-lower]foo"))
    (export "1" (func $stream.read))
    (export "2" (func $cabi_realloc))
    (export "3" (func $stream.write))
    (export "4" (func $future.read))
    (export "5" (func $future.write))
    (export "6" (func $"#core-func94 future.read"))
    (export "7" (func $"#core-func95 future.write"))
    (export "8" (func $error-context.debug-message))
    (export "9" (func $"#core-func97 indirect-foo:foo/bar-[async-lower]foo"))
    (export "10" (func $"#core-func98 stream.read"))
    (export "11" (func $"#core-func99 stream.write"))
    (export "12" (func $"#core-func100 future.read"))
    (export "13" (func $"#core-func101 future.write"))
    (export "14" (func $"#core-func102 future.read"))
    (export "15" (func $"#core-func103 future.write"))
    (export "16" (func $"#core-func104 stream.read"))
    (export "17" (func $"#core-func105 stream.write"))
    (export "18" (func $"#core-func106 future.read"))
    (export "19" (func $"#core-func107 future.write"))
    (export "20" (func $"#core-func108 future.read"))
    (export "21" (func $"#core-func109 future.write"))
    (export "22" (func $"#core-func110 stream.read"))
    (export "23" (func $"#core-func111 stream.write"))
    (export "24" (func $"#core-func112 future.read"))
    (export "25" (func $"#core-func113 future.write"))
    (export "26" (func $"#core-func114 future.read"))
    (export "27" (func $"#core-func115 future.write"))
  )
  (core instance $fixup (;7;) (instantiate $wit-component-fixup
      (with "actual" (instance $actual))
      (with "main" (instance $main))
      (with "shim" (instance $wit-component-shim-instance))
    )
  )
  (alias core export $fixup "hook0" (core func $hook0 (;116;)))
  (alias core export $fixup "hook1" (core func $hook1 (;117;)))
  (alias core export $fixup "hook2" (core func $hook2 (;118;)))
  (func $"#func2 foo" (@name "foo") (;2;) (type 4) (canon lift (core func $hook0) async))
  (export $"#func3 foo" (@name "foo") (;3;) "foo" (func $"#func2 foo"))
  (type (;7;) (func async (param "x" 6) (param "y" u32) (result 3)))
  (func $"#func4 foo" (@name "foo") (;4;) (type 7) (canon lift (core func $hook1) async))
  (component $foo:foo/bar-shim-component (;0;)
    (type (;0;) (future u32))
    (type (;1;) (future 0))
    (type (;2;) (stream string))
    (type (;3;) (func async (param "x" 1) (param "y" u32) (result 2)))
    (import "import-func-foo" (func (;0;) (type 3)))
    (type (;4;) (future u32))
    (type (;5;) (future 4))
    (type (;6;) (stream string))
    (type (;7;) (func async (param "x" 5) (param "y" u32) (result 6)))
    (export (;1;) "foo" (func 0) (func (type 7)))
  )
  (instance $foo:foo/bar-shim-instance (;1;) (instantiate $foo:foo/bar-shim-component
      (with "import-func-foo" (func $"#func4 foo"))
    )
  )
  (export $"#instance2 foo:foo/bar" (@name "foo:foo/bar") (;2;) "foo:foo/bar" (instance $foo:foo/bar-shim-instance))
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
