(module
  (func (import "$root" "[async]foo") (param i32 i32) (result i32))
  (func (import "foo:foo/bar" "[async]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]$root" "[stream-new-2]foo") (result i32))
  (func (import "[import-payload]$root" "[stream-read-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[import-payload]$root" "[stream-write-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[import-payload]$root" "[stream-cancel-read-2]foo") (param i32) (result i32))
  (func (import "[import-payload]$root" "[stream-cancel-write-2]foo") (param i32) (result i32))
  (func (import "[import-payload]$root" "[stream-close-readable-2]foo") (param i32))
  (func (import "[import-payload]$root" "[stream-close-writable-2]foo") (param i32 i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-new-2]foo") (result i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-read-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-write-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-cancel-read-2]foo") (param i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-cancel-write-2]foo") (param i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-close-readable-2]foo") (param i32))
  (func (import "[import-payload]foo:foo/bar" "[stream-close-writable-2]foo") (param i32 i32))
  (func (import "[import-payload]$root" "[future-new-0]foo") (result i32))
  (func (import "[import-payload]$root" "[future-read-0]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]$root" "[future-write-0]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]$root" "[future-cancel-read-0]foo") (param i32) (result i32))
  (func (import "[import-payload]$root" "[future-cancel-write-0]foo") (param i32) (result i32))
  (func (import "[import-payload]$root" "[future-close-readable-0]foo") (param i32))
  (func (import "[import-payload]$root" "[future-close-writable-0]foo") (param i32 i32))
  (func (import "[import-payload]foo:foo/bar" "[future-new-0]foo") (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-read-0]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-write-0]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-cancel-read-0]foo") (param i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-cancel-write-0]foo") (param i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-close-readable-0]foo") (param i32))
  (func (import "[import-payload]foo:foo/bar" "[future-close-writable-0]foo") (param i32 i32))
  (func (import "[import-payload]$root" "[future-new-1]foo") (result i32))
  (func (import "[import-payload]$root" "[future-read-1]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]$root" "[future-write-1]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]$root" "[future-cancel-read-1]foo") (param i32) (result i32))
  (func (import "[import-payload]$root" "[future-cancel-write-1]foo") (param i32) (result i32))
  (func (import "[import-payload]$root" "[future-close-readable-1]foo") (param i32))
  (func (import "[import-payload]$root" "[future-close-writable-1]foo") (param i32 i32))
  (func (import "[import-payload]foo:foo/bar" "[future-new-1]foo") (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-read-1]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-write-1]foo") (param i32 i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-cancel-read-1]foo") (param i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-cancel-write-1]foo") (param i32) (result i32))
  (func (import "[import-payload]foo:foo/bar" "[future-close-readable-1]foo") (param i32))
  (func (import "[import-payload]foo:foo/bar" "[future-close-writable-1]foo") (param i32 i32))
  (func (import "[export-payload]$root" "[stream-new-2]foo") (result i32))
  (func (import "[export-payload]$root" "[stream-read-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[export-payload]$root" "[stream-write-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[export-payload]$root" "[stream-cancel-read-2]foo") (param i32) (result i32))
  (func (import "[export-payload]$root" "[stream-cancel-write-2]foo") (param i32) (result i32))
  (func (import "[export-payload]$root" "[stream-close-readable-2]foo") (param i32))
  (func (import "[export-payload]$root" "[stream-close-writable-2]foo") (param i32 i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-new-2]foo") (result i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-read-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-write-2]foo") (param i32 i32 i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-cancel-read-2]foo") (param i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-cancel-write-2]foo") (param i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-close-readable-2]foo") (param i32))
  (func (import "[export-payload]foo:foo/bar" "[stream-close-writable-2]foo") (param i32 i32))
  (func (import "[export-payload]$root" "[future-new-0]foo") (result i32))
  (func (import "[export-payload]$root" "[future-read-0]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]$root" "[future-write-0]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]$root" "[future-cancel-read-0]foo") (param i32) (result i32))
  (func (import "[export-payload]$root" "[future-cancel-write-0]foo") (param i32) (result i32))
  (func (import "[export-payload]$root" "[future-close-readable-0]foo") (param i32))
  (func (import "[export-payload]$root" "[future-close-writable-0]foo") (param i32 i32))
  (func (import "[export-payload]foo:foo/bar" "[future-new-0]foo") (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-read-0]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-write-0]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-cancel-read-0]foo") (param i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-cancel-write-0]foo") (param i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-close-readable-0]foo") (param i32))
  (func (import "[export-payload]foo:foo/bar" "[future-close-writable-0]foo") (param i32 i32))
  (func (import "[export-payload]$root" "[future-new-1]foo") (result i32))
  (func (import "[export-payload]$root" "[future-read-1]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]$root" "[future-write-1]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]$root" "[future-cancel-read-1]foo") (param i32) (result i32))
  (func (import "[export-payload]$root" "[future-cancel-write-1]foo") (param i32) (result i32))
  (func (import "[export-payload]$root" "[future-close-readable-1]foo") (param i32))
  (func (import "[export-payload]$root" "[future-close-writable-1]foo") (param i32 i32))
  (func (import "[export-payload]foo:foo/bar" "[future-new-1]foo") (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-read-1]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-write-1]foo") (param i32 i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-cancel-read-1]foo") (param i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-cancel-write-1]foo") (param i32) (result i32))
  (func (import "[export-payload]foo:foo/bar" "[future-close-readable-1]foo") (param i32))
  (func (import "[export-payload]foo:foo/bar" "[future-close-writable-1]foo") (param i32 i32))
  (func (export "[async]foo") (param i32 i32) (result i32) unreachable)
  (func (export "[async]foo:foo/bar#foo") (param i32 i32) (result i32) unreachable)
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
)
