// parse-fail

package a:b0 {
package a:b1 {
package a:b2 {
package a:b3 {
package a:b4 {
package a:b5 {
package a:b6 {
package a:b7 {
package a:b8 {
package a:b9 {
package a:b10 {
package a:b11 {
package a:b12 {
package a:b13 {
package a:b14 {
package a:b15 {
package a:b16 {
package a:b17 {
package a:b18 {
package a:b19 {
package a:b20 {
package a:b21 {
package a:b22 {
package a:b23 {
package a:b24 {
package a:b25 {
package a:b26 {
package a:b27 {
package a:b28 {
package a:b29 {
package a:b30 {
package a:b31 {
package a:b32 {
package a:b33 {
package a:b34 {
package a:b35 {
package a:b36 {
package a:b37 {
package a:b38 {
package a:b39 {
package a:b40 {
package a:b41 {
package a:b42 {
package a:b43 {
package a:b44 {
package a:b45 {
package a:b46 {
package a:b47 {
package a:b48 {
package a:b49 {
package a:b50 {
package a:b51 {
package a:b52 {
package a:b53 {
package a:b54 {
package a:b55 {
package a:b56 {
package a:b57 {
package a:b58 {
package a:b59 {
package a:b60 {
package a:b61 {
package a:b62 {
package a:b63 {
package a:b64 {
package a:b65 {
package a:b66 {
package a:b67 {
package a:b68 {
package a:b69 {
package a:b70 {
package a:b71 {
package a:b72 {
package a:b73 {
package a:b74 {
package a:b75 {
package a:b76 {
package a:b77 {
package a:b78 {
package a:b79 {
package a:b80 {
package a:b81 {
package a:b82 {
package a:b83 {
package a:b84 {
package a:b85 {
package a:b86 {
package a:b87 {
package a:b88 {
package a:b89 {
package a:b90 {
package a:b91 {
package a:b92 {
package a:b93 {
package a:b94 {
package a:b95 {
package a:b96 {
package a:b97 {
package a:b98 {
package a:b99 {
package a:b100 {
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
}
