// parse-fail

package foo:foo;

interface foo {
  type t =
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    list<
    u8
    >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>;
}
