interface a1 { }
interface a2 { }

world my-world-a {
    import a: self.a1
}

world my-world-b {
    import a: self.a2
}

world union-my-world {
    include self.my-world-a
    include self.my-world-b
}
