# Publication of the `main` branch.
#
# Commits to `main` go through the merge queue first to produce artifacts and
# test results. If a special commit marker is found then a publish is made.

name: Publish Artifacts
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  create_tag:
    name: Publish artifacts of build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - uses: ./.github/actions/publish-release
      with:
        cargo_token: ${{ secrets.CARGO_REGISTRY_TOKEN }}
