# Publication of the `main` branch.
#
# Commits to `main` go through the merge queue first to produce artifacts and
# test results. If a special commit marker is found then a publish is made.

name: Publish Artifacts
on:
  push:
    branches: [main]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  create_tag:
    name: Publish artifacts of build
    runs-on: ubuntu-latest
    environment: release
    if: |
      github.repository_owner == 'bytecodealliance'
      && github.event_name == 'push'
      && github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v5
      with:
        submodules: true
        fetch-depth: 0
    - uses: ./.github/actions/publish-release
