(component
  (type (;0;)
    (instance
      (type (;0;) (func (param "s" string) (result string)))
      (export (;0;) "foo" (func (type 0)))
    )
  )
  (import "foo:foo/bar" (instance (;0;) (type 0)))
  (type (;1;) (func (param "s" string) (result string)))
  (import "foo" (func (;0;) (type 1)))
  (core module (;0;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (type (;1;) (func (param i32 i32 i32 i32) (result i32)))
    (import "$root" "[async]foo" (func (;0;) (type 0)))
    (import "foo:foo/bar" "[async]foo" (func (;1;) (type 0)))
    (memory (;0;) 1)
    (export "memory" (memory 0))
    (export "cabi_realloc" (func 2))
    (func (;2;) (type 1) (param i32 i32 i32 i32) (result i32)
      unreachable
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
      (processed-by "my-fake-bindgen" "123.45")
    )
  )
  (core module (;1;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (table (;0;) 2 2 funcref)
    (export "0" (func $"indirect-$root-[async]foo"))
    (export "1" (func $"indirect-foo:foo/bar-[async]foo"))
    (export "$imports" (table 0))
    (func $"indirect-$root-[async]foo" (;0;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 0
      call_indirect (type 0)
    )
    (func $"indirect-foo:foo/bar-[async]foo" (;1;) (type 0) (param i32 i32) (result i32)
      local.get 0
      local.get 1
      i32.const 1
      call_indirect (type 0)
    )
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core module (;2;)
    (type (;0;) (func (param i32 i32) (result i32)))
    (import "" "0" (func (;0;) (type 0)))
    (import "" "1" (func (;1;) (type 0)))
    (import "" "$imports" (table (;0;) 2 2 funcref))
    (elem (;0;) (i32.const 0) func 0 1)
    (@producers
      (processed-by "wit-component" "$CARGO_PKG_VERSION")
    )
  )
  (core instance (;0;) (instantiate 1))
  (alias core export 0 "0" (core func (;0;)))
  (core instance (;1;)
    (export "[async]foo" (func 0))
  )
  (alias core export 0 "1" (core func (;1;)))
  (core instance (;2;)
    (export "[async]foo" (func 1))
  )
  (core instance (;3;) (instantiate 0
      (with "$root" (instance 1))
      (with "foo:foo/bar" (instance 2))
    )
  )
  (alias core export 3 "memory" (core memory (;0;)))
  (alias core export 0 "$imports" (core table (;0;)))
  (alias core export 3 "cabi_realloc" (core func (;2;)))
  (core func (;3;) (canon lower (func 0) (memory 0) (realloc 2) string-encoding=utf8 async))
  (alias export 0 "foo" (func (;1;)))
  (core func (;4;) (canon lower (func 1) (memory 0) (realloc 2) string-encoding=utf8 async))
  (core instance (;4;)
    (export "$imports" (table 0))
    (export "0" (func 3))
    (export "1" (func 4))
  )
  (core instance (;5;) (instantiate 2
      (with "" (instance 4))
    )
  )
  (@producers
    (processed-by "wit-component" "$CARGO_PKG_VERSION")
  )
)
