(module
  (import "foo" "foo1: func() -> ()" (func))
  (import "foo" "foo2: func(x: u8) -> ()" (func (param i32)))
  (import "foo" "foo3: func(x: float32) -> ()" (func (param f32)))
  (import "bar" "bar1: func(x: string) -> ()" (func (param i32 i32)))
  (import "bar" "bar2: func(x: record { a: u8 }) -> ()" (func (param i32)))
  (import "baz" "baz1: func(x: list<string>) -> ()" (func (param i32 i32)))
  (import "baz" "baz2: func() -> ()" (func))
  (import "baz" "baz3: func(x: s8) -> ()" (func (param i32)))
  (memory (export "memory") 1)
  (func (export "cabi_realloc") (param i32 i32 i32 i32) (result i32) unreachable)
)